### ISSUE TITLE
ScrollTop (Issue) with Anchor Links

### ISSUE THREAD

**Issue by codebakery-ch** [noraesae/perfect-scrollbar#134]
This is expected, but I am not really sure on how to work around this:

I have made page with anchor Links. To make this work, I (at least I think I do) need to make a little onClick event
```Javascript
  $(element).click(function (event) {
                event.preventDefault();
                var id = attrs.href;
                var pos = $(id).offset().top;
                console.log(id);
                console.log(pos);
                $('.scrollarea').animate({
                     scrollTop: $(id).offset().top
                 }, 1000);
                $('.scrollarea').perfectScrollbar('update');
});
```

The Problem is when I let it scroll Down, the top of ScrollArea gets a 0 value, so if I click that anchor again, it scrolls up the area (instead of staying at this point, because the top position has been overwriiten). If I click another anchor (above the selected one) it scrolls up, but the position has a negative value now, so the position for scrolling down is too ~~high~~ low.

Maybe there is a nicer workaround if you can include this directly into your plugin.

Ninja Edit: Sorry if this is a duplicate!

**Comment by noraesae** [comment]
Very sorry that there has been no update on this thread. It may have been a timing issue, so the update call should be done after the animation finished.

**Comment by codebakery-ch** [comment]
no Prob, but I started to use this quite frequently. Works like a charm :)

**Comment by YossiCohen** [comment]
Can you share an example of using the scrollbar with angular + anchor support please?
