### ISSUE TITLE
Add a scrollBy option

### ISSUE THREAD

**Issue by Aedaeum** [noraesae/perfect-scrollbar#137]
It would be nice to scroll the content by a specific amount of pixels. I have a list of items which are scrollable via perfectScrollbar and they are all a fixed height. Because they are a fixed height, I can set a scrollBy value, which when the mouse wheel is used, will scroll by one item at a time, instead of an arbitrary "speed" amount.

Thanks :smile:

**Comment by noraesae** [comment]
Closed for the inactivity. I'll open it when I need to implement it.

Thanks

**Comment by trompx** [comment]
I'll be very interested to have this option too.
@Aedaeum did you have the time to work on this ?
