### ISSUE TITLE
Zoom 110% shows scrollbar even if not needed

### ISSUE THREAD

**Issue by eranaorato** [noraesae/perfect-scrollbar#147]
Hi,
I have found an issue with chrome and zoom at 100%. When having a prefect scroll bar plugin invoked on a list that is in the same size of the container the scroll bar appears - while in 100% zoom (or any other zoom percentage) it doesn't.
Did anyone noticed this issue before?

Thanks,
Eran

**Comment by noraesae** [comment]
Closed for the several fixes have been applied to the calculation logic, and not sure if it's still an issue.

Please feel free to reopen.
