### ISSUE TITLE
Perfect scrollbar stop working if the container html is updated.

### ISSUE THREAD

**Issue by alexforever86** [noraesae/perfect-scrollbar#158]
The container, in which the perfect-scrollbar is initialized, needs to be updated many times. When I remove the html in the container, the x-rail and y-rail elements will also be removed. If I try to update the perfect-scrollbar in the container after this, nothing happens.
It would be great to check for this elements if($('.ps-scrollbar-y-rail').length>0) rather than just checking whether there is  'perfect-scrollbar' data attribute to the container element and to append this if not present.

**Comment by noraesae** [comment]
Fixed with 2930041597fa5847414cef0fc63a36c3374ab9de.
Cheers,

**Comment by alexforever86** [comment]
Thanks
