### ISSUE TITLE
PS conflict with FastClick

### ISSUE THREAD

**Issue by Ironshu** [noraesae/perfect-scrollbar#171]
Perfect scrollbar does not play nice with the fastclick plugin on iOS. Fastclick requires two clicks instead of one with ps enabled on iOS. I'm not 100% sure which plugin is the culprit, but my guess is ps. My solution (for now) is to disable ps on iOS, however I would prefer not to do so.

**Comment by noraesae** [comment]
Thanks guys.

**Comment by sferoze** [comment]
I am having this issue right now. I am added the class `needsclick` class but it still does not work. 

Right now if I use perfect scroll on mobile, it requires a double tap to click any link. Please help
