### ISSUE TITLE
Jumpy scrolling for horizontal scrollbar

### ISSUE THREAD

**Issue by alexforever86** [noraesae/perfect-scrollbar#199]
I'm implementing a horizontal scrollbar for an iframe. I got this issue in Firefox 31.0/Ubuntu 12.04.
When the mouse goes out of scroll rail, the scrolling stops and jump to the position when the mouse comes back to scroll rail. How to fix this issue?

**Comment by noraesae** [comment]
Maybe related to #98 and #210.  Basically Firefox doesn't propagate the wheel event from iframe to its container, according to [this bugzilla thread](https://bugzilla.mozilla.org/show_bug.cgi?id=1084121). It seems that they don't have any plan to update in the near future. Now sure if the plugin should handle this as it's quite tricky to implement what a browser doesn't support natively.

Sorry for the inconvenience and the late response.
