### ISSUE TITLE
Overflow Issue for css Elements

### ISSUE THREAD

**Issue by kifayat** [noraesae/perfect-scrollbar#204]
I Use Version 0.4.11. which has issues on some of my DIVs.
actually i have some divs with Overflow :hidden, and then i have some mouse hover effects for some elements. 
The problem is if I do not apply the perfect-scrollbar every thing looks perfect, and as i wanted, but when i bind the perfect-scrollbar to it, the positions of the elements changes on mouse hover. as those elements are suppose to come out of the overflow:hidden div.
Need fix for this, please help.

**Comment by noraesae** [comment]
Recently I've found a bug in the RTL support in Chrome, and fixed it. It'll be applied in the next version. If you find the problem again, please feel free to let me know.

Cheers,
