### ISSUE TITLE
scrollbar's thumb is not shown properly

### ISSUE THREAD

**Issue by a3gmnr** [noraesae/perfect-scrollbar#208]
> railBorderXWidth = parseInt($scrollbarXRail.css('borderLeftWidth'), 10) + parseInt($scrollbarXRail.css('borderRightWidth'), 10),
> railBorderYWidth = parseInt($scrollbarXRail.css('borderTopWidth'), 10) + parseInt($scrollbarXRail.css('borderBottomWidth'), 10);

in some situnations, $scrollbarXRail.css('borderLeftWidth') returns empty string(""). so the railBorderXWidth and railBorderYWidth become NaN. this can cause calculation errors for thumb's height.

thank you.

**Comment by noraesae** [comment]
Hiya,

Thanks for the report and sorry for the late response. In the next refactored version, #277, `$.css` isn't used and is replaced with a native method, so I guess the problem will be fixed along with the change. If there's any further problem, feel free to tell me again.

Cheers,
