### ISSUE TITLE
.perfectScrollbar("update") not updating scrollbar

### ISSUE THREAD

**Issue by julmot** [noraesae/perfect-scrollbar#220]
Hi,

I have a navigation-panel which uses the perfectScrollbar. After some elements were removed in the navigation the scrollbar should disappear. But for some reasons it still appears, only after scrolling it will disappear. I have ensured that the update call was made, so this could not be the problem. Also I have checked that my elements have the same position and nested divs like in the examples. What could cause this problem?

What fixed my problem for now (no solution for a "perfect" scrollbar): use the destroy-function and init the plugin again instead of using update.

**Comment by varffs** [comment]
I had a similar issue with 0.5.8. `update` wasn't working but I just tried `destroy` and then re-initializing and it is now working. I had a div with content which was then removed and replaced with new content by an ajax load. I was waiting until images were loaded before calling `update`.

**Comment by julmot** [comment]
As this issue is long enouth open and the bug is not solved for me I switched to another scrollbar plugin. Now it's working as expected.

**Comment by FDiskas** [comment]
What plugin?

**Comment by julmot** [comment]
https://github.com/gromo/jquery.scrollbar

**Comment by medBouzid** [comment]
I was struggling with this issue recently and I downloaded the latest version which is at this time **0.6.11** and it seems fixing the problem for me. Give it a try :)

**Comment by azharuniverse** [comment]
I am also having this issue. Stuck on this for hours.
