### ISSUE TITLE
Does not work in Windows Phone 8.1 Internet Explorer

### ISSUE THREAD

**Issue by alensaqe** [noraesae/perfect-scrollbar#229]
The plugin does not work at all on Nokia Lumia 520 WP 8.1 Internet Explorer.

**Comment by martijnrusschen** [comment]
Any update about this?

**Comment by noraesae** [comment]
There comes a patch about MS touch devices, d6bd30f2daf677d1d56541df784654e47ab86087.

Will close for a while, but feel free to reopen.
