### ISSUE TITLE
Can I use multiple perfectScrollbar on same page?

### ISSUE THREAD

**Issue by mrrtee** [noraesae/perfect-scrollbar#246]
I have multiple div in the page, I assign script perfectScrollbar,. It seems to be work, it can render graphic scrollbar, but it cannot scroll up/down inside each boxes...

How do I resolve it ?

**Comment by noraesae** [comment]
Closed, as it seems resolved for the time being.

Cheers,

**Comment by StSenf** [comment]
Just in case anyone stumbles over this question with the newer version of this plugin - this is a working example:

`$('.dialogInner').each(function(){
        const ps = new PerfectScrollbar($(this)[0]);
    });`

**Comment by vm-bio** [comment]
Ich bin von Di, 09.01.2018 bis Mi, 21.02.2018 abwesend.




Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[utatti/perfect-scrollbar] Can I use multiple perfectScrollbar on same
page? (#246)" gesendet am 11.01.2018 13:22:28.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

www.biotronik.com 
BIOTRONIK - excellence for life 

BIOTRONIK SE & Co. KG 
Woermannkehre 1, 12359 Berlin, Germany 
Sitz der Gesellschaft: Berlin, Registergericht: Berlin HRA 6501 

Vertreten durch ihre Komplementärin: 
BIOTRONIK MT SE 
Sitz der Gesellschaft: Berlin, Registergericht: Berlin HRB 118866 B 
Geschäftsführende Direktoren: Dr. Daniel Bühler, Dr. Lothar Krings, Dr. Ralf Lieb, Thomas Simmerer 
This e-mail and the information it contains including attachments are confidential and meant only for use by the intended recipient(s); disclosure or copying is strictly prohibited. If you are not addressed, but in the possession of this e-mail, please notify the sender immediately and delete the document.

**Comment by theshashiverma** [comment]
@StSenf Thank you so much brother that works for me.

**Comment by starkana** [comment]
@StSenf how would I add the new PerfectScrollbar object to $(this) so I can access it later and perform an ps.update() when the scroll area content changes?

I tried $(this).ps = new PerfectScrollbar(...) but that does not work =/

**Comment by liza-demyanovska** [comment]
@StSenf
thank's!!!
