### ISSUE TITLE
Mobile Issue: The scrollTop function will not execute unless you move the scroller container.

### ISSUE THREAD

**Issue by bcgoodmate** [noraesae/perfect-scrollbar#248]
$("#Demo").scrollTop(0);
$("#Demo").perfectScrollbar('update');

The scrollTop function will not execute unless you move the scroller container in touch devices, but it's OK on desktop. What do you think is reason behind this problem?

You can see it from here http://jrkiosk.businesscatalyst.com/_source/browse-our-range.html under BRANDS menu item.

**Comment by noraesae** [comment]
First of all, sorry for the late response. I guess it's a timing issue of calculating the geometries of the container, but I'm not sure as the example seems not working anymore.


If possible, please specify the situation, or provide the example again? I'll leave the issue for a while.

Thanks.

**Comment by noraesae** [comment]
Closed for the inactivity. Feel free to reopen.
