### ISSUE TITLE
suppressScrollX is true -> empty page

### ISSUE THREAD

**Issue by ronihcohen** [noraesae/perfect-scrollbar#249]
When suppressScrollX is true and the content somehow moved  to the right  while using google-charts (I am not sure how and when), 
I got an empty page,  the solution for this problem was to remove the line:
$this.scrollLeft(0);
from updateGeometry()  function.

**Comment by noraesae** [comment]
Hmm, actually not sure how it happens, but guess that it's possible to happen. Anyway, if I can have an example to reproduce the problem, it would really help me narrow down the reason.

Anyway, very sorry for the late response.

**Comment by noraesae** [comment]
Will close for the inactivity. Please feel free to reopen.
