### ISSUE TITLE
How to use perfect-scrollbar for a table?

### ISSUE THREAD

**Issue by julmot** [noraesae/perfect-scrollbar#256]
I would like to add the perfect-scrollbar to a table to allow the user vertical scrolling. I didn't find a example for this, so @noraesae is there a way and if so, how?

**Comment by mkoryak** [comment]
I just added support for this plugin to my locked table header plugin. See:
http://mkoryak.github.io/floatThead/examples/perfect-scrollbar/

**Comment by julmot** [comment]
@mkoryak What does "thead" mean?
Seems to be a cool plugin. However, I have multiple problems with perfect-scrollbar on mobile devices so maybe I'll take a look to your plugin but without perfect-scrollbar.

**Comment by mkoryak** [comment]
thead refers to the `<thead>` within the table. the thing that is floated.

**Comment by noraesae** [comment]
As I said, `tbody` and `table` are not typical container elements. You can find many answers to make it scroll, changing their `display` style. For example, [this](http://stackoverflow.com/questions/17067294/html-table-with-100-width-with-vertical-scroll-inside-tbody). It means, if you add `display: block`, you can make it work. I've added an example for table content, so if still interested, please check it out.

Cheers,

**Comment by Vaibhav2812** [comment]
I want to use the scrollbar over the whole `<tbody>`-tag. for Angular App.

**Comment by IMMANISHBANSAL** [comment]
It is very easy to use perfect scrollbar at prime ng/ any other table.
**Use two tables**
1. For table header
2. For table body

We need to take care of the width of the header columns and table body columns in case if we are having different width of the columns .

<div>
   <div>
      <p-table>
         <ng-template pTemplate="header">
            <tr>
               <th class="width-40px">Column 1</th>
               <th>Column 2</th>
			   <th>Column 3</th>            
            </tr>
         </ng-template>
      </p-table>
   </div>
   <perfect-scrollbar>
      <div style="max-height: 300px;">
         <p-table [value]="tableData">
            <ng-template pTemplate="body" let-tableData>
               <tr>
                  <td class="width-40px">tableData.id</td>
                  <td>tableData.firstName</td>
                  <td>tableData.lastName</td>
               </tr>
            </ng-template>

            <ng-template pTemplate="emptymessage" let-columns>
               <tr>
                  <td class="text-align-center" colspan="3">
                     <div>Loading data.. Please wait...</div>
                  </td>
               </tr>
            </ng-template>
         </p-table>
      </div>
   </perfect-scrollbar>
</div>
