### ISSUE TITLE
Scroll bar's position doesn't stay steady while scrolling in IE 11.

### ISSUE THREAD

**Issue by walkingp** [noraesae/perfect-scrollbar#260]
Even the official demo also exists this issue, the scroll bar will go to the top position then go to correct position when it approaches the bottom.

**Comment by noraesae** [comment]
Redirected into #160. I'm really sorry for the inconvenience, but because of my shortage of environment and time, the process hasn't be very quick. I'll try to do it asap.

Cheers,
