### ISSUE TITLE
Using with a List

### ISSUE THREAD

**Issue by phillafrance** [noraesae/perfect-scrollbar#262]
Is it possible to get this to work on a list? I have a <ul> that I can't seem to get this to work for. I am able to get the scrollbar-y-rail to show up when you hover over the list but scrolling on it does not work. I am also unable to click on the little scrollbar-y cursor and drag it up or down.

**Comment by DanielApt** [comment]
Have you met all requirements?
* the container must have a 'position' css style.
* the container must have an 'overflow:hidden' css style.
* the scrollbar's position must be 'absolute'.
* the scrollbar-x must have a 'bottom' css style, and the scrollbar-y must have a 'right' css style.

If you have, and it still isn't working, could you maybe create an example?

**Comment by noraesae** [comment]
A working example of `ul` and `li` elements is `examples/text-content.html`. If there's any further issue you face, feel free to let me know.

Cheers,
