### ISSUE TITLE
Have you considered highlighting during :active?

### ISSUE THREAD

**Issue by MeoMix** [noraesae/perfect-scrollbar#264]
Hey there,

Thanks for the plugin. I'm just getting started using it and am customizing it to my needs. It seems to work very well!

One thought -- I'm adding the following rule to CSS and was wondering why you didn't have it:

.ps-scrollbar-y-rail:active > .ps-scrollbar-y {
    background-color: #999;
}

I think that this makes sense because when the user is mousedown on scrollbar, but moves mouse out of hovering, it is still possible to drag the scrollbar but there is no visual indicator that this is happening.

**Comment by noraesae** [comment]
Closed for the time being. Thanks for the suggestion!
