### ISSUE TITLE
Elements in scrolled container trigger :hover in 3px gap between scrollbarRail and side

### ISSUE THREAD

**Issue by MeoMix** [noraesae/perfect-scrollbar#266]
Hey,

In your code you have:

    .ps-scrollbar-y-rail {
        right: 3px;
    }

    .ps-scrollbar-y {
        right: 0;
    }

This gives 3px gap between side and scrollbar. This looks good visually, but, when mousing over that edge, elements with width: 100% trigger :hover.

I don't think this is very intuitive. Usually there is no possibility of hovering between the scrollbar and the edge of the content. So, I changed your code to:

    .ps-scrollbar-y-rail {
        right: 0;
    }

    .ps-scrollbar-y {
        right: 3px;
    }

Which fixed this for my project.

However, this is still not 100% perfect solution because now :hover effects for ps-scrollbar-y-rail trigger even when the mouse is not visually over the scrollbar area.

Here's a video showing issue: http://screencast.com/t/te30QrxsvPB

**Comment by noraesae** [comment]
Closed for the inactivity and difficulty in implementing this. Surely any PR will be welcomed.
