### ISSUE TITLE
MutationObserver support

### ISSUE THREAD

**Issue by MeoMix** [noraesae/perfect-scrollbar#268]
Hiya,

It seems to me the most common use case for needing to call the update method is when the given list's height changes.

This change can be detected in modern browsers by using MutationObserver to monitor the element's attributes and respond when the height changes.

Any reason not to try and support this where possible? People can always opt-out with a flag or call update in other scenarios if necessary.

**Comment by noraesae** [comment]
Will be supported on v1. If there is any comment, please leave it on the v1 thread.

**Comment by MeoMix** [comment]
👏
