### ISSUE TITLE
Perfect? Well ... almost

### ISSUE THREAD

**Issue by tengu3** [noraesae/perfect-scrollbar#271]
Hi there, love your plugin. I used your scrollbar for a small project with flipping 'fullpage' pages that are sometimes higher than 100%. The scrollbar works perfect.

One request: add callback functions. I had to manually insert a 'callback' in shouldPreventWheel() where my page 'flips up' when the scrollbar reaches the top, and 'flips down' when the scrollbar reaches the bottom. Not much of a hassle, but it would be nice if this could be done with a standard callback function. 

Otherwise, great!

**Comment by andig** [comment]
Why not provide a pr?

**Comment by DanielApt** [comment]
@tengu3 Please provide a pull-request. If you need help let me know.

**Comment by noraesae** [comment]
Sorry for the late response. I may consider implementing the feature in the future, as for the time being I have no much time to contribute to this plugin.

I'll close this issue now, and will open a new issue when starting to implement this.

Thanks!
