### ISSUE TITLE
using perfect-scrollbar and floatThead to scroll within tbody

### ISSUE THREAD

**Issue by mkoryak** [noraesae/perfect-scrollbar#273]
Hi,
I am the author of a plugin that lets you lock the table header. 

People wanted me to support a fancy scroll bar plugin, so I added support for yours. 
See: 
http://mkoryak.github.io/floatThead/examples/perfect-scrollbar/

That is all. You can close this issue.

**Comment by noraesae** [comment]
Looks brill. Thank you very much!
