### ISSUE TITLE
JavaScript runtime error: Unable to get property 'shadowRoot' of undefined or null reference

### ISSUE THREAD

**Issue by daverupp** [noraesae/perfect-scrollbar#275]
When I press the Key - ESC than I always get the error obove. Is it possible, to do one more hook to validate shadowRoot? that would be perfect.

Thank you very much

**Comment by noraesae** [comment]
2fc41e7045c0aa424f2da406a8eff40c9183874e fixes this.

Thanks for the report.

**Comment by daverupp** [comment]
thank you for the fix 😎
