### ISSUE TITLE
Help needed for the next version!

### ISSUE THREAD

**Issue by noraesae** [noraesae/perfect-scrollbar#277]
As you can find in the current master branch, the next version of the plugin will be independent from jQuery and NPM and Browserify friendly! I've done some work on it and it's about to finish, but I'd like somebody to help and participate in the project! Every kind of contribution would be really appreciated.

Here is a TODO list.

- [x] Migrate into Gulp.
- [x] Use Browserify to make the source tree modular.
- [x] Move to eslint.
- [x] Be independent from jQuery.
- [x] Rewrite examples with vanilla JS.
- [x] npm with browserify compatibility.
- [x] Make handlers modular.
- [x] Other adaptors including AMD.
- [x] Include built files in the NPM registry.
- [x] Automatic release with built files into GitHub Releases.
- [x] Separate a bower repo.

Specifically,

1. While modularising it into several part, I detached AMD support temporarily. To be honest, I'm not familiar enough to AMD or other adaptors. Currently, jQuery and just `global` adaptors have been implemented. Any contribution on new adaptors will be gratefully welcomed.
1. I've changed code base quite much, so I'd like to check if it works fine in most environments including IE>=9. I've just checked with my environment(the latest versions of Safari, Chrome and Firefox in OSX) and it looks working fine. Nevertheless, I'd like to make it sure. The easiest ways to test it would be with NPM or git.

NPM
```
$ npm install git+ssh://git@github.com:noraesae/perfect-scrollbar.git
```

git
```
$ git clone git@github.com:noraesae/perfect-scrollbar.git
```

Thanks in advance!

**Comment by Nijikokun** [comment]
Why separate the bower repo, this makes no sense?

**Comment by noraesae** [comment]
Why not? React has [a separated repo](https://github.com/reactjs/react-bower) for Bower. jQuery [has also dropped Bower](https://github.com/jquery/jquery/commit/e1949f43711b5808d42378bafb6728b40b1738d6). Frontend devs are moving to using npm to manage their dependencies and packages, with some help of modules like Browserify or Webpack, and I totally agree to the movement.

I think Bower is being deprecated. However, I don't want to frustrate users who are currently using Bower , so I've just separated into a repo, which works just the same as it used to do before, `bower install perfect-scrollbar`. I'll also update the repo with new versions for a while, in the way how React does, and users don't need to worry :)

**Comment by DanielApt** [comment]
Happy to help with the Github Pages. What are the main things you want to achieve by renewing the Github Pages?

**Comment by noraesae** [comment]
No specific plan yet, but the current version is nothing but a download page with a simple demo and I think it's not so enough for a plugin page.

In the new Github Pages, I'd like to provide more information to use and contribute to the plugin, and advanced demos with code snippets using jsbin or jsfiddle.

If you're interested, feel free to give me any suggestion. If you'd like, I will create a separated issue for the GH Pages and assign you.

**Comment by emkay** [comment]
@noraesae anything left to help out on to get this out the door? seems like most of the stuff is covered, but let me know if you need any help triaging issues, working on features, etc.

**Comment by noraesae** [comment]
Thanks to you guys, the new version has been released!

The new GH page task has been moved to #292.

**Comment by emkay** [comment]
:+1:
