### ISSUE TITLE
Disable scrolling with mouse wheel?

### ISSUE THREAD

**Issue by pajcho** [noraesae/perfect-scrollbar#278]
Is there a way to completely disable scrolling with mouse wheel, and only use keyboard or dragging of scrollbar?

**Comment by noraesae** [comment]
There's not yet an official way to do this. If you just want not to handle a `mousewheel` event, you can just unbind it with the code below.

```javascript
$('#container').unbind('mousewheel');
$('#container').unbind('wheel');
```

Thanks.

**Comment by pajcho** [comment]
Thanks @noraesae

**Comment by lordaplala** [comment]
e.stopPropagation(); did the trick for me. 

`$(element).on('mousewheel', function (e) {
                            e.preventDefault();
                            e.stopPropagation();
                        });`
