### ISSUE TITLE
Scrolls functionally, but no scrollbar + empty space at bottom of Div

### ISSUE THREAD

**Issue by docodewhiletrue** [noraesae/perfect-scrollbar#280]
I'm implementing tiny-scrollbar in a wordpress theme I'm building. I was pumped to get it working but I'm having two issues:

1. The scrollbar it self is not showing up. The div will scroll via mousewheel, but I can't actually manipulate the scrollbar on the screen.

2. There is a bunch of empty space at the bottom of the div when I scroll with the mousewheel.

Any advice?

**Comment by noraesae** [comment]
I think the css isn't properly applied. Please check if the css file is loaded and the container div meets [the requirements](https://github.com/noraesae/perfect-scrollbar#requirements).

Thanks.

**Comment by docodewhiletrue** [comment]
Thanks for getting back to me so quickly!

I have applied the requirements to the div that I need to scroll. However, I'm not sure if I understand the last two requirements regarding the scrollbar's position... how do I make those changes? What selector do I use in my css to meet these requirements?

As for loading the css... Can I just copy the css to the bottom of my main css file? That doesn't seem to change anything.

Thanks again.

**Comment by noraesae** [comment]
For the last two, `perfect-scrollbar.css` contains them, so you don't need to worry. Also for loading CSS, surely you can just copy the code.

If it still doesn't work, please let me know, preferably with an example page I can look into to narrow down the reason of the problem?

Thanks.

**Comment by andri** [comment]
I have a similar problem in a project. The element scrolls fine with the mouse-wheel but for some reason the scrollbars are not visible and **missing from the DOM**. In this case I have three scrollable elements on the page and only one of them has this bug. If I can't solve it soon I'll make a fiddle or something.

**Comment by michaltowilk** [comment]
I'm getting the same issue. After getting content via ajax and init PS, scrolling works fine but there is no scrollbar rails in DOM

**Comment by noraesae** [comment]
If your scrollbar elements are missing, it must be because they are removed when the content is refilled, likely with `.html()` or `.empty()` or something like these.

In the latest version, when the scrollbars are missing, there's no way to show them again, but you can manually call `.perfectScrollbar('destroy')` and `.perfectScrollbar()` again and then they'll show up.

However, in the new version, even if the scrollbars are missing, they'll show up again when `.perfectScrollbar('update')` is called.

**Comment by seedwalk** [comment]
you are not loading the css file
