### ISSUE TITLE
doesn't handle container padding correctly

### ISSUE THREAD

**Issue by fuddl** [noraesae/perfect-scrollbar#284]
when the container has a padding, the scollbar doesn't behalf like the native scrollbar.

see this [example on jsfiddl](http://jsfiddle.net/x93gx6Lh/6/)

It seems padding is generally not expected. the scrollbar does not span the whole container when it is present.

**Comment by noraesae** [comment]
There's an `includePadding` option. Please refer to an updated example I've written.

http://jsfiddle.net/x93gx6Lh/7/

Anyway, I think there's no point to keep the option, so I'll change it to a default behaviour. Thanks :)
