### ISSUE TITLE
Plugin should add overflow styling, do not use stylesheet.

### ISSUE THREAD

**Issue by DanielApt** [noraesae/perfect-scrollbar#285]
Currently one of the requirements for perfect scrollbar is to set the element's `overflow` to `hidden`.

I think this should be done by the plugin itself, and not in the css. My main reason is:

### Fall-back for no-js###
Let's say you have a list which you want to use perfectScrollbar with. You set `overflow` to `hidden`.
Sadly JavaScript is disabled, yet all css works. Now the list is unusable, as you can't scroll through it.

I'm happy to hear other people's thoughts before I'd start working on a patch.

**Comment by DanielApt** [comment]
Actually… just realised we can simply set `overflow` to `hidden` by adding that styling to the `.ps-container`

Will submit a pull-request soon.

**Comment by noraesae** [comment]
Agree with the idea. Discussion shall be done in #285.

Thanks!
