### ISSUE TITLE
[Browserify] Require perfect-scrollbar return an empty object

### ISSUE THREAD

**Issue by samuv** [noraesae/perfect-scrollbar#288]
Hi,

If I try to use your library and follow your guideline with npm and browserify the var Ps return an empty object.

Any thoughts on this problem?

**Comment by noraesae** [comment]
Hi, the new version hasn't been released, and it can't yet be used with `npm` by default. You can either use an [old version](https://github.com/noraesae/perfect-scrollbar/tree/0.5.9), or install a dev version manually with `npm install noraesae/perfect-scrollbar`. The new version will hopefully be released very soon.

Sorry for the inconvenience!

**Comment by samuv** [comment]
Thanks for the answer and congrats for the good jobs you have done!
