### ISSUE TITLE
Max-height

### ISSUE THREAD

**Issue by Samuell95** [noraesae/perfect-scrollbar#291]
Hello, i have problem with max-height. Scrollbar appears although not wonder long enough.

How to fix?

http://data.icrazy.eu/i/Qc3q8fYJ.png

**Comment by noraesae** [comment]
Hi, can you check the version of the plugin and if any `padding` is used for the container?

Cheers,

**Comment by Samuell95** [comment]
Version is latest (v0.5.8) and on container is padding.

**Comment by noraesae** [comment]
Then would you please try to use the `includePadding` option? It'd be used like below.

```javascript
$(someContainer).perfectScrollbar({includePadding: true});
```

In the new version, it is a default behaviour, but I hadn't been fixed in v0.5.8. Sorry for your inconvenience.

Cheers,

**Comment by Samuell95** [comment]
It works. Thanks for fast reply and thanks for this cool scrollbar ! :)

**Comment by noraesae** [comment]
Thanks :D
