### ISSUE TITLE
.ps-scrollbar-y-rail is moving which is a main div

### ISSUE THREAD

**Issue by przbadu** [noraesae/perfect-scrollbar#294]
Hi, for me the main scrollbar container which is with class name ".ps-scrollbar-y-rail" is moving along with it's child scrollbar with class ".ps-scrollbar-y".

Here ".ps-scrollbar-y" is the main scrolling div which should scroll and it is scrolling in my case

but the problem is the main container ".ps-scrollbar-y-rail" is also moving which is causing trouble..

May be this screenshot can make it clear:

![issue](https://cloud.githubusercontent.com/assets/4189129/6457978/0a83c146-c1a4-11e4-8e79-34169eedd7a7.png)

Please let me know, If I am unable to make you clear

**Comment by noraesae** [comment]
Hello,

Please check the styles of the container div. Does it have any `position` style? If not, please add `position: relative` or whatever you want. If there is and it doesn't work yet, let me know if the container div has any padding value.

Cheers,

**Comment by noraesae** [comment]
Closed for inactivity.

Please feel free to reopen.

**Comment by vytautas-pranskunas-** [comment]
position: relative helps but on IE11 it scrolls "jumpy".

**Comment by DParua** [comment]
> Hello,
> 
> Please check the styles of the container div. Does it have any `position` style? If not, please add `position: relative` or whatever you want. If there is and it doesn't work yet, let me know if the container div has any padding value.
> 
> Cheers,

I have the same exact problem.. I also tried adding `position: relative;` as it says so in the usage guide.. but still no luck.

```
#pages_list_div {
    position: relative;
    overflow: hidden;
    border: 1px solid #ccc;
    height: 100%;
}
```

This is the CSS for perfect-scrollbar container.

```
.page_num_div {
    font-size: 10px;
    height: 40px;
    line-height: 40px;
    border-top: 1px solid #fff;
    border-bottom: 1px solid #ccc;
    width: 100%;
    padding-left: 15px;
}
```

Divs with class "page_num_div" are dynamically added and removed from the container "pages_list_div". 

![1](https://user-images.githubusercontent.com/28051980/49201719-0c4a3a00-f3c8-11e8-97d3-07d02c426ac9.png)

The div takes scrolling white space above the content as shown in the picture.. Please provide me with a solution.
