### ISSUE TITLE
Input focus and type issue

### ISSUE THREAD

**Issue by nthibert** [noraesae/perfect-scrollbar#298]
I have just implemented the scroll in my app. Found a really obscure bug. 

I have a container that is a set width and height that holds a form like below. So above the container are 2 fix bars (header/footer). When I focus on the input within the scroller, all is fine. Once I start typing all is fine. The issue comes when I move the mouse outside the container of the scroll. The scrollbar becomes more active and when I move the mouse down or above the container it then scrolls the container when I didn't want it to. I dug into the code a bit and it centers around the bindSelectionHandler and the mousemove. 

```
<form>
    <div class='scroller'>
        <div><input></div>
    </div>
</form>
```
Any thoughts would be great.

**Comment by zomp** [comment]
Hi @nthibert , there was a bug till recently which could lead to this behaviour (I cannot find its reference). Could you try the newest version of perfect-scrollbar and confirm whether the bug persists, please?

**Comment by nthibert** [comment]
Looks like things are working great now. Thanks for the update!

**Comment by noraesae** [comment]
Thanks guys for the helps.
