### ISSUE TITLE
Disable wheel?

### ISSUE THREAD

**Issue by ronihcohen** [noraesae/perfect-scrollbar#299]
Hello,

How can I disable the mouse wheel?
I have another wheel event listener used for zooming and I am using ``` event.preventDefault(); ``` for locking the scrollbar but with this plugin the container still scrolling on wheel event.

**Comment by noraesae** [comment]
Actually, I'm afraid there's no way to do this. However, if you don't mind modifying code by yourself, you can just comment out the following line in `src/js/plugin/initialize.js`.

```js
clickRailHandler(element);
dragScrollbarHandler(element);
// mouseWheelHandler(element); // comment out this line
nativeScrollHandler(element);
selectionHandler(element);
```

You can make built files with `gulp build`.

Thanks.

**Comment by tonyrusignuolo** [comment]
Also had a zooming feature that I hoped would override/pause mouse wheel scrolling. Tried [this solution](https://github.com/mdbootstrap/perfect-scrollbar/issues/749), but that would automatically jump to the top of the page.  So I wrote this work around
```
var len = ps.event.eventElements.length;
var temp = ps.event.eventElements[len].handlers.wheel[0];
$('''zoom element''').on('pointerover', (e) => {
    document.querySelector('.main-panel').removeEventListener('wheel', temp, false);
});
$('''zoom element''').on('pointerleave', (e) => {
    document.querySelector('.main-panel').addEventListener('wheel', temp, false);
});
```
Inspiration from [here](https://stackoverflow.com/questions/39684633/pause-event-listeners-in-the-background).

Hopefully this helps!
