### ISSUE TITLE
Can't get this to work in an iframe

### ISSUE THREAD

**Issue by NetOperatorWibby** [noraesae/perfect-scrollbar#302]
I have a NW.js app that I'd like custom scrollbars for. I am able to inject JS/CSS/&c into iframes, but for some reason, I am unable to get perfect-scrollbar to work.

However, while I see the `data` attribute on the iframe itself (if I just query the `iframe` selector), it doesn't change the scrollbar, so I have to dig deeper.

Can anyone help me out with this? I've attached a screenshot of the error code I'm seeing:

![screen shot 2015-03-10 at 4 09 59 pm](https://cloud.githubusercontent.com/assets/1288356/6584201/f3457f82-c73f-11e4-88d2-d50113fbd7ea.png)

^^ comes from this code I'm injecting:
```
_scrollbarBody = "";

_scrollbarBody += "<script>";
  _scrollbarBody += "Ps.initialize('html');";
_scrollbarBody += "</script>";
```

**Comment by noraesae** [comment]
Hello there,

First of all, I'm not sure if it works fine with a `html` element. I'd use with a full sized div container in the case I wanted to use a full screen app. Also, you should pass an element to `Ps.initialize`, not a tag name, such as a value obtained by `document.getElementById` or something like that.

For iframe, I'm not sure my plugin can cover your use case as iframe is kinda a special case, but if there's any problem, you can refer to an iframe example in the `examples` directory.

If you have any further problem, feel free to ask me.

Cheers,

**Comment by noraesae** [comment]
Closed for inactivity.

Please feel free to reopen.

**Comment by NetOperatorWibby** [comment]
That's totally fine @noraesae, I'll update if I figure it out. Taking a break on development to learn some things for my OS.
