### ISSUE TITLE
Firefox / Chrome difference when using "column-count"

### ISSUE THREAD

**Issue by ikb42** [noraesae/perfect-scrollbar#304]
In Firefox (36.0.1)
If you have an element using "-moz-column-count: 2" and within this element you have an element which has the scroll attached, then the content with the scroll bar is moved to the 2nd column.
It seems to have something to do with:
.ps-container {
    overflow: hidden !important;
}

When in a webkit browser using "-webkit-column-count: 2", the scroll bar is attached only to the first column, but the content displays across both columns and the scrolling works.

**Comment by noraesae** [comment]
Hello,

Actually I didn't consider the `column-count` cases, so it might not work well with them. For the time being I have no enough time to contribute to this plugin, so I'm not sure when to look into this issue, but I hope it's done in a while.

Thanks for reporting.

**Comment by noraesae** [comment]
It's been a while there's no update for this issue and I am sorry but it may be better to close this issue here. If it is still an issue in the latest Firefox too, please upload a new issue, preferably with a fiddle to reproduce the issue.

Thanks again.
