### ISSUE TITLE
progate event to children elements

### ISSUE THREAD

**Issue by parliament718** [noraesae/perfect-scrollbar#307]
I have a page that uses perfect-scrollbar but not everywhere (it seems to have dramatic degrde performance on some live stock ticker table with high-refresh rate and row virtualization).. So I left the native scrollbar on these tables.

However, it seems I cant scroll those tables now.

To clarify, perfect-scrollbar is on the parent, and native scrollbars are children.

Is there a way to progatate the event?

**Comment by noraesae** [comment]
In this case, the event must have been propagated into the parent from the children. if you'd like not to handle the children's scrolling events in PS, please stop the propagation of the children's scroll event. It can be done like below:

```js
childElement.addEventListener('wheel', function (e) {
  e.stopPropagation();
});
childElement.addEventListener('mousewheel', function (e) {
  e.stopPropagation();
});
```

Thanks. If you have any further problem, please feel free to reopen!
