### ISSUE TITLE
Cannot scroll textarea inside container

### ISSUE THREAD

**Issue by jejo** [noraesae/perfect-scrollbar#308]
I am experiencing an issue when a textarea is inside the container. Even if the focus is at the textarea during scrolling, the container is the one being triggered to scroll.

**Comment by yashikagarg13** [comment]
Any updates on this.. I am facing the same issue

**Comment by noraesae** [comment]
Hi there,

Sorry for the late response. dc7b14d0e16378805ce138f870181a52d38b54b9 fixes the issue.

Thanks!
