### ISSUE TITLE
Make a "fluid scroll"

### ISSUE THREAD

**Issue by AoEmaster** [noraesae/perfect-scrollbar#310]
Hi.

Thank you very much for this awesome scrollbar.
How can I make the scroll "fluid", like a transiton effect ?

Thank you :) (sorry for bad english, french here ^^' )

**Comment by DanielApt** [comment]
On what device are you trying to get the fluid scrolling behaviour? Browser, or touch?

**Comment by AoEmaster** [comment]
Browser

**Comment by noraesae** [comment]
It's kinda tricky to do this. You should hook a mousewheel event and handle it by your self. The basic code may be like below.

```js
containerElement.addEventListener('mousewheel', function (e) {
  var heightToScroll = getHeightToScroll(e); // should be implemented manually
  var heightToScrollAtOnce = 2; // for example

  var scrolledHeight = 0;  
  var transitionInterval = setInterval(function () { 
    containerElement.scrollTop += heightToScrollAtOnce;
    Ps.update(containerElement);

    scrolledHeight += heightToScrollAtOnce;
    var atBottom = /* check if it's at bottom */;
    if (scrolledHeight >= heightToScroll || atBottom) {
      clearInterval(transitionInterval);
    }
  }, 30);
});
```

The code is not tested, but the basic concept may be right.

**Comment by noraesae** [comment]
Will close for the inactivity. Please feel free to reopen when having further issues.

Thanks!
