### ISSUE TITLE
Scrollbar not working on firefox after a click on <select>

### ISSUE THREAD

**Issue by AoEmaster** [noraesae/perfect-scrollbar#311]
Hi.

Open it with firefox https://jsfiddle.net/fvhyosgd/2/
Click on the selectbox, change option if you want. Try to scroll after you did it, scrollbar is not working anymore (with mousewheel) until you click in the box again.

Sorry for bad english :)

Also noticed same bug on last IE. Works great with chrome

**Comment by noraesae** [comment]
It's actually intended behaviour, because of this bug: #247.

However, the native bug may have been fixed, or not, so I'll check again in a while.
