### ISSUE TITLE
Version information is not included in the deployed files

### ISSUE THREAD

**Issue by slimandslam** [noraesae/perfect-scrollbar#313]
It appears that there is no version information in the deployed files. Add this information so that one can quickly tell which version of perfect-scrollbar they're running.

**Comment by noraesae** [comment]
It's fair enough and it's just been implemented with c21cfb6ed01feb741a893efe6f04259be067aaf5!

Thank you very much.

**Comment by slimandslam** [comment]
You rock.  :-)
