### ISSUE TITLE
Heavy nodejs' affinity

### ISSUE THREAD

**Issue by bertmsk** [noraesae/perfect-scrollbar#314]
Current version has very strange affinity to NodeJS.

jQuery has its own plugin guidlines. Please don't break them. 

I dont see any good reason why did you choose server-side tool for UI plugin

**Comment by bertmsk** [comment]
Also remove from CSS
-ms-filter: "progid:DXImageTransform.Microsoft.Alpha(Opacity=60)";
filter: alpha(opacity=60);

Because it's not needed since IE7 (and your scrollbar dont work in IE6 either)

**Comment by noraesae** [comment]
Using server-side preprocessors and tools is quite common practice in front-end development nowadays. Have you ever experienced with Browserify or any other module system? Any JavaScript or CSS preprocessor?

You're saying about jQuery plugin guidelines, but using server-side tool is nothing to do with jQuery plugin guidelines as the jQuery itself uses many server-side tools like `grunt`, `jshint`, `requirejs`, and even `npm`.

If you don't see any good reason, I recommend using them hard, as they are really helpful to make the code base modular.

Also, in twitter you talked about `procedural`, but it's kind of a programming paradigm, like functional or OO, and nothing to do with nested or coding style. If you were describing modular design, I used Browserify to make the code modular. Browserify made by substack, an awesome JavaScript developer, is such a great tool and I really recommend trying it.

If you see any further problem, please upload PR which I really appreciate :smile:

BTW, thanks for the `-ms-filter` thing! I'll remove them.

**Comment by noraesae** [comment]
And if you talking about `require()` usages in the plugin, it's not Node.js, it's Browserify. If you keep refusing looking into it and saying it's bad, well, I've no many things to do about it :laughing: 

Sorry, and thanks for the opinion.

**Comment by noraesae** [comment]
One last thing, it's not just a jQuery plugin anymore. It works with vanilla JS as well. All the modules such as event, DOM, etc are to make it independent from jQuery.
