### ISSUE TITLE
Multi scrollbars on mobile devices

### ISSUE THREAD

**Issue by devolkpl** [noraesae/perfect-scrollbar#315]
Hi guys, 
I'm not sure if it's a bug or just incorrect setting up.  
I have outer wraper with horizontal scroll. Inside this wrapper there is eight blocks with vertical scroll. Everything works perfect on desktop browsers but I'm getting issue on mobile devices (tested on ipad air retina). Outer wrapper (horizontal) not scrolling when I'm swiping on inner blocks - only bottom rail works. 
Please give me some answer, current settings attached. 

$('.month_grid').perfectScrollbar({
	wheelPropagation : true,
	suppressScrollX : true
});
$('.month_grid .cell').perfectScrollbar({
	useBothWheelAxes : true,
	suppressScrollY : true,
	wheelPropagation : true
});

**Comment by ditkachuk** [comment]
I have some problems on touch devices.

**Comment by noraesae** [comment]
#424 looks like fixing this. I'm really sorry that it's really been a long time, but can anybody having the same problem test the PR out?

**Comment by DanielApt** [comment]
I've tested #424 and it works. Closing this issue now.
