### ISSUE TITLE
Feature Request: Draggable scrolling on desktop

### ISSUE THREAD

**Issue by molimits** [noraesae/perfect-scrollbar#316]
Hi!

First of all, great plugin, I love it! I've come across a small little issue though for my own use case. I'm using the plugin to support a horizontally scrolling image gallery (see www.topflight.ie/summer-sun/italy/lake_garda/peschiera/bella_italia_apartments?v=b as an example). The issue I'm having is that on desktop, with a mouse input, intuitively people are trying to grab the images and drag them to the left, like on a touchscreen, as they assume that's how the gallery will work. Is there a way I can easily implement such a behaviour using a mouse input? 

Thanks for your help,
Sean

**Comment by noraesae** [comment]
Hmm, actually I've not considered implementing this, as I think it's kinda too much for a scrollbar plugin. I think the feature is more adequate to sliders. However as it seems quite handy, I may consider in the future, but nowadays I have no enough time to work on this.

I'll close the issue for the time being, and will open a new issue when implementing this.

Thanks for your interest!
