### ISSUE TITLE
Scrollbar not working in textarea on firefox v37

### ISSUE THREAD

**Issue by sachin333** [noraesae/perfect-scrollbar#318]
Hi, thank you for making such a nice and light weight scrollbar. Recently i try to run my application on firefox. Every thing is perfect but with TEXTAREA perfect scrollbar not working, although it's working on IE 11. Can you please, confirm this issue.

**Comment by noraesae** [comment]
Hi,

What does 'not working with textarea' mean? If you mean applying the plugin to a textarea element, I'm afraid that the scrollbars are appended to the container element, but textarea is not a valid container and cannot contains any element in itself. So even though it fortunately works in IE, it's not assured that the plugin works fine in every other browser.

However, if I misunderstood and you mean another issue, please specify the case a bit more.

Thanks.

**Comment by noraesae** [comment]
I doubt, but if you mean #308, please refer to it.

**Comment by noraesae** [comment]
Closed for inactivity. Please feel free to reopen.

Thanks!
