### ISSUE TITLE
Page Update increases height of ps-scrollbar-y-rail

### ISSUE THREAD

**Issue by yashikagarg13** [noraesae/perfect-scrollbar#319]
I am using this plugin in angular js through https://github.com/itsdrewmiller/angular-perfect-scrollbar. After the response of an ajax call, the page or say div with ".scroller" class height increases and what I noticed is its the div with class "ps-scrollbar-y-rail" that has irrelevant height.. that is more than the content height. Also if I scroll, then that extra space is gone and it works normal.

**Comment by yashikagarg13** [comment]
I found its the top that has extra value for div with class "ps-scrollbar-y-rail".

**Comment by noraesae** [comment]
The geometry is updated when it's scrolled, but if you'd like to update before scrolling, you should manually call the update function when you need to update. In this case, maybe in the ajax callback.

```js
Ps.update(element); // In case of vanilla JS
$(...).perfectScrollbar('update'); // jQuery
```

Actually, the angular version is not maintained by me, so I've no idea how to manually update in it. But as I provide the methods, there may be a way to do that in the angular version too.

Thanks.

**Comment by yashikagarg13** [comment]
$(...).perfectScrollbar('update'); this doesn't help
Attaching screenshot for this. Content is only upto the red border. the space after it is the extra height or top postion of  "ps-scrollbar-y-rail".
![screen shot 2015-04-10 at 11 51 49 pm](https://cloud.githubusercontent.com/assets/11815050/7094138/9f90911e-dfdc-11e4-93d7-210ed48b84f8.png)

**Comment by noraesae** [comment]
Hmm, can I have an example page or a fiddle to reproduce the problem? If I can't use the inspector, it's really hard to narrow down the reason.

**Comment by noraesae** [comment]
Closed for inactivity. Please feel free to reopen.

Thanks!
