### ISSUE TITLE
Perfect scrollbar not working in ie 9

### ISSUE THREAD

**Issue by vguduguntla** [noraesae/perfect-scrollbar#325]
i am getting
 Object doesn't support property or method 'perfectScrollbar' <div class="storeContainer custom ui divided list scroller ng-scope" suppress-scroll-x="true" wheel-speed="5" wheel-propagation="true" perfect-scrollbar=""> error

when i am using perfect scroll bar in ie 9 any fixes for this

**Comment by noraesae** [comment]
Hi,

You may use it with jQuery? Can you provide some part of your code or site? It'll help me to look into the issue.

Thanks,

**Comment by vguduguntla** [comment]
code
<perfect-scrollbar class="scrollbar" wheel-propagation="true" wheel-speed="5" suppress-scroll-x="true"> 
<div  >
</div>
</perfect scroller>

libraries
<script src="/perfect-scrollbar.js">
<script src= "/angular-perfect-scrollbar.js">
<script src= "/jquery.mousewheel.js">

here are my code snippets

**Comment by noraesae** [comment]
Closed for inactivity. Please feel free to reopen.

Thanks!
