### ISSUE TITLE
Discussion: should click events occurring on rails bubble?

### ISSUE THREAD

**Issue by MeoMix** [noraesae/perfect-scrollbar#326]
Hey,

I'm here to suggest that clicking on the scrollbarYRail/scrollbarXRail should have the default click event prevented.

Consider the following scenario:

* List of items is displayed with scrollbar
* Each item in list has a click event handler bound to it.
* User wants to scroll the list by clicking on a point on the scrollbar's rail to move up/down.
* The scrollbar scrolls, but the click event propagates up and causes the list item's 'click' event handler to run.

I don't think this makes much sense because normal scrollbars could never have a click event propagate. Plus, it's pretty obvious what the user's expected result is of the click.

Thoughts?

**Comment by noraesae** [comment]
I totally agree. Will work on.

**Comment by Alexwijn** [comment]
The stopPropagation causes an issue in my project. I got a sidebar that can open and it closes when the user clicks outside the sidebar. But because of stopPropagation I'm unable to detect if the user clicks on the scrollbar and because of that the sidebar will close even when the user does not want that.

**Comment by MeoMix** [comment]
@Alexwijn 

If you open your browser's dev tools on this page and run:

`window.addEventListener('click', function(){ console.log('hi'); } );`

submit the code, and then click on the native scrollbar on the side you **won't** see the click event handler run. By contrast, if you click on any element on the page -- you will.

The functionality you're experience is equivalent to native functionality. So, I don't think my suggested change should be considered a bug in perfect-scrollbar.

**Comment by Alexwijn** [comment]
Thanks for the quick response! Currently I have the following code to close the sidebar when clicking outside it:

    $(document).on('click', function (e) {
        //
    });

But in e.target, where I normally check if its an element inside of the sidebar, I receive the wrapper element around the document rather than the sidebar. And I think this is caused by the stopPropagation.

**Comment by MeoMix** [comment]
Right. I get that. I'm not saying you don't have a UX bug you need to solve. I'm saying that the issue isn't related to perfect-scrollbar as perfect-scrollbar is properly emulating native functionality.

I made a CodePen for you which highlights the issue you're describing without use of perfect-scrollbar: http://codepen.io/Meo/pen/EPXXOV

Try clicking around a bit. You'll see that clicking the scrollbar does not propagate click events.

**Comment by Alexwijn** [comment]
If its emulating native functionality than why is there a click event at all since it should not fire one? If it was not fired than my code is not executed and the sidebar is not getting closed.

**Comment by MeoMix** [comment]
Looking at the valid options for perfect-scrollbar, I see `stopPropagationOnClick` as a possible option. I suspect the rest of the propagating is defaulted on, but can be disabled as desired to properly emulate native functionality.

**Comment by Alexwijn** [comment]
Not sure why I did not saw stopPropagationOnClick earlier but for some reason this does not seem to work for me. The variable e.target still contains the wrapper of my document and not the scrollbar.

**Comment by MeoMix** [comment]
Well, ideally you should never see a scrollbar element in e.target because it shouldn't be a valid element. I'm not aware of other bugs (I don't do active development on this -- simply got an e-mail when you first commented). Mostly just wanted to stand by the fact that I think my suggest of stopPropagation is correct. Good luck! <3
