### ISSUE TITLE
Idea: Invert Scrolling on Y axis

### ISSUE THREAD

**Issue by nellsavedra** [noraesae/perfect-scrollbar#328]
I love Perfect-Scrollbar but dont have any option to invert the scrolling on Y to X axis like tinyscrollbar

**Comment by noraesae** [comment]
Hmm interesting. Actually it works along with the original OS X direction, but I've not yet considered it as an option.

I will think over implementing it, but I've no much time to contribute to this plugin nowadays, so not sure when to do.

Anyway, thanks!
