### ISSUE TITLE
'reverse' flex direction support

### ISSUE THREAD

**Issue by liuyang1204** [noraesae/perfect-scrollbar#329]
When I use css3 flexbox `flex-direction: column-reverse;` on the container, the scrollbar position 'top' stays the 'bottom' of the container.

**Comment by noraesae** [comment]
I've not considered using the plugin with `flex-direction`. Nowadays I'm afraid I don't have much time to work on this plugin, so it may take quite much time to get this issue addressed. Any contribution will surely be welcomed.

**Comment by noraesae** [comment]
It's been a while there's no update for this issue and I am sorry but it may be better to close this issue here. If it is still an issue in the latest Firefox too, please upload a new issue, preferably with a fiddle to reproduce the issue.

Thanks again.

**Comment by hellmelt** [comment]
I ran into this, just 9 days after the issue was closed... Please re-open it.

Take a look at this fiddle:
https://jsfiddle.net/hellmelt/xsh3uzsz/2/

- The first box is a flex with normal order. It works as expected.
- The lower box is a flex with reversed order. 
    - In Chromium 50.0 the scrollbar has the top too low. 
    - Firefox 46.0 shows no scrollbar at all, and the content is not scrollable.

Tested on Linux version of browsers. I have not tested any other browsers.

I need this to work, so I'll try to solve it and submit a pull request later.

**Comment by noraesae** [comment]
I've just checked it and found it quite tricky to fix. It is needed for absolute-positioned element to show properly for the plugin. It seems that absolute positioning doesn't work well with flex-reverse.

Any PR will be welcomed for this issue.

**Comment by hellmelt** [comment]
Yup, tricky. If I understood the code, perfect scrollbar relies on the browser's computation of scrollHeight (and scrollWidth). And for anything else than the conventional left-to-right, top-to-bottom ordering, the browsers do not compute scrollHeight/Width correctly when using flex.

This fiddle illustrates it (there is no perfect scrollbar in the fiddle):
[https://jsfiddle.net/hellmelt/xLq0p1q6/]

The first box (flex-direction: column) is left-to-right, top-to-bottom, scrollHeight is correct, and perfect scrollbar would work for that particular case.

The second box (flex-direction: column-reverse) has the correct scrollHeight in chromium but the origin for the scrollbar will not be at the top for some reason (check my previous post and the fiddle linked there). In firefox the scrollHeight equals clientHeight, so no scrollbar would be displayed at all.

For the third box (flex-direction: column, justify-content: flex-end) the scrollHeight equals clientHeight in both browsers. No scrollbar would be shown, even though the content overflows.

If you change overflow:hidden to overflow:auto, you will see that the browser's built-in scrolling also fails, for box 3 in chromium, and boxes 2 and 3 for firefox.

I guess a tedious and error-prone workaround would be to try to traverse all children inside the element, and add the heights together, and get a custom scrollHeight. But that feels genuinly wrong, the browsers should be able to compute scrollHeight and scrollWidth correctly. Don't you agree on that?

So in my opinion this is not possible to solve, and the only way out is to mention in the readme file that display:flex is a limitation where perfect scrollbar not always works as expected.

**Comment by noraesae** [comment]
As @hellmelt suggested, mentioning it is difficult in README seems viable solution. Will close this issue, and add it to README.
