### ISSUE TITLE
Scrollbar is invisible on Chrome but not Firefox

### ISSUE THREAD

**Issue by oleduc** [noraesae/perfect-scrollbar#332]
Please note that this issue wasn't tested with elements not created by javascript.

See the following JSFiddle:
https://jsfiddle.net/hkwaxgky/1/

Thank you.

**Comment by oleduc** [comment]
Okay I fixed this by making sure that initialization occurs after the container is appended to an existing DOM element.

**Comment by noraesae** [comment]
Hi, sorry for the late response. If we change the order of `initialize` and `appendChild` it works. It doesn't work in Safari too and it means WebKit seems to do something on DOM and make it asynchronous.

Anyway, it works with following order.

```
document.body.appendChild($testContainer);
Ps.initialize($testContainer);
```

As we already initialise, no update is needed. 

Thanks!
