### ISSUE TITLE
Invalid horizontal scrollbar on floating width value (IE 10)

### ISSUE THREAD

**Issue by aszmyd** [noraesae/perfect-scrollbar#333]
When we use an floating value of width (i.e. `550.47px`) in `IE10` (tested on `Windows7`) plugin shows an horizontal scrollbar even if its not necessary (content is smaller that container).

In the codepen i've used `0.5.9` version and jquery-way of initialize but the same happend to me with `0.6.2` and `Ps.initialize` way of initialization.

Here is an example (must bee seen in `Internet Explorer` to saw the issue): http://codepen.io/aszmyd/pen/waKNdq/
Also screenshot of how it looks for me:
![compare](https://cloud.githubusercontent.com/assets/3050805/7533107/c86c5a08-f56e-11e4-827b-4d4c38b3bb8f.jpg)

**Comment by noraesae** [comment]
Hmm, there may be a problem in calculating float number with IE10. I will check if there is any problem in the code. Nowadays I have got quite much work to do, so I'm not sure when I can look into this. I'll try to do asap.

Thanks for the report.

**Comment by noraesae** [comment]
It's been a while and there's been some updates on calculating floating-pointed number. I think it may be better to closeclose this issue here. If it is still an issue, please upload a new issue, preferably with a fiddle to reproduce the issue.

Thanks again.
