### ISSUE TITLE
"'this' is not a Function object" in IE10

### ISSUE THREAD

**Issue by GiovanniBattista** [noraesae/perfect-scrollbar#338]
Hello,

to reproduce this bug open IE10 (not sure about other IE versions) and go to the online demo of perfect-scrollbar.
Drag the scrollbar with the mouse cursor and release it. The mouse cursor needs to be exactly over the scrollbar (the dark area), otherwise no error is thrown.

**Comment by noraesae** [comment]
There seems to be a problem with mouse scrolling apparently. I'll create a separated issue.

Thanks for report.
