### ISSUE TITLE
Controlling with the mouse is broken when set on body

### ISSUE THREAD

**Issue by fresheneesz** [noraesae/perfect-scrollbar#340]
I wrote the following test:

```
<link rel='stylesheet' href='node_modules/perfect-scrollbar/dist/css/perfect-scrollbar.css' />
<style>
  body {
    position: relative;
  }

    #a {
        border: 1px solid red;
        height: 15000px;
    }
</style>
<script src='node_modules/perfect-scrollbar/dist/js/perfect-scrollbar.js'></script>
<body>
    <div id='a'></div>
</body>
<script>
    Ps.initialize(document.body)
</script>

```

Trying to control the scrollbar with the mouse is impossible, it jumps from the top to the bottom if you try to scroll down, and vice versa.

**Comment by lebiru** [comment]
this is also a bug for me.

**Comment by noraesae** [comment]
The plugin is not implemented to work on `body`. I recommend creating a wrapping div element. However, there seems to be a problem with mouse scrolling apparently. I'll create a separated issue.

Thanks for report.
