### ISSUE TITLE
More Than One Div

### ISSUE THREAD

**Issue by drumalert** [noraesae/perfect-scrollbar#342]
Hi, I have 3 divs all with id="Demo", only the first div is showing perfect-scrollbar.  How do I apply it to all divs?  Thanks :)

**Comment by 11mb** [comment]
It is considered invalid HTML when you have 3 ID's which are the same. ID's should be unique.. so you may want to use classes: <div class="demo">

**Comment by noraesae** [comment]
Yes. As @11mb said, you should use something like the `class` attribute. ID should be unique in a document.

Thanks!
