### ISSUE TITLE
scrollbar not always visible on IE 9

### ISSUE THREAD

**Issue by miguelmonraz** [noraesae/perfect-scrollbar#343]
Hi 
I am using perfect scroll bar and I want the vertical scroll bar to be always visible this works fine in firefox and chrome however whenever I start a new e session on IE9 the scroll doest not appear until I mouse over the container element, or even I need to press f12 and then refresh the page

Here is the code:

 $(".detail-col").perfectScrollbar({
      wheelSpeed: 8,
      wheelPropagation: true,
      minScrollbarLength: 20,
      suppressScrollX: true
    });

html code

&lt;div class="row glp-container always-visible"&gt;
&lt;div class="col-xs-7 col-sm-7 col-md-7 detail-col"&gt;

I have try the following solutions:

create the always visibe class inside the JSP

<style type="text/css">
/* to make scrollbars always visible */
.always-visible.ps-container.ie > .ps-scrollbar-y   {
opacity: 0.6;
visibility: visible;
}
</style>

To affect the div created by the perfect scrollbar

Override the perfect-scrollbar vertical scrollbar property by putting this code on the application css

ps-container.ie .ps-scrollbar-y {
visibility:visible !important;
}

And finally I have modified directly the perfect-scrollbar css directly

.ps-container.ie .ps-scrollbar-x,.ps-container.ie .ps-scrollbar-y{visibility:hidden} to visible

Sometimes works sometimes does not appear until I refresh then only show on mouseover

Please help me on this issue

Thanks in advance

Regards,
Miguel Monraz

**Comment by miguelmonraz** [comment]
html code (only the importan parts

  <div class="row glp-container always-visible">
    <div class="col-xs-5 col-sm-5 col-md-5  overview-col">
    </div>
     <div class="col-xs-7 col-sm-7 col-md-7 detail-col">
     </div>
</div>

**Comment by noraesae** [comment]
If it occurs only by chance, it may be a timing issue. How do you fill the content? Is it static? Any jsfiddle or codepen examples, or the site example will help us a lot to narrow down the reason.

**Comment by noraesae** [comment]
Closed for the inactivity.
