### ISSUE TITLE
onScroll callback

### ISSUE THREAD

**Issue by sergeylaptev** [noraesae/perfect-scrollbar#344]
Hi, why you don't trigger some events such as onScroll, onScrollEnd etc? I can't realize when scroll occured, just because your lib requires overflow: hidden and native scroll event doesn't triggers:) Pls tell me what do you think about it

**Comment by noraesae** [comment]
Hi,

Actually, `scroll` event must be triggered in `overflow: hidden` too. The event is triggered when `scrollTop` or `scrollLeft` is updated with any user interaction including mousewheel, browser search, etc.

Please try use `onscroll` or `addEventListener('scroll')` to handler the event. I've also created a fiddle with which you can see how it works.

http://jsfiddle.net/3o01oxgw/

Thanks!

**Comment by sergeylaptev** [comment]
thx for help!
