### ISSUE TITLE
Scroll flicker on contenteditable and scroll of other areas

### ISSUE THREAD

**Issue by ivomynttinen** [noraesae/perfect-scrollbar#348]
First of all, I prepared a jsfiddle so you can see the issue live: **https://jsfiddle.net/wsgsqs5v/1/**

Everything works fine as long as you just use your mouse/trackpad to scroll within the scroll areas. However, when you select text in the `#inner` div and drag your cursor up, the selection starts to flicker around:

![what2](https://cloud.githubusercontent.com/assets/1096989/8199920/a98cdb38-14e7-11e5-8aee-fba946546a1a.gif)

The second issue is that when the upper scroll area is at position 0 (not scrolled), you select text in the footer, then drag up your cursor, the whole upper area scrolls down to the bottom.

![what2](https://cloud.githubusercontent.com/assets/1096989/8199965/1853b1ae-14e8-11e5-931f-05c7a53be9f8.gif)

This is all in Chrome 43 OSX.

**Comment by noraesae** [comment]
I could reproduce the problem in my environment too. There seems to be a problem with mouse scrolling apparently. I'll create a separated issue.

Thanks for report.
