### ISSUE TITLE
Selecting text problem when perfectscrollbar nested inside perfectscrollbar

### ISSUE THREAD

**Issue by DominikVogt** [noraesae/perfect-scrollbar#351]
Seems like there is a Problem with text selection, when there is a perfectScrollbar inside another perfectScrollbar.

Does anyone else has this problem?

**Comment by asaadmahmoodspin** [comment]
+1 not sure if it's because it's nested but I'm having this issue too.

**Comment by asaadmahmoodspin** [comment]
Fixed, for me this was because I was running:
.perfectScrollbar(); 
and then doing:
.scrollTop(100000);
 doing .perfectScrollbar('update');

If I just go ahead and have
.scrollTop(100000);
 doing .perfectScrollbar();

That fixes my issue.

**Comment by asaadmahmoodspin** [comment]
+1 facing this issue, not sure if it's because it's nested but none the less facing it.

**Comment by asaadmahmoodspin** [comment]
It's due to pointer-events: none; on 
.ps-container.ps-in-scrolling or.ps-container:hover.ps-in-scrolling
removing them from both classes in the css file fixes it for me.

**Comment by noraesae** [comment]
Because of these issues, I disabled the `useSelectionScroll` option by default. But disabling it doesn't mean the issue is resolved. Any contribution will be welcomed!

**Comment by liugui** [comment]
I tried to remove the "pointer-events:none" from css file, but it not works.
So I open the js file, and there is a function named "bindSelectionHandler", which is invoked in the initialize function. Disabled it and then the problem solved!

**Comment by noraesae** [comment]
Currently, the buggy `selection` handler is disabled by default. It may not a ultimate fix, but it may not be used anymore until a 'right' solution for the selection scrolling, so there may be no problem anymore.
