### ISSUE TITLE
size not so perfect

### ISSUE THREAD

**Issue by neuropass** [noraesae/perfect-scrollbar#352]
42kb base for a perfect scrollbar? really?

**Comment by ayamflow** [comment]
Minified + gzip'ed version is 6ko.

**Comment by noraesae** [comment]
It's kinda big as the plugin isn't a single script file and we use browserify to zip the script files. I would say it's suitable for projects using browserify. But as @ayamflow said, it may be acceptable when minified and gzip'ed.

I wouldn't mind you fork the project, make it smaller and release as a perfect-er scrollbar :smile: 

Anyway, thanks for your interest.
