### ISSUE TITLE
it can't work normal  in "iframe"

### ISSUE THREAD

**Issue by dianbudian** [noraesae/perfect-scrollbar#353]
i used a plug called "colorbox" and load a page as iframe
============================================================
In iframe, I used Ps,and it works.
    Now, the body's original height is 1400px,
    I set body height:620px, but the srcoll looks like just as it was original height.

    Note:http://www.verygrain.com/index.asp#2 , click a button, you can get it.
============================================================
waiting......
Labels BUG,HELP

**Comment by noraesae** [comment]
Hi,

I cannot reproduce the problem in the page you suggested. However, In my opinion you may just call `Ps.update()` or `$(...).perfectScrollbar('update')` to update the view. Please check the iframe height is also fit the size of the page too.

**Comment by noraesae** [comment]
Closed for the inactivity.
