### ISSUE TITLE
I used the .perfectScrollbar(); with a class that have a lot of divs

### ISSUE THREAD

**Issue by Jhonan321** [noraesae/perfect-scrollbar#355]
that div sometimes doesnt need to scroll and have no info, but even in that case appear the scroll

**Comment by noraesae** [comment]
I'm afraid it's too difficult to look into the issue with such a simple and general explanation. Can you provide any example page or jsfiddle? They would help me a lot to find out the reason.

Thanks.

**Comment by noherczeg** [comment]
I think he wants to hide the scrollbar when the content inside is emty.

**Comment by Jhonan321** [comment]
That's right @noherczeg,

![captura de pantalla de 2015-07-13 09 13 01](https://cloud.githubusercontent.com/assets/7134196/8651743/5b6c3468-2940-11e5-947b-87c6ea639b3f.png)

all divs have the same class, but in first div there is no content and even has the scrollbar, what should i do to hide de scroll bar in the first div without broke the rest

**Comment by noherczeg** [comment]
If I'm not mistaken there actually is some text below the top scrolling area. I can certainly see the top of some text there. That's why it's there imho.

**Comment by Jhonan321** [comment]
nop, there is nothing in first item, look

![hallo2](https://cloud.githubusercontent.com/assets/7134196/8658988/1ceef360-296d-11e5-8fb4-88940ca21f32.png)
 and appears the scroll bar, in second one there is more info and the scroll bar is good, in first one is not

**Comment by noherczeg** [comment]
Have you tried the scrollYMarginOffset option? Are there any <br /> tags at the end of the text? Or any leftover whitespaces? If not then it might be some sort of css problem in your code imho :-/

**Comment by Jhonan321** [comment]
nope, there is nothing, and the problem is not that has an empty scroll, the problem is the scrollbar, it appears but the info is static, just appear the bar, there is no scroll

**Comment by Jhonan321** [comment]
anyone???

**Comment by noherczeg** [comment]
Without code I can't think of anything else.

**Comment by Jhonan321** [comment]
you got a personal email? i dont have permission to publish the  url, im pretty sure you shall follow me when you see the real problem

**Comment by Jhonan321** [comment]
????????

**Comment by noraesae** [comment]
Was not sure if you sent me the email. I've got nothing. If you did, can you send me again?

me@noraesae.net

**Comment by Jhonan321** [comment]
you got the url on your inbox! i just send it

**Comment by noraesae** [comment]
I think I've found the reason. The containers have `padding` and your page is using the old version of the plugin, so you should specify `includePadding` option. Please use `.perfectScrollbar({includePadding: true})` instead of `.perfectScrollbar()`.

I've tried with console and it works well, so please tell me if it works for you too.

**Comment by Jhonan321** [comment]
I'll try it and i let u know what happened, thanks bud!

**Comment by Jhonan321** [comment]
i think it does not work
               $('.tpl-paquete-contenido-principal, .taxonomy-term-description').perfectScrollbar({
			suppressScrollX: true,
			maxScrollbarLength: 120,
			includePadding: true
		});

**Comment by Jhonan321** [comment]
i think it does not work
               $('.tpl-paquete-contenido-principal, .taxonomy-term-description').perfectScrollbar({
			suppressScrollX: true,
			maxScrollbarLength: 120,
			includePadding: true
		});

**Comment by Jhonan321** [comment]
u can help me please with the last perfect-scrollbar.js i dont know how to upgrade mine without broke everything, and i didnt install it in drupal...

**Comment by Jhonan321** [comment]
It works, perfect!!! thanks for helping and time you guys!
