### ISSUE TITLE
.ps-scrollbar-x-rail need z-index in sometime

### ISSUE THREAD

**Issue by luhaining** [noraesae/perfect-scrollbar#356]
When perfect-scrollbar be used in float or 'position:absolute' elements, shoud be show with z-index.
Like z-index:999999, how rude it is, but it's wrok.

**Comment by luhaining** [comment]
This issue will be reappear when u used zepto.sortable or jQuery-ui.sortabl.

**Comment by luhaining** [comment]
.ps-scrollbar-x-rail { z-index:999999; }
.ps-scrollbar-y-rail { z-index:999999; }

**Comment by noraesae** [comment]
Thank you for the report. `z-index` may vary for each use case. Some people may need it and some people may not, so for the time being I may leave them to users.

Thank you again!

**Comment by zedtux** [comment]
A `z-index` of 1000 out-of-the-box make more sense to me, as the scrollbar should be always visible. Then in case people needs to change it (1% of the use cases?) then they could override it.
