### ISSUE TITLE
initialize needs a callback

### ISSUE THREAD

**Issue by zubinmehta** [noraesae/perfect-scrollbar#360]
I am trying to use scrollTop just after initialization and it doesn't work. It works if I do it after a small timeout. So ideally I would like to do scrolltop changes within the initialize callback.

**Comment by kotmatpockuh** [comment]
same issue...

**Comment by noraesae** [comment]
It must not need a callback as it's not asynchronous. You can see just sequential code working well in this fiddle.

http://jsfiddle.net/fusmpgdt/1/

It's been tested with latest Chrome, Safari and Firefox in OS X. If your code doesn't work, it may be a different reason such as lazy loading.

If there is still the same problem, please upload the issue with some code examples or fiddles.

Thank you for reporting.
