### ISSUE TITLE
Watch your task runners (missing scrollbars may not be a bug)

### ISSUE THREAD

**Issue by noherczeg** [noraesae/perfect-scrollbar#362]
I'm posting this to prevent others from unnecessary google-ing, and headaches. The maintainer may put this into the docs as well.

So scrollbars weren't showing for me, and I tried lots of things, but the problem was on Grunt's side in my case. I'm using the [bower_concat plugin](https://github.com/sapegin/grunt-bower-concat), and despite the fact that Perfect Scrollbar's bower.js file's main section seems correct, I had to load it explicitly in that grunt plugin.

When I loaded the CSS everything worked fine, so guys the conclusion is to always check your task runners when something odd is happennig :)

Sample code snippet:

```
'use strict';

module.exports = function () {
    return {
        [...]
        vendorCSS: {
            cssDest: 'dist/vendor.css',
            include: [
                [...]
                'ag-grid',
                'angular-ui',
                'font-awesome',
                'perfect-scrollbar'
            ]
        }
    };
};
```

**Comment by noraesae** [comment]
Thank you for the report! I added it in [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ).
