### ISSUE TITLE
TypeError: Cannot read property 'isNegativeScroll' of undefined

### ISSUE THREAD

**Issue by FDiskas** [noraesae/perfect-scrollbar#367]
```
TypeError: Cannot read property 'isNegativeScroll' of undefined
```
Error points to the file: https://github.com/noraesae/perfect-scrollbar/blob/6c642d8a478ce231aad98aee7f6cd541cac816d2/src/js/plugin/update.js#L19

**Comment by noraesae** [comment]
As you may see in the code, the following lines have been added recently and now there may be no problem.
```js
if (!i) {
  return;
}
```

The new version will be released now, so pls wait a little more :smile:
