### ISSUE TITLE
how can i detect the stopScrolling as an event ?

### ISSUE THREAD

**Issue by liquida** [noraesae/perfect-scrollbar#368]
hello guys i need to check when the user leave the scrollbar

i've tried with mouseleave, but it's triggered even when user is scrolling

thanks in advance!

**Comment by noraesae** [comment]
If you mean the event a user stop scrolling, you may consider implementing the feature by setTimeout and `scroll` event. There's no native `stopScrolling` event in JavaScript. I've just written a simple jsfiddle here:

http://jsfiddle.net/d48bdzba/2/

Hope it helps!

**Comment by liquida** [comment]
hello! thanks its working :)

**Comment by noraesae** [comment]
Great to hear that :smile:
