### ISSUE TITLE
window.Event.prototype.stopPropagation.bind : undefined

### ISSUE THREAD

**Issue by spyesx** [noraesae/perfect-scrollbar#370]
Hi there, thx for this work.
I'm using this code on a project and unfortunately it doesn't work at all because of a crash due to an error in ``click-rail.js:14``
```javascript
var stopPropagation = window.Event.prototype.stopPropagation.bind;
``` 
I'm using Chrome and ``stopPropagation`` is ``undefined``.

I installed perfect-scrollbar with a ``npm install prefect-scrollbar --save-dev``.

```javascript

require('perfect-scrollbar/jquery')($);

// then a bit further in a method

$('.scrollable').eq(0).perfectScrollbar();

```
It does the same without jQuery.

I might do something wrong but I just follow the Readme. Any idea?

**Comment by noraesae** [comment]
Hmm, I've just tested it out in my Chrome in OS X and it works well. I don't think Chrome abandons it as it's [W3C Recommendation](http://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-flow-capture).

Pls check there is really no `stopPropagation` through opening an empty page and try `window.Event.prototype.stopPropagation`. I doubt it's not implemented, so please check if other libraries override it.

**Comment by spyesx** [comment]
Thank you very much for this idea. It was a simple line hidden in a package.
``var Event = window.Event = module.exports = function() {};``
Don't know what's the point to write that but anyway, it works now ;)

**Comment by noraesae** [comment]
Great to hear it works! Thanks :+1:
