### ISSUE TITLE
Perfect-Scrollbar in a html textarea component

### ISSUE THREAD

**Issue by dveintimilla** [noraesae/perfect-scrollbar#371]
Hello, i'm just starting with perfect-scrollbar plugin, i'm trying to add perfect-scrollbar to a html textarea component, when i call Ps.initialize(myTextArea), the original text area is removed and the scroll behavior works with the mouse wheel, but the text area section (grey one), never appears.

Could anyone help me with this?

Thanks

**Comment by noraesae** [comment]
As you can find in other issues, a textarea is not a normal HTML container and PS doesn't work well with textarea.

I suggest create a outside div for the textarea, or use other plugins working in the different manner for the time being.

Thanks
