### ISSUE TITLE
Without Require.js

### ISSUE THREAD

**Issue by zeeshanjan82** [noraesae/perfect-scrollbar#372]
Is there any way to use this library without Require.js

**Comment by noraesae** [comment]
As explained in [How to use](https://github.com/noraesae/perfect-scrollbar#how-to-use) section in README, you can just load the script as usual.

```html
<script src='dist/js/perfect-scrollbar.js'></script>
<script src='dist/js/perfect-scrollbar.jquery.js'></script><!-- for jQuery -->
```

And every example in `examples` are written without any help of packaging tool. You may want to start from the basic usage, then `examples/options-default.html` is a good point to start.
