### ISSUE TITLE
How to get the offset value of element on scroll

### ISSUE THREAD

**Issue by mtwallet** [noraesae/perfect-scrollbar#375]
I want to create a sticky header if the element scrolls past xx px's. I would normally use Waypoints for something like this but I'm unsure how to to do it with Perfect Scrollbar. 

How do I get the scroll position of an element within Perfect Scrollbar, please can you help?

**Comment by noraesae** [comment]
Hi, you can use the usual `scrollTop` property of the container.

```js
document.getElementById('test').scrollTop; // vanilla
$('#test').prop('scrollTop'); // jQuery
```

Thanks.
