### ISSUE TITLE
Dynamic div height

### ISSUE THREAD

**Issue by Sanivlei** [noraesae/perfect-scrollbar#376]
Once you update the div size ,the scroll gets duplicated. Even if you send the "update" query or even resetting the scroll bar completely it still get duplicated for some reason. Any way around this ?

**Comment by noraesae** [comment]
Hmm, if there are scrollbars duplicated, the initialise call must be called twice. Can you please put `console.log` and checks if the initialize method is called twice? It means the following code may be called twice.

```
$(...).perfectScrollbar(); // jQuery
Ps.initialize(...); // vanilla
```

**Comment by steel97** [comment]
Got the same problem,here is live example skinov.net,this issue appears when someone writing a message and height of div is updating

**Comment by noraesae** [comment]
I can't find the case where it occurs in the provided page, but if the scrollbar doesn't update its geometry, it's very likely to be the timing issue of the user's code itself. Please check if any asynchronous call is used and ensure the update call is really called after the content is updated.

If it's confirmed that the update call is called later and there's still the issue, please provide code example(preferably jsfiddle) to reproduce the problem. It really helps us narrow down the reason of the problem.

Thanks!

**Comment by steel97** [comment]
Thanks for reply,I am not sure about async calls(i think that it's possible if websockets work asynchronously),but I sure that i call update after content updated,here is code example that executing after one of websocket events:
```
document.getElementById("scr-chatbox-cont").innerHTML += entry;		
chatContainer.scrollTop = 1000000;
Ps.update(chatContainer);
```
P.S Sorry for bad english

**Comment by noraesae** [comment]
Hmm, the code looks fine. Is it the code of the page you provided? If true, can you give me a detailed instruction to reproduce the problem in your page? I'm currently on a travel so it may take a while but I'll check it out when possible.

Thanks

**Comment by steel97** [comment]
Yes this code from my page,I trying to write clean example that can cause this issue,I'll post it here when I finish

**Comment by steel97** [comment]
Ok,ready http://jsfiddle.net/3hn8L85b/8/, i am new to jsfiddle so onLoad method for me not worked and thats why code is not so clean,to reproduce issue just click several times on button

**Comment by noraesae** [comment]
I found the problem, and may fix it in a while. I really appreciate for your report. Please wait a little bit for the fix! 😆

**Comment by steel97** [comment]
looking forward for fix, thanks in advance!

**Comment by steel97** [comment]
Hmm,i think that i understand my problem,here is workaround:http://jsfiddle.net/3Lurqnx0/1/ thanks for help,no fix required anymore)

**Comment by noraesae** [comment]
Your workaround is nice enough, but you need an extra variable to keep track of the content. The patch fixes the problem.

However, I really don't recommend using `innerHTML` itself as it may re-initialize the scrollbar rails every time it calls the update. Creating a inner content `div` or using DOM operations may be the alternatives.

Anyway, thanks!
