### ISSUE TITLE
Drag direction on iPad/Touch

### ISSUE THREAD

**Issue by brendonmm** [noraesae/perfect-scrollbar#377]
Hi, I'm tried to use this plugin as a scrollbar for touch app running on iPad devices and have a little problem. The direction of touch wheel (drag) is inverted for usual mode to scroll.

I'm dragging the scrollbar up to show the content bellow. That's make sense if I using a OS X device (iMac), but not in tablets (like iPad). 

I need to drag scrollbar down, to show bellow items.

There are any way to do that?

**Comment by noraesae** [comment]
I'm not sure I understand well or not. I've just tested with my iOS devices, and the direction was just fine. If you mean the scrolling with scrollbar rails, in touch devices, the content is only scrolled with touch event, not with the rails.

**Comment by brendonmm** [comment]
It's exactly what I mean. There are any way to use rails for scroll the content?

**Comment by noraesae** [comment]
Hmm, it's currently impossible on its own, and we need to modify the code a little bit.

**Comment by brendonmm** [comment]
I'll try some modifications here to implement this feature and if I have "a solution" make a PR here, alright?

**Comment by noraesae** [comment]
Fantastic.

**Comment by noraesae** [comment]
Closed for the inactivity. Please feel free to reopen the issue.
