### ISSUE TITLE
has perfect-scrollbar  support 'easing' to scroll smooth ?

### ISSUE THREAD

**Issue by thanhmabo** [noraesae/perfect-scrollbar#378]
How add easing in perfect-scrollbar

**Comment by noraesae** [comment]
Easing effect is implemented only for touch events. As there is some desktop browsers where the easing effect is implemented by default in native level, it's not implemented for wheel or mouse interactions. By the same reason, I may not add the effect to the plugin by myself. I welcome any PR about it as an optional feature though.

Thanks!

**Comment by thanhmabo** [comment]
Thanks @noraesae
