### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by Dc01m** [noraesae/perfect-scrollbar#380]
Uncaught TypeError: Cannot read property 'split' of undefined (line 28 of the file perfect-scrollbar.js)
line 27 : function oldAdd(element, className) {
line 28 : var classes = element.className.split(' ');

The error appear when i try to use it.
Exemple :
if(block.find(".target").size()>0) {
     var target = block.find(".target");
     console.log(JSON.stringify(target));
     ps.initialize(target); 
  }
});

Console :
{"0":{},"length":1,"prevObject":{"0":{},"length":1},"selector":".target"}
perfect-scrollbar.js Uncaught TypeError: Cannot read property 'split' of undefined

**Comment by noraesae** [comment]
`target` must be a `jQuery` object. `ps.initialize` is for a vanilla JS DOM object. Please use `target.perfectScrollbar()` instead.
