### ISSUE TITLE
Scroll Past Bottom

### ISSUE THREAD

**Issue by BrettStatman** [noraesae/perfect-scrollbar#381]
Hi @noraesae -

I am having the same trouble described here https://github.com/noraesae/perfect-scrollbar/issues/8. Looks like it was fixed, but the problem may have been re-introduced. Is there something I need to do to get this functionality back?

FYI you can see the issue on the Demo page

**Comment by noraesae** [comment]
Was introducted once, but there were still many people who don't want, so it became an optional feature. Please read the documentation and check 'wheelPropagation'.

Thanks.
