### ISSUE TITLE
Error when using with AMDClean

### ISSUE THREAD

**Issue by alahtarin** [noraesae/perfect-scrollbar#382]
I am using Perfect Scrollbar in my project with RequireJS. It works perfect, but after compiling the full project with AMDClean I receive the following error: `Uncaught ReferenceError: main is not defined` in this part of the compiled code:

```javascript
1: [
    function (require, module, exports) {
      'use strict';
      var ps = main;
      if (true) {
        scrollbar = function () {
          return typeof ps === 'function' ? ps() : ps;
        }();
      } else {
        window.PerfectScrollbar = ps;
        if (typeof window.Ps === 'undefined') {
          window.Ps = ps;
        }
      }
      return exports;
    },
    { '../main': 7 }
  ],
```

Any ideas on this?

**Comment by noraesae** [comment]
I've no idea about AMDClean, but the error may be because of `var ps = main;` line. Literally, `main` is defined nowhere.

**Comment by sacredMonster** [comment]
I am facing the same issue and was wondering if you can tell me what the fix/issue was??

Thanks..
