### ISSUE TITLE
Scrollbar not visible on load of a modal

### ISSUE THREAD

**Issue by DaRR2121** [noraesae/perfect-scrollbar#384]
When you open a modal the scrollbar is invisible and only when you start scrolling does it appear. How can I get it to be visible the moment the modal is open? I've already changed the opacity's to 1.

**Comment by noraesae** [comment]
If it appears when starting scrolling, it's very likely to be a timing issue. Please ensure that an update method is called after the content is filled. I'm not sure which modal is being used, but there may be a callback to handle it.

**Comment by DaRR2121** [comment]
Hey Noraesae! I made a post on Stackoverflow. http://stackoverflow.com/questions/32576843/perfect-scrollbar-not-showing-updating-the-scrollbar-in-modal. :) I'm still very new to all coding and the likes.

**Comment by DaRR2121** [comment]
I've tried putting    
    remodal.$bg.addClass(remodal.settings.modifier);
    remodal.$overlay.addClass(remodal.settings.modifier).show();
    remodal.$wrapper.show().scrollTop(0);
    remodal.$modal.focus();
   remodal.perfectScrollbar('update');

but that doesn't work.

**Comment by DaRR2121** [comment]
Solved it by calling scrollbar after modal content loaded. :)
