### ISSUE TITLE
Scrolling becomes extremely slow after floating layer is hidden

### ISSUE THREAD

**Issue by leoloso** [noraesae/perfect-scrollbar#387]
Hi Jun, thanks for your plug-in, I use it all over my website and find it extremely valuable.

There's an issue which I'm 95% sure belongs to your plug-in, when interacting with other plug-ins: whenever a floating layer is created on top of the perfect-scrollbar div, and then this floating layer is hidden, the perfect-scrollbar div becomes very sluggish to scroll. Only when clicking again on the perfect-scrollbar container div, scrolling it becomes normal again.

You can check the behavior in my website http://www.mesym.com. There, all panels (the one on the left, the one on the top, and the body) are perfect-scrollbar containers. To reproduce the problem:

1- Go to http://www.mesym.com/add-event/ (no need to log in)

![mesym-issue-step1](https://cloud.githubusercontent.com/assets/1981996/10067237/4f8ed56c-62cd-11e5-8120-4f82d208e1e8.png)

2- Click on "Date/Time*" input: this creates a floating layer on top of the perfect-scrollbar container

![mesym-issue-step2](https://cloud.githubusercontent.com/assets/1981996/10067235/4f8c7aa6-62cd-11e5-9eff-e9f09a99c797.png)

3- Select a date range, and click on "Apply": this closes the floating layer, adding "display: none;"
4- Try to scroll on the body container: it became very sluggish
5- Click on the body container and scroll again: it works fine again.

![mesym-issue-step3](https://cloud.githubusercontent.com/assets/1981996/10067236/4f8e72d4-62cd-11e5-93a5-faa4cf4676da.png)

![mesym-issue-step4-5](https://cloud.githubusercontent.com/assets/1981996/10067234/4f8bbc9c-62cd-11e5-9726-0ab5bf76de29.png)

This happens with all floating layers. Eg: if you click on the tinymce's "change font color" button, or "add link" button, it also happens.

Anything I can help with (mainly testing), please let me know.

Cheers,
Leo

**Comment by leoloso** [comment]
I'm using Google Chrome Version 45.0.2454.99 (64-bit)

**Comment by noraesae** [comment]
Sorry for the late response. The page seems changed, and I close this issue for the time being. If there is further problem, please feel free to reopen it. JSFiddle may be better for debugging too.

Thanks.
