### ISSUE TITLE
Selection scrolling optional

### ISSUE THREAD

**Issue by igortd** [noraesae/perfect-scrollbar#388]
Is it possible to disable the scrolling on selection trough some option or configuration?

I know that you can disable this option with commenting this line:
```
selectionHandler(element);
```
but that is not good practice.

If not is there plan this to be added as option?

**Comment by bugfreetech** [comment]
you have the same problem as https://github.com/noraesae/perfect-scrollbar/issues/393 and I still cannot make mine touch-scroll
what broswer & os?

**Comment by noraesae** [comment]
I've added `useSelectionScroll` option, the default value of which is `false`: 17e5f67519a0ca11ed22be064edff43bfac6452e

I also thought it's better to be disabled by default, as not so many users may use it, but it can cause many problems.
