### ISSUE TITLE
Can it be used with middle-button autoscroll like jquery.scrollbar?

### ISSUE THREAD

**Issue by imShara** [noraesae/perfect-scrollbar#389]
![270x238ximage136 png pagespeed ic otxzs_vmdr](https://cloud.githubusercontent.com/assets/4913196/10078700/9bb54978-62ee-11e5-892f-0e681a13b812.png)

[jquery.scrollbar example](https://gromo.github.io/jquery.scrollbar/demo/basic.html)

**Comment by bugfreetech** [comment]
+1 this -- it was one of the first things i tried and it simply makes the main page scroll

**Comment by imShara** [comment]
@bugfreetech, i think they don't approve patch for this, because it can be made only with hacks, wich not works in some browsers. I probably will make purejs port of jquery-scrollbar.

**Comment by imShara** [comment]
@bugfreetech, there is cool [gemini-scrollbars](https://noeldelgado.github.io/gemini-scrollbar/).

**Comment by bugfreetech** [comment]
@imShara thanks, looks very nice

**Comment by noraesae** [comment]
Merged into #412. Thanks for the interest, guys!
