### ISSUE TITLE
scroll with mouse not working if top not in view

### ISSUE THREAD

**Issue by madebycambiamentico** [noraesae/perfect-scrollbar#390]
i'm currently using google chrome, but the problem is there in firefox too. I'm using the jquery one.

if the scrollbarred element is not fully contained in the window, or to be precise, if the element top is not in view (because the document is scrolled down), the plugin fails to scroll-y the content.
in the demo you created (http://noraesae.github.io/perfect-scrollbar/), the plugin fails too.

to reproduce the problem:
scroll document until the #Demo div top is partially invisible in your window.
try to scroll using the bars in the #Demo div
(it will not move)

**Comment by DanielApt** [comment]
To be clear, do you mean that dragging the scroll track (highlighted in the below image) does not work when the browser is scrolled down?

![screen shot 2015-09-29 at 15 15 02](https://cloud.githubusercontent.com/assets/52545/10166660/f7d97360-66bc-11e5-890c-8bca43a133d9.png)

**Comment by Reeker94** [comment]
Actually, it doesnt work if scroll container bigger than window height :<

**Comment by DevertNet** [comment]
+1

**Comment by DanielApt** [comment]
Fixed it. Ready to be released @noraesae

**Comment by noraesae** [comment]
Great job! Will release in a while.
