### ISSUE TITLE
Firefox and perfectScrollbar (jQuery)

### ISSUE THREAD

**Issue by RS2065** [noraesae/perfect-scrollbar#391]
Hi,

I have used perfect scrollbar in simple static html page. When I open the page in Firefox there is an exception:
window.getComputedStyle (...) is null

An exception is caused in the method:
cssGet function (element, styleName) {
   return window.getComputedStyle (element) [styleName];
}

In fact window.getComputedStyle sequence (element) returns null, which results in an error. Situations improves modify the code to the form:

cssGet function (element, styleName) {
   var style = window.getComputedStyle (element);
   return style? Styles [styleName]: null;
}

(FireFox 40.0.3, jQuery 1.10.2)

Thanks

**Comment by DanielApt** [comment]
Thanks @RS2065 for flagging. Could you share an example where this is happening, as I can't reproduce it with the info you've shared.

**Comment by noraesae** [comment]
Closed for inactivity. Please feel free to reopen.

**Comment by thanhansoft** [comment]
I same you, please help me
