### ISSUE TITLE
dist folder is missing for version with Events

### ISSUE THREAD

**Issue by pmtarantino** [noraesae/perfect-scrollbar#392]
Hi! I am interested in the new version of perfect-scrollbar, that includes the events. However, I couldn't find it for download, only the sources. I checked the examples and it is trying to include the js files from a dist folder, but that folder is missing from the repo.

Are you planning to release the .min.js files with the events soon? Thank you!

**Comment by DanielApt** [comment]
@pmtarantino Currently there has not yet been an official release with the events implemented. I'd still like to do some further testing and possible optimisation before I give the green-light for @noraesae to release.

Is this urgent? I can generate the `.min.js` files if you need it soon.

**Comment by pmtarantino** [comment]
Hi Daniel, if you could generate the `.min.js` would be great because we are needing it to keep working on this project. We are using the jQuery plugin, by the way.

**Comment by DanielApt** [comment]
Just sent you an email with the files.

**Comment by pmtarantino** [comment]
Thank you Daniel, you are the best :) It worked like a charm!
