### ISSUE TITLE
Swipe (?) bug while selecting text

### ISSUE THREAD

**Issue by iKorso** [noraesae/perfect-scrollbar#393]
Hello, im sorry for this message, but i cant understand why i got this bug, using your plugin.
There is 2 short videos:
http://recordit.co/iOmqokueGC
Im trying to select text from down to up and container with initialized PS acting like im using touch event...
And here http://recordit.co/iOmqokueGC
Im selecting text from up to down and after some tries scrolling event works even if im not pressing anything.

I didn't change anything in source code, used jquery to initialize scrollbar:
`$('.custom-scrollbar').perfectScrollbar()`
Can anyone help me with this issue?

**Comment by bugfreetech** [comment]
i wish my elements had touch dragging on PC, how did you manage that? What browser? What OS?

**Comment by noraesae** [comment]
Selection scroll is disabled by default. Please refer to #388.

Thanks for the report!
