### ISSUE TITLE
When scrolling, Need to add new class in jQuery perfect scrollbar

### ISSUE THREAD

**Issue by nareshkumar2110** [noraesae/perfect-scrollbar#394]
I am using jQuery perfect-scrollbar to my web application. I have called perfect-scrollbar in ready function like this

jQuery(document).ready(function ($){
    "use strict";
    $('.cs-scroll, .cs-scroll-2').perfectScrollbar();
});

How can i add the new class in perfect-scrollbar?

Can you help me ?

**Comment by noraesae** [comment]
What do you mean by the new class?

**Comment by VPenkov** [comment]
```javascript
$('.cs-scroll, .cs-scroll-2').each(function(){
$(this).perfectScrollbar();
});
```

**Comment by DanielApt** [comment]
@nareshkumar2110 Could you please elaborate on the issue?

**Comment by noraesae** [comment]
Closed for the inactivity.
