### ISSUE TITLE
Bootstrap dropdown closed in Chrome after scrolling perfectScroll

### ISSUE THREAD

**Issue by sly-slaw** [noraesae/perfect-scrollbar#396]
When scrolling perfectScroll bootstrap dropdown closed in Chrome. In Firefox work fine. How to fix?
http://jsfiddle.net/rd2d2/aqvfx6j6/

**Comment by noraesae** [comment]
You mean scrolling with mouse click, right? I think calling `stopPropagation` on the scrollbar rail click event may work, but not sure. Can you please try it?

**Comment by forivall** [comment]
Enjoy. [Click here if you want a PR of it](https://github.com/noraesae/perfect-scrollbar/compare/master...forivall:issue396?expand=1). It's not complete at all, but it's most of the hard work. Definitely needs to go behind a flag.

**Comment by sly-slaw** [comment]
I tried , but stopPropagation not working. http://jsfiddle.net/rd2d2/aqvfx6j6/2/

**Comment by sly-slaw** [comment]
worked, thanks!
http://jsfiddle.net/rd2d2/aqvfx6j6/3/

**Comment by noraesae** [comment]
Good to hear it works. :+1:
