### ISSUE TITLE
No dist directory in repository

### ISSUE THREAD

**Issue by ecipil** [noraesae/perfect-scrollbar#397]
I have downloaded the whole repository (master branch) in my local, but there is no dist directory, so no perfect-scroll js and css. Did you may miss to upload dist directory ?
Thanks

**Comment by noraesae** [comment]
`dist` is not included in the repository, because in it there are built files. You can build it by yourself with `gulp`, or download built source files in [releases](https://github.com/noraesae/perfect-scrollbar/releases). There is also `dist` when installed with `npm`.

Thanks

**Comment by forivall** [comment]
public service announcement: github releases are great!
