### ISSUE TITLE
[Browserify] Require perfect-scrollbar return an empty object

### ISSUE THREAD

**Issue by roedit** [noraesae/perfect-scrollbar#398]
I saw this issue #288 closed from feb 25. It looks that the issue is still there.
I'm using the latest /* perfect-scrollbar v0.6.7 */
Thanks. Keep up the good job !

**Comment by noraesae** [comment]
I've just test quickly and it worked well in my env. How did you install Ps? Which version of Browserify do you use?

Thanks

**Comment by roedit** [comment]
I'm using it as a thirdparty. 
browserify: {
            public: {
                options: {
                    transform: [
                        ['babelify', {
                            loose: 'all',
                            "compact": false
                        }]
                    ],
                    alias: [
                        '../public/client/thirdparty/react-0.13.3/react-with-addons.min.js:react',
                        '../public/client/thirdparty/jquery-2.1.4/jquery-2.1.4.min.js:jquery',
                        '../public/client/thirdparty/react-bootstrap/react-bootstrap.min.js:bootstrap',
                        '../public/client/thirdparty/perfect-scrollbar/perfect-scrollbar.min.js:scrollbar'
                    ]
                },
                files: {
                    '../public/client/js/compiled/shared.concat.js': ['../public/client/js/concat/shared.concat.js']
                }
            }
        }
"grunt-browserify": "^3.8.0",
So i'm pointing to the downloaded file. I have a better control like this.
When I require the library like this Ps is an empty object.
Thank you!

**Comment by noraesae** [comment]
I'm sorry for the late response. It may not work well with the downloadable version. I recommend using it with `npm`. If you still prefer to use the static version, you may be able to consider using a whole file tree under `src/js` and load `main.js` in the directory.

Sorry that it may not satisfy your need.
