### ISSUE TITLE
Perfect scrollbar overlapping resize element

### ISSUE THREAD

**Issue by steve-mcqs** [noraesae/perfect-scrollbar#403]
I have divs that use the perfect scroll bar. However these divs are also resizeable. The problem I am having is that the scroll bar is overlapping the re size element and when trying to resize I just end up grabbing the scroll bar. Has anyone dealt with this issue already?

**Comment by noraesae** [comment]
As I understand, the divs are resized using a custom method? Then as a naive workaround, you can disable(or destroy) PS when starting to resize, and re-initialise when finishing.

If my understanding was wrong, could you specify the case a bit more, preferably with an example or a jsfiddle?

**Comment by noraesae** [comment]
Closed for inactivity. Please feel free to reopen.
