### ISSUE TITLE
IE11: Click on scroll bar does not move scroll handle

### ISSUE THREAD

**Issue by sondreb** [noraesae/perfect-scrollbar#409]
On IE11, it is not possible to click the scroll bar (light area) to scroll, only supports clicking the scroll handle and move it with mouse (or touch).

**Comment by pliasetski** [comment]
Hello,
I have the same problem in IE10 and IE11. But for only scroll down doen't work. Please see this video file for more details:
https://www.dropbox.com/sh/55w3nbu2jdnq6ew/AAAsjewRHCbDMkdizqtDw7bwa?dl=0

**Comment by Chehow** [comment]
Hi guys!

Any progress with this issue? I have the same problem and this really important for my project.

Thx in advance.

**Comment by DanielApt** [comment]
@Chehow I haven't had a chance to look in to this yet. I'm still tackling a different issue first, before I'll address this issue.

If you want to have a look, I believe the issue would be in [`handler/click-rail.js`](https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/click-rail.js).

If you do find anything, please let me know.

**Comment by pliasetski** [comment]
Hello,
I've checked this file: https://github.com/noraesae/perfect-scrollbar/issues/409
There is no window.scrollY and window.scrollX in IE11 and below. It works only in edge.

https://developer.mozilla.org/ru/docs/Web/API/Window/scrollY

**Comment by DanielApt** [comment]
Thank you @pliasetski. I've addressed the bug now.
