### ISSUE TITLE
Middle click scrolling

### ISSUE THREAD

**Issue by harangue** [noraesae/perfect-scrollbar#410]
It'd be fantastic if the middle-click, mouse move behavior that typically allows pages to scroll also functioned with Perfect Scrollbar.

**Comment by zomp** [comment]
Hi @harangue, note please, that is probably only a Windows behaviour and on plenty of other systems there are different actions on middle-click (e.g. a very useful clipboard).

**Comment by noraesae** [comment]
Merged into #412. Thanks for the interest!
