### ISSUE TITLE
Touchstart event is not propagated 

### ISSUE THREAD

**Issue by jinmingyougit** [noraesae/perfect-scrollbar#411]
in touch.js, touchstart event is always propagated.  Can we do something about it. 
We need touchstart event to be propagated in order to scroll outside since we have in house scrolling solution on mobile instead of native scrolling. 

https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/touch.js#L89

And also, what is the inGlobalTouch trying to prevent? Isn't inLocalTouch good enough for telling if the scroll is inside the dom or not?

**Comment by noraesae** [comment]
Hello,

There's currently no way to make a `touchstart` event propagate to the parent. It is to prevent the parent div scrolling at the same time when the PS container is scrolling. I'm not sure if there is a workaround to force-propagate the `touchstart`event only when we need to do.

For `inGlobalTouch`, I'm also not sure as the implementation was quite old, but my guess is that it's to tell a scrolling from multi-touch gesture. For example, a user can pinch the page while putting thumb outside of the container and a finger inside the container.

I'm sorry for the inconvenience. I welcome any contribution to make it better :smiley:

**Comment by jinmingyougit** [comment]
Hi,  

Thanks for the quick reply. I think we should be able to prevent the parent div scrolling by prevent touchMove event already. The code is pretty much in place. https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/touch.js#L113
It will prevent parent scrolling if the inside ps container is still in the middle of scrolling(not hitting the boundary yet). 

However, in order to totally remove the stopPropagation in touchStart handler, we need to get rid of the document touchstart handler, since it will cause cause inGlobalTouch to be true and cause touchMove handler to be never executed even if it inside the local touch.  

I understand getting rid of the document touchstart/end handler will cause unnecessary calls for multi-touch gesture. But I think it is worth it compare to not having touchStart event.  I am going to have a PR for this soon.  

Thanks again for your comments.

**Comment by noraesae** [comment]
Now scroll propagation is supported in mobile too with the `swipePropagation` option. Thank you very much for your report.
