### ISSUE TITLE
Middle click scrolling

### ISSUE THREAD

**Issue by noraesae** [noraesae/perfect-scrollbar#412]
`perfect-scrollbar` hooks the scrolling event, and virtualising it with JavaScript. So, if we try to add another scrolling method, it means we add another scrolling emulation. Especially, middle click scrolling contains UI issues such as the indicating cursor, and it's really not so easy as keyboard scrolling.

Though, it has been requested several times and I think supporting it seems reasonable enough, so I'd like to consider it as a public enhancement. Anybody can contribute on this issue.

**Comment by noraesae** [comment]
This may not be supported officially in PS, as it's quite difficult to emulate naturally with only JS and may cause further problems. Instead of implementing this, PS will provide a new way to write PS plugin in v1, so it will be much easier for anybody to write a new scroll emulator.

**Comment by joejordan** [comment]
Any progress on this issue? Picked up a project with perfect-scrollbar, but losing my usual habit of middle-clicking to scroll is a difficult thing to give up.

FYI this is on Windows 10, and it appears to work in Edge, but fails in Chrome and Firefox.
