### ISSUE TITLE
Providing source files in bower repo

### ISSUE THREAD

**Issue by jmaks1** [noraesae/perfect-scrollbar#417]
WARNING in ./lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js
Critical dependencies:
2:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./lib/perfect-scrollbar/js/perfect-scrollbar.jquery.js 2:113-120

WARNING in ./lib/perfect-scrollbar/js/perfect-scrollbar.js
Critical dependencies:
2:113-120 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.

Hello, my english is bad, sorry for this.
When i use webpack and load this module through bower i recieve this message. Npm package is ok.

**Comment by noraesae** [comment]
Some what related with #408. I'm still not sure the source files should be included in bower, as using NPM may be just enough. The plugin is currently being uploaded on bower too, but it's really a minimum effort.

However, I understand that there are still many bower users asking this, so may consider in later releases. I'm sorry but please use NPM repo for the time being.

Thanks.

**Comment by DanielApt** [comment]
@jmaks1 feel free to let me know if you have any issues with perfect scrollbar and webpack. We use the npm package, and it works just fine.

**Comment by jmaks1** [comment]
i'm loaded all packages from bower and one from npm) 
perfectionist in me suffering

**Comment by wujekbogdan** [comment]
+1

I include all the *.scss files directly from bower components. For perfect-scrollbar i had to make an exception and copy the file into my /src/scss/ directory. I feel bad about it.

**Comment by noraesae** [comment]
From 0.6.8, `src` directory will be included in the bower package too.

Thanks guys!
