### ISSUE TITLE
Integration with jQuery Sortable

### ISSUE THREAD

**Issue by kstover** [noraesae/perfect-scrollbar#419]
I'm integrating perfect scrollbar with jQuery sortable. The sortable list is inside a container that has perfect scrollbars applied, and everything works as I'd expect, but dragging an item does not make the scrollbar scroll. I've tried the scroll on selection option, but can't seem to figure out how to enable scrolling while dragging the sortable. Any help would be greatly appreciated.

**Comment by DanielApt** [comment]
@kstover could you please create a jsfiddle? This will help us address this quicker.

**Comment by kstover** [comment]
@DanielApt Sure! I'm a bit busy with other things, but will get a fiddle up in a couple of hours.

**Comment by Perezmarc** [comment]
Hey, 
I'm struggling with the same issue, did you solve it?

Thanks!

**Comment by DanielApt** [comment]
Could you set up a jsfiddle?

**Comment by noraesae** [comment]
Closed for inactivity. Please feel free to reopen.

**Comment by rmemon** [comment]
Hi @DanielApt 

I am facing same issue and created jsfiddle, 

**jQuery sortable without perfect scrollbar:**
https://jsfiddle.net/rahilmemon/dsh1x34v/3/

**jQuery sortable Integrating perfect scrollbar:**
https://jsfiddle.net/rahilmemon/dsh1x34v/4/

Thanks in advance
