### ISSUE TITLE
Jquery Resizable perfect scroll on initial height and width.

### ISSUE THREAD

**Issue by mandar-k** [noraesae/perfect-scrollbar#421]
I'm using ps with a jquery resizable div.
even if the div is at its initial height and width and no contents are overflowing still the Perfect scrollbar shows up on hover.

only css used for resizable div:

.resizable { 
  width: auto;  
  margin: 1%;
  min-height: 100px;
}

**Comment by noraesae** [comment]
I guess jQuery Resizable dynamically changes the geometry of the container after it is initialized. Can you provide a fiddle or an example to reproduce the problem?

**Comment by mandar-k** [comment]
thnx for the support but problem is resolved now with small changes in css for resizable div and ps css.
