### ISSUE TITLE
Browser scroll bar does't work if i'm within perfect-scroll area

### ISSUE THREAD

**Issue by yasirhaleem** [noraesae/perfect-scrollbar#423]
how to make default browser scroll bar works if i reached end of the content with in perfect-scroll bar

please see picture below

![2015-11-23_1345](https://cloud.githubusercontent.com/assets/989956/11332599/dafe7342-91e8-11e5-9543-206f1b41addf.png)

**Comment by noraesae** [comment]
Hi,

Please refer to the [`wheelPropagation`](https://github.com/noraesae/perfect-scrollbar#wheelpropagation) option.

Thanks!

**Comment by yasirhaleem** [comment]
Hi,

Thanks a lot for the reply, i have set wheelPropagation to true

$('.ui-panel-content').perfectScrollbar({ 
          wheelPropagation:true
         });
.ui-panel-content{height:500px;}
but its too much sluggish almost not responding

i'm implementing perfect scroll bar to primefaces dashboard component
http://www.primefaces.org/showcase/ui/panel/dashboard.xhtml

so there will be multiple scrollbars 

another thing i don't see scrollbar inside .ui-panel-content  but inplace of default chrome scrollbar i'm on mac.

**Comment by yasirhaleem** [comment]
here is the fiddle https://jsfiddle.net/yasirhaleem/b7ng0h9k/3/ please scroll slow within

**Comment by DanielApt** [comment]
@yasirhaleem I've not noticed any performance issues. I did notice your jsfiddle is missing `position: relative`

Could you provide us with more details re. your machine and browser's set up?

**Comment by yasirhaleem** [comment]
@DanielApt  great!! because of position:relative ( sorry i missed that ) now i see the scrollbar but scrolling effect is same its almost not responsive.

when i reached end point of div having perfect-scroll scrollbar and i'm scrolling inside div to see bottom content or move to bottom i can't.

i'm on Mac Yosemite using Chrome latest version.

i can prepare short video if needed.

**Comment by DanielApt** [comment]
@yasirhaleem Yes please, could you provide a video?

**Comment by yasirhaleem** [comment]
@DanielApt please click below link to see video, please use mouse pad for scrolling.

http://screencast.com/t/NKRlaIiH

**Comment by akocmark** [comment]
this happens to me also. Im on elcapitan mac. latest chrome

**Comment by noraesae** [comment]
I cannot see the issue now in OS X El Capitan and the latest Chrome. I used trackpad.

https://www.youtube.com/watch?v=BPK12F0CO-Y

**Comment by noraesae** [comment]
Closed for the inactivity.
