### ISSUE TITLE
Packagist integration

### ISSUE THREAD

**Issue by ruslan-fidesio** [noraesae/perfect-scrollbar#426]
Could you put it on packagist ?

**How to ?**

Create a new account on Packagist.org. Hit the “Submit Package” button. 
Copy-paste the plugin’s online git repository URL to the input field and hit “Check”. 
Finish the process.

**Comment by noraesae** [comment]
Hello,

Thank you for the information, but the plugin is not a PHP package and it seems not appropriate to add it in Packagist. Please use NPM instead for JavaScript packages.

Thanks,
