### ISSUE TITLE
Use variables in main.scss

### ISSUE THREAD

**Issue by megapctr** [noraesae/perfect-scrollbar#427]
The [How can I make the scrollbar always visible](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ#how-can-i-make-the-scrollbars-always-visible) FAQ section offers two ways to achieve such effect: Modify the source scss (unweildy) or pile some other css on top of it (redundant). I think the best way to achieve this is to define variables in the `main.scss` file.

I.e. change this
```
@mixin scrollbar-rail-default {
  . . .
  opacity: 0;
}
```
to
```
$rail-default-opacity: 0 !default;

@mixin scrollbar-rail-default {
  . . .
  opacity: $rail-default-opacity;
}
```

Then we can simply do this:
```
$rail-default-opacity: 0.6;
@import '~perfect-scrollbar/src/css/main.scss';
```

**Comment by noraesae** [comment]
I like the idea. #433 indeed adds variable usages, and may be merged soon.

**Comment by DanielApt** [comment]
#433 has been merged now.
