### ISSUE TITLE
Issue Nested Scroll Containers with Events

### ISSUE THREAD

**Issue by nthibert** [noraesae/perfect-scrollbar#428]
Hello,

I have been working with your library for quite some time now. I really enjoy. As of recently, I needed to use the events to trigger some functionality. The idea is to have a nested container scroll, and on that scroll stop pagination in the handler. What seems to have happened is, when triggering the scroll again the handler doesn't get fired. It also does not get fired for any other scroll container on the page.

So I went into the libs code, and found that the events are only getting created once, stored in memory. So this so when I do stopPagination() on the event, it will never fire. Unfortunitly, due to the project I am working in, I was unable to create a fork. 

The solution I found for this was to bring all the events creations into the module.experts function. This way the events get created when they are needed. Usually events should never keep state. They should be created when they are needed. Maybe a way to optimize my approach is to create the event right before it is dispatched, so that not all events are created when only 1 or 2 should be dispatched.

**Comment by DanielApt** [comment]
Could you create a jsfiddle demonstrating this issue?

**Comment by noraesae** [comment]
Closed for the inactivity.
