### ISSUE TITLE
Question...

### ISSUE THREAD

**Issue by red111** [noraesae/perfect-scrollbar#429]
Probably this is not a place for asking this question, but unfortuanlly I dont see any forum or other way to ask....

I am trying to createa "Perfect Scrollbar" using this:

https://noraesae.github.io/perfect-scrollbar/

With the most simple possible code:

&lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js&quot;&gt;

&lt;/script&gt; &lt;link rel=&quot;stylesheet&quot; href=&quot;/css/perfect-scrollbar.css&quot; /&gt; 

&lt;script src=&quot;/js/perfect-scrollbar.js&quot;&gt;&lt;/script&gt; 

&lt;script type=&quot;text/javascript&quot;&gt; $(document).ready(function(){ 

$(&quot;#msgid&quot;).html(&quot;This is Hello World by JQuery.&quot;); 

$('#msgid').perfectScrollbar(); }); &lt;/script&gt; 

&lt;div id=&quot;msgid&quot;&gt;&lt;/div&gt; 

And I have the following error:

    TypeError: $(...).perfectScrollbar is not a function

Of course every js/css is pointing to the right direction, if needed you can see it live here:

http://florida.red111.net/a.html

Looks like jQuery is not recognizing the library,

Any ideas?

Thanks in advance.

**Comment by DanielApt** [comment]
It appears you are using the vanilla javascript file. Instead you should use the jquery adaptor. You can find this in `/dist/js/perfect-scrollbar.jquery.js` (after building with gulp)

Please re-open if you need further help.
