### ISSUE TITLE
[Improvement] Get rid of border-radius() and transition() mixins

### ISSUE THREAD

**Issue by wujekbogdan** [noraesae/perfect-scrollbar#431]
There's no need to use these mixins:
1. Mixins names are very general it can cause conflcts with existing mixins.
2. There's a better solution: gulp-autoprefixer.

**Comment by noraesae** [comment]
`gulp-autoprefixer` looks nice. Can you provide a PR for it?

**Comment by wujekbogdan** [comment]
Sure: https://github.com/noraesae/perfect-scrollbar/pull/434

**Comment by noraesae** [comment]
Merged. Another superb work :+1:
