### ISSUE TITLE
[feature] Make perfect-scrollbar easily themeable

### ISSUE THREAD

**Issue by wujekbogdan** [noraesae/perfect-scrollbar#432]
Hi,

I use perfect-scrollbar widely across the site and I needed an ability to create themes with ease.

I came up with an idea:
- All the visual styles could be moved to variables.
- These variables could be put in a scss map.
- Then we could pass the map as a parameter to `ps-container()` mixin
- Thanks to scss `map_get()`, we could easily grab the variables from the map
- We could create our own map, and thanks to scss `map-merge()` function we would be able to extend defaults with our own map. So we wouldn't be forced to define all the values for each theme
- Additional `'theme'` option could be passed in the settings object to the `.initialize()` method. It defines a class name which is added to the `.ps-container` element when the plugin is being initialized. The class is prefixed with `ps-theme` so it's removed when ps is destroyed.

Additional comments:
- Yes. I know that because of `.ps-container()` mixin almost all the styles are outputed in each theme. This is redundant, and makes the output CSS file bigger. But because of HTTP Gzip compression we shouldn't worry about it at all. 
- If we don't want to create multiple themes but just overwrite default values, we don't need to create a map. We can simply overwrite default scss variables. We could even do it before the perfect scrollbar `main.scss` file is imported because all the variables are defined with `!default` statement.
- scss files are split into partials. So we can import all of them or just pick some of them (for example exclude `variables.scss` not to polute the global namespace with `$ps-*` variables)

Here's a pull request: https://github.com/noraesae/perfect-scrollbar/pull/433

**Comment by sharpshark28** [comment]
Something like this would be great. I feel dirty practically needing to !important override most of the styles to adjust it to look like what a designer expects it to look like. Even basic color swaps are like this.

**Comment by wujekbogdan** [comment]
@sharpshark28 
So you can give it a try. Here's a fork I created: https://github.com/wujekbogdan/perfect-scrollbar/tree/Make-perfect-scrollbar-easily-themeable-%23432

**Comment by pedro380085** [comment]
:+1:

**Comment by noraesae** [comment]
PR merged. Great work!
