### ISSUE TITLE
Jumping scroll in IE 10/11 WIndows 7

### ISSUE THREAD

**Issue by pliasetski** [noraesae/perfect-scrollbar#435]
Hello,
When you scroll in IE 10/11 (only on WIndows 7) it is scrolled with jumps (I mean scroll bar rail). Please see attached video: https://dl.dropboxusercontent.com/u/73896408/jumping%20scroll.avi
Maybe you could help with this problem or specify what the problem may be related with.

With best regards

**Comment by noraesae** [comment]
Related with #160, and there is no really good solution for the time being. Some workarounds are suggested in the thread, so please have a look.

Sorry that it can't help so much :disappointed:
