### ISSUE TITLE
Accessibility Support (Using Keyboard)​ - The second Change

### ISSUE THREAD

**Issue by chavishindler** [noraesae/perfect-scrollbar#437]
regarding https://github.com/noraesae/perfect-scrollbar/issues/425:
Thanks for the change.

But what about the second change:
in perfect-scrollbar/src/js/plugin/handler/keyboard.js remove lines 49-51:

if (!hovered) {
return;
}

these lines cause the keyboard up/down keypress to work only on mousehover - and the accessibility rule is that when you focus on the scrollbar you can go up and down also not on mousehover.

waiting to your reply.

**Comment by noraesae** [comment]
It may be changed to `if (!hovered && !focused)` and set `focused` as it should be.

**Comment by chavishindler** [comment]
Sounds good.
Is it going to be fixed soon?
Thanks

**Comment by noraesae** [comment]
Will do this tonight.

**Comment by noraesae** [comment]
Fixed. Thank you very much for the report :smile:

**Comment by chavishindler** [comment]
Thanks!
Can you release a formal version?

Waiting for your reply...

**Comment by noraesae** [comment]
Will release a new version in a while, but I'm afraid not right now. I'll tell you when it's released, hopefully soon.
