### ISSUE TITLE
Submit to JSDelivr

### ISSUE THREAD

**Issue by bradvogel** [noraesae/perfect-scrollbar#439]
Would be great to have this on JSDelivr so we can download it with our other scripts (via JSDelivr's concatenation feature).

See https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md

**Comment by brauliobo** [comment]
+1

**Comment by noraesae** [comment]
PR prepared :rocket: 

https://github.com/jsdelivr/jsdelivr/pull/10049

**Comment by noraesae** [comment]
Merged. It may take some time for the JSDelivr machine will actually load the scripts, but maybe soon.

Thanks.

**Comment by brauliobo** [comment]
Nice, thanks!

Em ter, 23 de fev de 2016 13:33, Jun <notifications@github.com> escreveu:

**Comment by brauliobo** [comment]
the link for usage: https://www.jsdelivr.com/projects/perfect-scrollbar

**Comment by bradvogel** [comment]
Thanks all!
