### ISSUE TITLE
Any plan for AngularJS!

### ISSUE THREAD

**Issue by elmor34** [noraesae/perfect-scrollbar#442]
what about an Angular implementation?

**Comment by rayronvictor** [comment]
Try [angular-perfect-scrollbar](https://github.com/itsdrewmiller/angular-perfect-scrollbar).

**Comment by ethanmay** [comment]
I would not recommend using angular-perfect-scrollbar. It is no longer actively maintained.

**Comment by elmor34** [comment]
Thanks....

On Wed, Jan 20, 2016 at 8:35 PM, Rayron Victor <notifications@github.com>
wrote:

> Try angular-perfect-scrollbar
> <https://github.com/itsdrewmiller/angular-perfect-scrollbar>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/noraesae/perfect-scrollbar/issues/442#issuecomment-173318057>
> .
>



-- 
Gokhan AYKAN

**Comment by noraesae** [comment]
We're trying to make it independent from any specific framework. Yes, we support jQuery, but it's rather a legacy, other than support(perfect-scrollbar used to be a jQuery plugin).

As recommended above, there's angular-perfect-scrollbar and also angular-perfect-scrollbar-2, I've tried nor though.

Sorry that I cannot help so much, and thanks for your interest.
