### ISSUE TITLE
Position of scrollbar in rail

### ISSUE THREAD

**Issue by vAhyThe** [noraesae/perfect-scrollbar#444]
Hi, can i know how far on `y-scroll` i m when scroling down/top. Is there possibility to know the position maybe in percentage like `top: 50%` and some callbacks maybe. 

e.g. i will scroll to bottom `position top: 100%` some callback can be called ?? like `scrollbottom : done` .

I use this library and i like it and this will be very helpfull.

**Comment by DanielApt** [comment]
We do not offer a percentage value, however we do offer events which should address the scenario of when scrolling reaches the end/bottom of an element.

In the [Events documentation](https://github.com/noraesae/perfect-scrollbar#events) you'll see the `ps-y-reach-end` event described. I think this will address your scenario.
