### ISSUE TITLE
Example of scrolling a DOM element into view?

### ISSUE THREAD

**Issue by slimandslam** [noraesae/perfect-scrollbar#450]
I have a scrolling window that uses the latest version of perfect scrollbar. Is there an example somewhere of how to scroll a div element within that scrolling window (with id="someid") into view?  The usual approaches (scrollintoview, focus, scrolltop, scrollto) don't seem to work for me.

J

**Comment by DanielApt** [comment]
Perfect-scrollbar does not change the way that scrolling works. So getting an element to scroll in to view would work the same way you normally would achieve it. You'd have to simply change the `scrollTop` to the value that matches where your element is.

I've created a quick example with jQuery demonstrating how this could work in practice: 
https://jsfiddle.net/hLr7oa0k/

Please reopen if I've misunderstood the issue, or if you need more help.

**Comment by aproni34f** [comment]
jQuery seems to work, but scrollto not. (It works with default browser scorllbar)

https://jsfiddle.net/mrjLbf2n/1/
