### ISSUE TITLE
Rail container!? Outside main scrollable container.

### ISSUE THREAD

**Issue by WoW-rotfl** [noraesae/perfect-scrollbar#453]
Hi, will be great if you add container rail option( rails creates exacltly inside container which selector we set and outside scrollable container ). What for? I have scrollable grid list with drag&drop sortable and scrollbar rails creates inside list container. Sometimes sortable element occurs after rails as a result we have empty space between elements. Any solutions?

**Comment by DanielApt** [comment]
Could you send me a screenshot of the current situation, and what you are suggesting?

**Comment by WoW-rotfl** [comment]
Okay here it is:

![empty-space edited](https://cloud.githubusercontent.com/assets/6151069/12942457/5fe1179a-cfec-11e5-9cff-c18f7ccfe2f2.jpg)


`<div class="area-folders clearfix ps-container" data-ps-id="773724b2-d148-4fd6-6850-a2c0b997840c">
    <div class="folder">
        <div class="folder__centered">
            <i class="icon icon-folder ac"></i>
        </div>
    </div>
    <div class="folder">
        <div class="folder__centered">
            <i class="icon icon-folder ac"></i>
        </div>
    </div>
    <div class="folder">
        <div class="folder__centered">
            <i class="icon icon-folder ac"></i>
        </div>
    </div>
    <div class="folder">
        <div class="folder__centered">
            <i class="icon icon-folder ac"></i>
        </div>
    </div>
    <div class="folder">
        <div class="folder__centered">
            <i class="icon icon-folder ac"></i>
        </div>
    </div>
    <div class="folder">
        <div class="folder__centered">
            <i class="icon icon-folder ac"></i>
        </div>
    </div>
    <div class="folder">
        <div class="folder__centered">
            <i class="icon icon-folder ac"></i>
        </div>
    </div>
    <div class="folder">
        <div class="folder__centered">
            <i class="icon icon-folder ac"></i>
        </div>
    </div>
    
    
    <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;">
        <div class="ps-scrollbar-x" style="left: 0px; width: 0px;"></div>
    </div>
    <div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;">
        <div class="ps-scrollbar-y" style="top: 0px; height: 0px;"></div>
    </div>
    
    
    <div class="folder" draggable="false">
        <div class="folder__centered">
            <i class="icon icon-folder ac"></i>
        </div>
    </div>
</div>`

it's happens because rails in one container with folders.
i suggest some option like: 

`Ps.initialize(container, {
  wheelSpeed: 2,
  wheelPropagation: true,
  minScrollbarLength: 20,
  // new option
  railContainer: '.selector' 
});`

**Comment by noraesae** [comment]
Moved to #508. Thanks for the suggestion.
