### ISSUE TITLE
Jumpy Scrolling with Images

### ISSUE THREAD

**Issue by bribar** [noraesae/perfect-scrollbar#465]
Scrollbar always seems to work great, but I found this weird issue. When images come into view of the scroller it hesitates for a second then scrolls. Jumpy at times too. Images are coming from aws s3. See here:

https://jsfiddle.net/gbfLazpx/29/

Mac OSX/Latest Chrome

**Comment by noraesae** [comment]
Hello,

I looked into it a little bit and found that it happens with a browser native scrollbar too.

https://jsfiddle.net/gbfLazpx/30/

It happens in WebKit browsers like Chrome and Safari. My guess is that the image size is quite large(5061x3374) and the browser rendering engine just can't handle it smoothly. If it's your case, please consider using smaller images.

It seems like no perfect-scrollbar issue, and I close this now. Please feel free to ask further.

Thanks,

**Comment by DanielApt** [comment]
Just my two cents:

Moving images is actually one of the toughest things for the browser to repaint. 

As suggested, smaller images are a good start. 

What also *might* help is to add `transform: translate3d(0,0,0)` to the image. That CSS will move the image rendering to a separate layer that the GPU will take care of. 

Anyway, to reiterate: this is indeed no perfect scrollbar issue.

**Comment by bribar** [comment]
When I remove perfectScollbar, browser handles this perfectly fine with same image sizes.
