### ISSUE TITLE
when reaching the end of a scrollable area, continue scroll the surrounding element. e.g: window

### ISSUE THREAD

**Issue by loominade** [noraesae/perfect-scrollbar#469]
Using a trackpad try to scroll down this example:
https://jsfiddle.net/gbfLazpx/35/

without releasing the trackpad and re-placeing the cursor outside of the ps-container, it is not possible to reach the bottom of the page.

Any regular scrollable element will do just that.

I included a textarea at the bottom of the fiddle to try.  Since there already is a `ps-x-reach-end` event, it should be possible to replicate this behaviour even without changing anything on the library, right?

**Comment by DanielApt** [comment]
When setting `wheelPropogation` to `true` the behaviour takes place that you expect. https://jsfiddle.net/DanielApt/7vvycnep/1/

**Comment by loominade** [comment]
that is _perfect_.

Thank you

**Comment by DanielApt** [comment]
Haha *perfect* comment right there :wink: !

Feel free to contribute by opening any other issues or by sending a pull request. Thanks!
