### ISSUE TITLE
Unification dist/**/*.min.* files

### ISSUE THREAD

**Issue by vsn4ik** [noraesae/perfect-scrollbar#472]
For minificated JS files foldet in a separate folder. CSS - not.

I think it is not necessary to use an additional folder.

**Comment by noraesae** [comment]
I actually think this is valid point. I wrote edaeccebf264a5eb3317c2a25448ec3ce3082221, but I should be very careful when releasing a new version as it will make some CDNs not to work properly as they refers to the original `min` directory automatically.

Thus I will leave this issue with the TODOs until the next release.

- [ ] cdnjs
- [ ] JSDelivr
