### ISSUE TITLE
Mobile Scroll Smoothness

### ISSUE THREAD

**Issue by leggomuhgreggo** [noraesae/perfect-scrollbar#473]
On mobile, the scroll is not as fluid as native scroll.

[Here's a live view of a CodePen](http://codepen.io/leggomuhgreggo/live/GZpaXO) to demo the issue.  

Sorry if I missed something in existing issues. I just disabled PS when user agent detects mobile or tablet, but I wanted to let y'all know.

Thanks for the cool library!

EDIT: Using android/chrome

**Comment by noraesae** [comment]
First of all, thank you for your praise! I'm happy to hear that PS helps others.

For the issue, simulating scroll virtually is not cheap at all. It is likely to have a performance issue, especially for mobile devices which do not have enough computing power like desktops. However we may see if the issue can be solved, or get better at least. Unfortunately I don't have an android device, so it may take a while. Any help or contribution will be welcomed.

Thanks.

**Comment by yeou** [comment]
Do you have an iOS device? Because the performance on an iPad is not great :(

**Comment by noraesae** [comment]
Even though we address most of performance issues in PS touch scrolling, I think there are still problems in some devices. I suggest using native scroll instead of scroll emulation like PS for performance-sensitive situations like mobile, if possible.
