### ISSUE TITLE
Error	1	Cannot find module '../main' from '***\node_modules'.

### ISSUE THREAD

**Issue by sacredMonster** [noraesae/perfect-scrollbar#478]
Hello,

I am new to everything node.js and could really use some help.
I added the perfect-scrollbar.js to the node_modules folder in my project by manually downloading perfect-scrollbar.js.
I am using it this way in my .js file: 
var Ps = require('perfect-scrollbar'); 
However, I get the following build time error:
_Error	1	Cannot find module '../main' from '***\node_modules'.__

What am I doing wrong?
Thanks..

**Comment by noraesae** [comment]
Hello,

To use with `require`, you should install the plugin with `npm`, which is installed together with `node`. It does not work with distributed scripts. You can install this plugin with `npm` like below:

```
npm install perfect-scrollbar
```

You can also find more details in the following sites:

- https://nodejs.org
- https://www.npmjs.com
- http://browserify.org

Thanks!
