### ISSUE TITLE
Offset from top

### ISSUE THREAD

**Issue by ankurmitujjain** [noraesae/perfect-scrollbar#479]
Hello Team,

I am using perfect-scrollbar from a long time with datatables and floatThead, many a time I see requirement to enable scrolling with fixed headers along with fixed search box and datatables button

Below is example...

![image](https://cloud.githubusercontent.com/assets/1140475/13826454/aad89a36-ebdd-11e5-96c4-912104a27a96.png)

Is there any way I can keep header of datatable fixed along with search and buttons?

**Comment by noraesae** [comment]
I think this is actually not a PS issue, but a general implementation detail. Using fixed header for table can be implemented in several ways, such as using `position: absolute`, `overflow: auto`, etc. You can find the detailed methods with googling.

perfect-scrollbar is just a scrollbar plugin, so it has nothing to do with the table header. If there's any further issue concerning ps or I misunderstood the problem, please feel free to reopen and tell me.

Thanks.
