### ISSUE TITLE
Container is not pannable on touch devices

### ISSUE THREAD

**Issue by titansc** [noraesae/perfect-scrollbar#480]
Tested on Chrome, touch device emulator and the Android device.

Fiddle: https://jsfiddle.net/xv0rrxv3/33/

1. Create a page having other blocks before and after container, so that a page has its own non-perfect scroll
2. Place container in the middle of the page, place content inside, so that perfect scroll is available.
3. Scrolling inside a container works perfectly. But if you swipe inside the container and reach the end, you are not able to scroll the page after that.
4. This results in that having a large item-list container empty, you may not scroll the page by swyping on this container.

Problem: `touch-action: none;` disables any touch actions on the container itself (`swipePropagation` does not affect this).

See [related old Hammer discussion](https://github.com/hammerjs/hammer.js/wiki/How-to-fix-Chrome-35--and-IE10--scrolling-(touch-action)), they came to `touch-action: pan-y;` as a solution.

But simple replacing to `touch-action: pan-y;` results touch move being handled twice: container inner scroll and page scroll are being scrolled simultaneously. Looks like event should be propagated only if it is not handled inside a container. But `swipePropagation` still disables propagation at all, or enforces it.

**Comment by azala** [comment]
I'd second this - touch-action:none disables very popular gestures like pinch/double-tap to zoom.
I'm using touch-action:auto on my local build.

**Comment by illus0r** [comment]
Thanks, @noraesae!
