### ISSUE TITLE
Just a little fix for multiple select

### ISSUE THREAD

**Issue by rockfeeler** [noraesae/perfect-scrollbar#481]
I think, it will be a good idea to add multiple select to the function that prevents Ps from scrolling as you've done for textarea. I fixed it easily added "textarea:hover, select[multiple]:hover" to certain function as the second selector.

**Comment by DanielApt** [comment]
Please send a pull request

**Comment by noraesae** [comment]
I've confirmed the issue and applied the change.

Thanks.
