### ISSUE TITLE
max-height child div of another div and perfect scrollbar

### ISSUE THREAD

**Issue by nitheflin** [noraesae/perfect-scrollbar#482]
Hi, I have for example:

```
<div id='parent' style='max-height:100px'>
<div id='child' style='max-height:80px'>
<table>...</table>
</div>
</div>

```
parent and child gets in js .perfectScrollbar();

problem appear when I get table with many rows, that has 300px

perfect scrollbar scrolls child like it has 300px and hide when scrolls below 80px height

I want that perfect scrollbar scrolls child only in range 0px to 80px but shows all tabel rows.
Is it possible?

**Comment by noraesae** [comment]
Hi, thank you for the report.

Could you please provide a fiddle to reproduce the issue? It really helps people to dig the problem down. Writing a fiddle can easily be started with the following links.

- [perfect-scrollbar fiddle](https://jsfiddle.net/DanielApt/xv0rrxv3/)
- [perfect-scrollbar fiddle with jQuery](https://jsfiddle.net/DanielApt/gbfLazpx/)

Thanks in advance.

**Comment by noraesae** [comment]
Closed for the inactivity. Please feel free to re-open if you have further problem.
