### ISSUE TITLE
how to make a ps-scrollbar-y-Rail in another div?

### ISSUE THREAD

**Issue by drtvader** [noraesae/perfect-scrollbar#488]
I need to scroll was in another div, this can be done, that he continued to work?
` <div class="event-time__block">
    <div class="scroll-time-vertical time-message ps-container ps-theme-default ps-active-x ps-active-y" data-ps-id="422df033-ecde-32d7-d468-60f1c27b1f68">
       <div class="time-message__vertical">
         <div class="time-message__column">1</div>
         <div class="time-message__column">2</div>
         <div class="time-message__column">1</div>
         <div class="time-message__column">1</div>
         <div class="time-message__column">2</div>
         <div class="time-message__column">2</div>
         <div class="time-message__column">1</div>
         <div class="time-message__column">1</div>
       </div>
       <div class="ps-scrollbar-y-rail" style="top: 0px; height: 1080px; right: -7px;">
          <div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 1075px;"></div>
        </div>
    </div>
 </div>`

I apologize that the code does not look so readable, do not know how to do properly. How to make a ps-scrollbar-y-rail in event-time__block?

**Comment by noraesae** [comment]
It is not supported by default now. I've created the issue #508, and let's see how we can handle this.

Thanks for the suggestion.
