### ISSUE TITLE
Scrollbar not visible when resizing the browser. 

### ISSUE THREAD

**Issue by amrigo** [noraesae/perfect-scrollbar#489]
When i resize the browser, the scrollbar is not visible. 

If i refresh the browser, after the resizing, the scrollbar appear.

Is the any listener event i can use to make the scrollbar always visible ?

I do already use this code to make the scrollbar always visible :
.ps-container > .ps-scrollbar-x-rail,
.ps-container > .ps-scrollbar-y-rail {
  opacity: 0.6;
}

**Comment by noraesae** [comment]
It may be because the geometry of the container changes after resizing. Please try adding the following code.

```js
var container = document.getElementById('the-container');
window.addEventListener('resize', function () {
  Ps.update(container);
});

// or with jQuery
$(window).resize(function () {
  $('#the-container').perfectScrollbar('update');
});
```

**Comment by amrigo** [comment]
Hi  @noraesae 

This work´s for me : 

```
var container = document.getElementById('.container');
window.addEventListener('resize', function () {
                    [].forEach.call(document.querySelectorAll('container'), function (el) {
                           Ps.initialize(el);
                    });
}); 
```

I try Ps.update(container); also but did not work
