### ISSUE TITLE
How to disable trackpad scrolling?

### ISSUE THREAD

**Issue by loominade** [noraesae/perfect-scrollbar#490]
How to disable the two-finger-scrolling on OSX trackpads?

![Slide two fingers up or down to scroll.](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/macbookair/trackpad-two_finger_scroll.png)

**Comment by noraesae** [comment]
Is what you would like to do preventing wheel event or one using trackpad?

If it's the former, try setting `handlers` option to `['click-rail', 'drag-scrollbar', 'keyboard', 'touch']`. If it's the latter, it is not supported by default and may be a bit tricky.

**Comment by loominade** [comment]
I already tried that but I can still scroll the ps, using the two-finger-scroll

**Comment by noraesae** [comment]
I'm sorry. The option is not released on npm. Will release now.

**Comment by noraesae** [comment]
I've just released `0.6.11` on both npm and bower. It will resolve the problem. If there is still the problem, please feel free to reopen the issue.

**Comment by loominade** [comment]
Works well. Thank you
