### ISSUE TITLE
not compatible with jQuery scrollintoview()

### ISSUE THREAD

**Issue by loominade** [noraesae/perfect-scrollbar#491]
I'd like to use ps along with [jQuery .scrollintoview() plugin](https://github.com/litera/jquery-scrollintoview) but when ps is applied on an element, `scrollintoview` does not do anything.

Is there a way to make it compatible or emulate the same functionality with ps?

### [Link to Fiddle](https://jsfiddle.net/gaxpv7o6/1/)

**Comment by DanielApt** [comment]
This is a nearly identical question to #487. Please read that one for an explanation.

This is how you can solve it, without using the scrollintoview() plugin: https://jsfiddle.net/wcgmjmqn/2/

**Tip**: To help speed up creating a jsfiddle, you can always fork one mentioned [in our documentation](https://github.com/noraesae/perfect-scrollbar#jsfiddle).
