### ISSUE TITLE
Perfect-scrollbar does not scroll when selecting text outside the viewport

### ISSUE THREAD

**Issue by jmuerle** [noraesae/perfect-scrollbar#492]
Hello,

I'm encountering an issue where selecting text by dragging does not scroll the viewport as it does with the native scrollbars. To reproduce, visit this jsfiddle: https://jsfiddle.net/yfof6mtn/1/.

Select some of the text, and then drag below the viewport container to select text currently out of view. Notice that it doesn't scroll the content. Then, comment out the Ps.initialize() call and do it again. Notice that the content does scroll this time.

Thank you for taking the time to look into this,
James

**Comment by noraesae** [comment]
Actually, this feature is once implemented as [selection](https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/selection.js) for `handlers` option. You can test it out with `{handler: ['click-rail', 'drag-scrollbar', 'keyboard', 'wheel', 'touch', 'selection]}`. It is currently disabled by default as it creates more issues.

Perfect Scrollbar basically simulates scrolling by script and it is sometimes very difficult to implement as the native scrolling works. Any contribution on this will be welcomed, including improving the selection handler or rewriting it completely.

Thanks for the report.

**Comment by noraesae** [comment]
Selection scrolling will be deprecated in v1. Instead, there will be `webkit` method where we can just use the native scrolling with hidden native scrollbars. It's only for webkit browsers, though. For other browsers, we will provide plugin interface to write users' own scroll emulation. Sorry that I cannot help so much.

Thanks again.
