### ISSUE TITLE
ps-scroll-x trigger many time

### ISSUE THREAD

**Issue by FlyMaple** [noraesae/perfect-scrollbar#493]
`
document.addEventListener('ps-scroll-x', function (ev) {
    console.log(ev.srcElement);
})
`
I will scroll vertical bar, the ps-scroll-x event will be trigger many time??

please help

**Comment by DanielApt** [comment]
Hmmm… that's odd, does `ps-scroll-y` trigger as well?

**Comment by noraesae** [comment]
If you need to throttle the event, please consider implementing it in each handler. You can find it with keywords like `throttle` or `debounce` in JavaScript.
