### ISSUE TITLE
how to make overflow-x visible?

### ISSUE THREAD

**Issue by cesiya23** [noraesae/perfect-scrollbar#494]
I tried to change css style of ps-container, but it does not work.
I wonder how to make my container only scrollable in y axis and overflow visible in x axis.
```
.ps-container  {
  overflow: visible/auto !important;
  overflow-y: hidden !important;
  overflow-x: visible !important;
}
```

**Comment by noraesae** [comment]
It is not possible to use `visible` and `hidden` together for `overflow-x` and `overflow-y`. It is not a problem or bug, but it is defined by W3C spec. Please refer to the following links

- [CSS overflow-x: visible; and overflow-y: hidden; causing scrollbar issue](http://stackoverflow.com/questions/6421966/css-overflow-x-visible-and-overflow-y-hidden-causing-scrollbar-issue)
- [W3C Overflow Spec](https://www.w3.org/TR/css3-box/#overflow-x)

**Comment by thesergeev** [comment]
This hack helped me: https://css-tricks.com/popping-hidden-overflow/
