### ISSUE TITLE
How to get a ScrollPosition? and how to scroll to a given position?

### ISSUE THREAD

**Issue by rajagopal14** [noraesae/perfect-scrollbar#497]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by noraesae** [comment]
#### Getting a scroll position:

```js
container.scrollTop // scroll top
container.scrollLeft // scroll left

// or with jquery
$(...).scrollTop();
$(...).scrollLeft();
```

#### Scroll to given position

```js
container.scrollTop = 100; // scroll to 100px from the top
Ps.update(container);

// or with jquery
$(...).scrollTop(100);
$(...).perfectScrollbar('update');
```
