### ISSUE TITLE
Touch bug?

### ISSUE THREAD

**Issue by davilmaster** [noraesae/perfect-scrollbar#498]
Na versão mobile, quando movemos o corpo da página, o que está dentro do perfect-scrollbar
 some, isso é um bug no touch? Meu site tem duas laterais retráteis e quando estão abertas, ao mover o corpo da página para baixo, o conteúdo some. Porém se eu fechar e abrir a parte lateral, volta ao normal. Estou confuso com isso.

**Comment by brendonmm** [comment]
@davilmaster Teria um exemplo disso ou em que navegador(es) acontece, para que possa verificar? 
Ps.: O Jun não fala português. =)

**Comment by davilmaster** [comment]
@brendonmm Olá amigo. Acabei descobrindo um erro, mas não era no scroll e sim no meu código devido a um $resize do jquery. Sempre que eu movimentava a tela ou ativava o recurso de escrita, ele automaticamente chamava o resize e o recurso lateral era oculto. Então o plugin está ótimo. Falha minha mesmo :100:

**Comment by noraesae** [comment]
I'm really sorry that I have no idea about Portugues :sweat:
I actually translated texts with Google Translator and the issue may have been resolved?

I close this issue now. Please feel free to reopen if there are further problems.

Obrigado!
