### ISSUE TITLE
Not working properly with carousel

### ISSUE THREAD

**Issue by BenevidesLecontes** [noraesae/perfect-scrollbar#499]
Hi! I'm trying to make this plugin working with slick carousel, but it don't work as expected, here's my fiddle: http://jsfiddle.net/benevideslecontes/ne688fy4/1/
The expected behavior is scroll all the items  on carousel and scroll on the click button of carousel.

**Comment by davilmaster** [comment]
I am not the creator and use this slide. But it was not done for this purpose you want. Unfortunately. He's just a scrollbar.

**Comment by noraesae** [comment]
Hello,

I've just checked the fiddle and unfortunately slick carousel does not use `scrollLeft` to scroll the content. It uses `translate3d` to virtually move its content. It means, it may be difficult to use both of them together, as they use different ways for scrolling.

Sorry and thanks for your interests on this plugin!
