### ISSUE TITLE
perfect-scrollbar removes "native" easing ?

### ISSUE THREAD

**Issue by phil-lgr** [noraesae/perfect-scrollbar#504]
First of, thanks for your hard work, the scrollbar looks very nice and works perfectly with AngularJS and other libs, so easy to use.

One issue, maybe I am doing something wrong but it seems that perfect-scrollbar removes the "native" easing that Chrome/Edge/FF apply to scrolling area. With the perfect-scrollbar active, the scrolling  "ticks" like in Windows explorer instead of accelerating and decelerating. 

I checked the demo page on Chrome/Edge/FF and it's the same behavior. This is on Windows 10, I don't know if you get that on Mac. 

If you remove perfect-scrollbar in the inspector and just make it `overflow: scroll` 

```
var demo = document.getElementById('Demo'); 
demo.removeAttribute("data-ps-id"); 
demo.className = ''; 
demo.style.overflow = "scroll";
```

You will see what I mean. Reading #378 I though perfect-scrollbar would maintain the native scrolling experience.

**Comment by noraesae** [comment]
No, PS doesn't intentionally remove native easing. But the wheel scrolling is implemented with a custom wheel delta calculation, and it may not work well with some browsers. It is implemented in [mouse-wheel.js](https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/mouse-wheel.js).

I've just checked in Chrome and Firefox in OS X and the scrolling works just fine. It could be a Windows-specific problem, but unfortunately I don't have many Windows environments(only VirtualBox). It is surely possible to test in VirtualBox, but any help from others will be super-welcomed.

Thanks for the report!

**Comment by azharuniverse** [comment]
I am having this issue on chrome. Scrolling using mouse wheel looks very bad. 
Also for some reason I had to add 
```
.ps-scrollbar-y-rail {
    top: 0px !important;
}
```
in my css otherwise on scrolling top value is dynamically changing causing rail container to move down.

**Comment by DanielApt** [comment]
I'm surprised that you needed to add that above line of code.

Does the container have its `position` set to `relative`?

As Javascript is running on each `scroll` event, there will be a performance impact. This impact should be minimal, though.

Could you share an example?

**Comment by noraesae** [comment]
What @azharuniverse pointed out is different from the original issue. Absolute positioned scrolling will be removed in v1, so the issue will be resolved too.

I close the original issue for its inactivity. It can also be resolved in v1. (I feel like I'm spamming v1, sorry about that 😅)
