### ISSUE TITLE
Scrollers out of container

### ISSUE THREAD

**Issue by KrakenTyP-co** [noraesae/perfect-scrollbar#507]
How can I set position of scrollbars out of the container.

I know there is problem do it, bc. scroller container need to be with position relative and overflow hidden.

But pls help me with this situation, bc. i dont want overlaped content by srollers.

Thx.

**Comment by noraesae** [comment]
It is not supported by default now. I've created the issue #508, and let's see how we can handle this.

Thanks for the suggestion.
