### ISSUE TITLE
Scrollbar out of container

### ISSUE THREAD

**Issue by noraesae** [noraesae/perfect-scrollbar#508]
It is not supported yet, but there have been several requests on this feature. I'm not really up for this, as PS is designed to work as the browser native scrollbar does, but not more. However, there are still many people requesting this to be implemented and I would like to discuss if we should and how we can implement this.

Any idea or PR will be welcomed.

**Comment by samherrmann** [comment]
I worked around this issue for now by adding the following CSS:

.ps-container {
    padding-right: 16px; // Or whatever px value you desire
}

I understand that this padding is always there, even if there is no overflow in which case no scrollbar may exist. So maybe the solution is for perfect-scrollbar to add padding to .ps-container when it's visible?

**Comment by noraesae** [comment]
This will be officially supported in v1. It's part of the v1, so please refer to v1 docs.

- [Discussion](https://github.com/noraesae/perfect-scrollbar/issues/553)
- [Design Draft](https://gist.github.com/noraesae/b5202b6131509a46c7e041791036ca86)
- [Dev Branch](https://github.com/noraesae/perfect-scrollbar/tree/next)

Here is also [a quick fiddle](https://jsfiddle.net/pk2f0gsw/2/) for who really want to know how scrollbars out of container work!
