### ISSUE TITLE
example with infinite scrolling

### ISSUE THREAD

**Issue by rbiq** [noraesae/perfect-scrollbar#509]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

Even after the div has finished loading the last paged records I am not able to prevent the scroll bar from scrolling and showing the data in the container. Can you please provide an example?

**Comment by noraesae** [comment]
I don't understand the situation. Can you explain about your issue more specifically?

**Comment by DanielApt** [comment]
I believe @rbiq simply wants an example of us demonstrating an infinite scroll feature.

**Comment by DanielApt** [comment]
Care to confirm @rbiq ?

**Comment by noraesae** [comment]
Closed for its inactivity. Please feel free to re-open if there is any further issue 😄
