### ISSUE TITLE
how to give default height for a scrollbar ?

### ISSUE THREAD

**Issue by rajagopal14** [noraesae/perfect-scrollbar#510]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by rajagopal14** [comment]
I have lot more data in a container If I scroll the scrollbar height is reducing to 1px I need a default height for scrollbar how to implement this??

**Comment by noraesae** [comment]
`minScrollbarLength` will set the minimum length of scrollbar.

**Comment by rajagopal14** [comment]
I have given minScrollbarLength but its not working for me

**Comment by noraesae** [comment]
Will check now for the option. Can you please prepare a simple fiddle if possible?

**Comment by rajagopal14** [comment]
customScrollbar(jQuery(".qboxheight"));
jQuery(".qboxheight").perfectScrollbar({minScrollbarLength:30});

I have give like this while initiating am setting minScrollbarLength

**Comment by rajagopal14** [comment]
here the fiddle you can check here

https://jsfiddle.net/gbfLazpx/143/

**Comment by noraesae** [comment]
Oh, you called `.perfectScrollbar()` twice. Please check here: https://jsfiddle.net/x951d155/

Currently options can be set only once when initializing the plugin.

**Comment by rajagopal14** [comment]
oh k thank you so much
