### ISSUE TITLE
Support scaling scroll rails on hover

### ISSUE THREAD

**Issue by cdriscol** [noraesae/perfect-scrollbar#514]
Facebook, Twitter, and many other cutting edge front-end companies are now implementing scalable scroll bars that grow when you hover/drag them.  I think this would be an excellent addition to the perfect-scrollbar library.

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [x] Provide a page or source code where the issue can be checked

**Comment by DanielApt** [comment]
I can't find the behaviour you're describing on Facebook and Twitter.

Do you mean this?
![scroll](https://cloud.githubusercontent.com/assets/52545/15776580/8e443ffc-2980-11e6-9a4b-6789375e3115.gif)

That is not scripted, but a default OSX scrollbar behaviour.

Is this maybe happening on a different OS?

**Comment by cdriscol** [comment]
Facebook's you can find on the messenger and friends list on the right side widgets.  You're right that Twitter's is a OSX thing.. but the growing bars are nice for smaller widgets much like Facebook's implementation.

http://screencast.com/t/HAZztkxEFp

**Comment by cdriscol** [comment]
LinkedIn also has a similar effect on their "pulse" widget:

http://screencast.com/t/qEqXhcvk
(on windows)

**Comment by DanielApt** [comment]
Thanks, I can reproduce the desired effect on my Mac for the Pulse widget on LinkedIn as well.

I like it, and I think it looks very elegant. Let me just review your code for the PR

PS: Massive thanks for writing the PR

**Comment by DanielApt** [comment]
Just had the chance to look at it, will keep coments on the [PR thread](https://github.com/noraesae/perfect-scrollbar/pull/513)
