### ISSUE TITLE
Show inner hidden menu element above perfect-toolbar div

### ISSUE THREAD

**Issue by amrigo** [noraesae/perfect-scrollbar#515]
Hi 

I can not see an "actions" hidden menu using onClik event into a button.

The menu is not seen entirely, it stays below the perfect-scrollbar div.

How can i see the menu above the perfect-toolbar div ?

I try every possible combination of positioning between three elements:
eg.:
.table-list-div: 	 position: absolute; z-index: 1;
.table-list-results:  position: absolute; z-index: 2;
.dropdown-menu-right: position: relative; z-index: 3; 
and so on...

Steps to reproduce:
1. Set a perfect-scrollbar div (i do apply class=table-list-div)
2. Set a table with 10 query results or more (i do apply class=table-list-results) 
3. Set a hidden menu using bootstrap library dropdown-menu class  (i do apply class=dropdown-menu-right) .

**Comment by noraesae** [comment]
We actually do not use `z-index` at all, so it must show properly. Can you provide a fiddle reproducing the problem? You can start from forking basic fiddles.

- Vanilla JS: https://jsfiddle.net/DanielApt/xv0rrxv3/
- jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/

**Comment by noraesae** [comment]
Closed for its inactivity. Please feel free to re-open.
