### ISSUE TITLE
Y rail position

### ISSUE THREAD

**Issue by danielverejan** [noraesae/perfect-scrollbar#516]
Hi, 

the plugin sets right property of the Y rail equal to the width of container where it is initialized.

ex: container has 1024px; width --> Y rail moves to left with right: 1024px;

I'm initializing it without any parameters nor any changes was made to source code.
Fixed it at the moment with right: 0 !important;

Don't know how to reproduce it, I just opened the project after a few days and it was on the left.

**Comment by noraesae** [comment]
Hmm, I've tested examples and it's working fine without changes in CSS. Is there any CSS or script change you have made? I understand sometimes it's difficult to find out how to reproduce an issue, but it would be really helping us to address the issue. Can you consider creating a fiddle to reproduce the problem? You can start from forking basic fiddles.

- Vanilla JS: https://jsfiddle.net/DanielApt/xv0rrxv3/
- jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/

**Comment by danielverejan** [comment]
It seems to have been a CSS problem, don't know how but I fixed it.
Anyway I think you should improve the CSS it was really hard to add some custom styles for it forcing me to use !important and ">" things so I ended up writing styles from scratch.
But that's a small issue, thanks for the great plugin!

**Comment by DanielApt** [comment]
Sorry to hear you found customising the plugin difficult. We offer the possibility of creating [custom themes](https://github.com/noraesae/perfect-scrollbar#theme). Let me know if you need any help.

**Comment by noraesae** [comment]
I agree that it's somewhat difficult to add custom styles, and that's why I consider it from scratch in v1. I really appreciate your comment.

I close this issue now. Please feel free to ask us if you have further issue. Thanks!
