### ISSUE TITLE
html scroll bar

### ISSUE THREAD

**Issue by ssalcio** [noraesae/perfect-scrollbar#520]
Hi,
I try to use your plugin for html

$('html').perfectScrollbar();

it's show the bar but does not work

![image](https://cloud.githubusercontent.com/assets/5671287/16155431/a9c06974-34af-11e6-9c7b-6c2ab9a8a3b9.png)

**Comment by imarkdesigns** [comment]
Please check and refer to this issue.
https://github.com/noraesae/perfect-scrollbar/issues/72

**Comment by noraesae** [comment]
As already said, `html` or `body` is not a normal container element, so PS may not work properly. Please consider implementing it with a full-fetched `div` wrapping the whole body.
