### ISSUE TITLE
Webpack production run error

### ISSUE THREAD

**Issue by erwinyusrizal** [noraesae/perfect-scrollbar#521]
Hi I have a problem when running perfect-scroll on nodejs, when build for production it's ok but when trying to running it, it returns this error:

```
/home/xxx/public_html/xxxxxx/node_modules/perfect-scrollbar/src/js/lib/helper.js:80
  isWebKit: 'WebkitAppearance' in document.documentElement.style,
                                  ^

ReferenceError: document is not defined
    at Object.<anonymous> (/home/xxx/public_html/xxxxxx/node_modules/perfect-scrollbar/src/js/lib/helper.js:80:35)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)

    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/xxx/public_html/xxxxxx/node_modules/perfect-scrollbar/src/js/plugin/destroy.js:3:9)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

any idea how to fix it?

Cheers,

**Comment by noraesae** [comment]
It's not to run on Node.js. It is to run on browsers.

**Comment by erwinyusrizal** [comment]
@noraesae thanks for your reply,

I'm running it with React, but i'm having problem with that, yeah I realized about that too

thanks,

**Comment by noraesae** [comment]
I now understand. A React component sometimes uses itself as a server-side renderer. PS is not designed to run in a server, so please consider disable PS when used in the server. It can be done by wrapping with a condition to check `document` like below.

```js
if (document) {
  Ps.initialize(element);
}
```

**Comment by 6-162** [comment]
@noraesae using ``` if (document) ``` doesnt solve the problem, Im using server side rendering in a react application and getting the same error,

**Comment by usebaz** [comment]
@noraesae browser code(` isWebKit: 'WebkitAppearance' in document.documentElement.style`, /src/js/lib/helper.js) executed when i requre your lib, and it`s break server side rendering. 
```
const Ps = require('perfect-scrollbar'); // it`s breaking here, on server

app.onBrowserRendering = () => {
  Ps.initialize(element);
}
```

Can you fix this?

**Comment by MaxSvargal** [comment]
+1

**Comment by ethanresnick** [comment]
@noraesae I think this should be reopened. As others have pointed out, it's hard to solve at the webpack layer (though it is possible with enough trickery), so it would save a lot of total effort if the module were aware of the possibility that it's running server side and simply did nothing.

If I created a PR, adding a bunch of `typeof document`/`typeof window` checks, would that be accepted?

**Comment by noraesae** [comment]
@ethanresnick Yes, now SSR is common in the JS community, and we should take care of this. I will absolutely accept the PR.

**Comment by philosophocat** [comment]
What about PR?)

**Comment by noraesae** [comment]
#650 resolves this.
