### ISSUE TITLE
No touchpad scroll in EDGE on NON-touchscreen laptop

### ISSUE THREAD

**Issue by ghost** [noraesae/perfect-scrollbar#529]
Found other submissions on the subject.  Some were merged, some were closed, some were open.  All of the suggestions/solutions were way over my head.  One said to open a new submission, so forgive me if I am not in line with policy.

W10-64, EDGE will not scroll with TOUCHPAD on Toshiba laptop with Synaptics touchpad. NONtouchscreen.  

Another laptop I have .. with same OS but DELL 'pointing device' does work ... but it is a TOUCH SCREEN.

Any help is appreciated in advance.

Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by ihorzenich** [comment]
I tested and found NO PROBLEM in Edge/14.14383 on Windows 10 rs1_release 14383.
Notebook is MacBook Pro 13" Late 2013 under Bootcamp with NO-touchscreen.

**Comment by WacoJohn** [comment]
Thank you for this input.  Test bed is not quite the same.  Glad it is working for you.

**Comment by noraesae** [comment]
Closed for the original author seems deleted. Please feel free to open an issue if there is further problem about this.
