### ISSUE TITLE
Provide additional themes

### ISSUE THREAD

**Issue by noraesae** [noraesae/perfect-scrollbar#530]
As said in #519, I agree that it is a bit hard to achieve 'alwaysVisible' style. I still don't think merging it into JS is a good idea. Instead, I'm thinking about providing themes for it. Specifically, I would add `themes` directory and include the built CSS into distributions. The themes could include not only `always-visible`, but also `square`, `different-color`, etc.

I'd like to discuss if it's good enough, or there is any better way.

**Comment by danielverejan** [comment]
That's funny :D I just declared and .always-visible class for this 
![always-visible](https://cloud.githubusercontent.com/assets/7072732/16832134/8d819992-49b1-11e6-954a-d878ec4442ff.png)
For different-color would be great to make use of currentcolor CSS variable, set it once on .ps-container and use elsewhere with currentcolor.

**Comment by noraesae** [comment]
In v1, default CSS won't be included, as it becomes simple enough for users to build from scratch. Wide range of examples and guide to write CSS will be also provided.

Thanks for your interests and helps!
