### ISSUE TITLE
[feature request] Ability to set scrollbar offset

### ISSUE THREAD

**Issue by wujekbogdan** [noraesae/perfect-scrollbar#531]
Perfect scrollbar is always aligned to the edge of the container. It would be great if there were `offsetX` and `offsetY` attributes.

**Comment by steve-mcqs** [comment]
```js
Ps.initialize(yourElement, {
    scrollYMarginOffset: 100,
    scrollMarginXOffset: 100
});
```

**Comment by wujekbogdan** [comment]
It seems that these options are doing something different. Have a look: http://codepen.io/wube/pen/mEpaRk

There's no offset. Scrollbars are aligned to the edges of the container.

**Comment by noraesae** [comment]
This will be supported by default in v1, as you can actually place scrollbars *anywhere*. Please refer to v1 docs for the detail.

- [Discussion](https://github.com/noraesae/perfect-scrollbar/issues/553)
- [Design Draft](https://gist.github.com/noraesae/b5202b6131509a46c7e041791036ca86)
- [Development Branch](https://github.com/noraesae/perfect-scrollbar/tree/next)

Thanks!

**Comment by yurii-sorokin** [comment]
Do you have any examples how to add such offset in v1?
