### ISSUE TITLE
Function clone in helper.js ( TypeError: obj is undefined )

### ISSUE THREAD

**Issue by fabioconedera** [noraesae/perfect-scrollbar#537]
Hi, I have found this problem on helper.js

var clone = exports.clone = function (obj) {
  if (obj === null) {   <== THIS FAIL IF obj IS UNDEFINED
    return null;
  } else if (obj.constructor === Array) {
    return obj.map(clone);
  } else if (typeof obj === 'object') {
  ...
...

Please fix. Thanks

**Comment by noraesae** [comment]
Thanks for the report!
