### ISSUE TITLE
scrollbar rail no longer supports border radius

### ISSUE THREAD

**Issue by cdriscol** [noraesae/perfect-scrollbar#539]
This commit (https://github.com/noraesae/perfect-scrollbar/commit/26852236cce8336fbdc3e975eff8871d978a2846) removed the ability to set a border radius on the rails.  I was relying on this behavior for a project of mine that had rounded scroll bar rails as well as rounded scroll thumbs.

Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [x] Provide a page or source code where the issue can be checked

**Comment by noraesae** [comment]
Sorry that it changed how SCSS was written. I think customising CSS in the current version of PS is quite difficult. I'm thinking about providing better way in v1.

The change is only a style change, so you can still just use the dist CSS of the previous version while using the new scripts.

Thanks.
