### ISSUE TITLE
Why not add a event when scrolling stops?

### ISSUE THREAD

**Issue by liu-dongyu** [noraesae/perfect-scrollbar#540]
I want to get the events when scrolling stops. Fortunately， i find a solution in this [issue](https://github.com/noraesae/perfect-scrollbar/issues/475)

But i have a question, why not add a event in api such as ps-scroll-x-stop?

**Comment by noraesae** [comment]
I'm glad you found the solution. The reason why it's not included as a feature is, as I mentioned in the previous issue, performance. There is no native way to capture scrolling stops, and we need a timer to keep updated in every scroll event. I thought it's better for users to decide whether they use the event or not. It's just a few lines of code, so users may have no difficulty without any API, I think.

Anyway, I really appreciate your interest 😄
