### ISSUE TITLE
Bottom border on textarea prevents scroll propagation

### ISSUE THREAD

**Issue by BenArunski** [noraesae/perfect-scrollbar#541]
JSFiddle (run on Chrome): https://jsfiddle.net/eL7yku9e/2/

Angular Material calculates textarea height as you type, and the output is similar to what you see on the jsfiddle.  When you hover over the unselected textarea and use the mousewheel to scroll down, the page does not scroll.

The fiddle was made to demonstrate on Chrome, but the same thing happens on IE with Angular Material.

For anyone else seeing this issue, I am currently working around it with scss: `md-input-container textarea.md-input { box-sizing: content-box; }`

I think this could be fixed by replacing both uses of clientHeight with offsetHeight in perfect-scrollbar.js

There is also a related issue (unreported) that I have only seen in IE, where perfect-scrollbar shows scrollbars on non-scrollable sections.  I think that correcting the height/width calculation could fix that, too.

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by noraesae** [comment]
Actually I've made minimal case: https://jsfiddle.net/eL7yku9e/3/
Not sure why this happens. Will investigate.

**Comment by noraesae** [comment]
Found the reason. Thanks for your report!

**Comment by BenArunski** [comment]
Thank you, @noraesae !
