### ISSUE TITLE
Question: check if element is scrolled to the bottom

### ISSUE THREAD

**Issue by keevitaja** [noraesae/perfect-scrollbar#542]
Hello!

What is the best option to check, if element is scrolled down to the bottom?

**Comment by people-06** [comment]
Hello! 

**ps-y-reach-end**
This event fires when scrolling reaches the end of the y-axis (useful for infinite scroll)

**Comment by noraesae** [comment]
Thanks, @people-06!

Please refer to [Events](https://github.com/noraesae/perfect-scrollbar#events) doc if further details are needed.

**Comment by slidenerd** [comment]
Interesting, what if you want to keep a buffer of 10px or so because the exact end being reached, will it fire across all browsers and all devices in a reliable manner? the native scroll event most certainly doesnt
