### ISSUE TITLE
Need a new option to position the scrollbar on the right in rtl mode

### ISSUE THREAD

**Issue by Suzanne3** [noraesae/perfect-scrollbar#543]
I would like to force the scrollbar position on the right in rtl or ltr mode. I didn't found this option.

**Comment by noraesae** [comment]
I'm afraid I'm not aware of how it works on RTL, but can't the scrollbar position be adjusted using CSS?

**Comment by BaDe3** [comment]
.ps-container>.ps-scrollbar-y-rail { right:auto !important;left:0; } , work for me .

**Comment by noraesae** [comment]
Closed for its inactivity. Please feel free to reopen if there is further information.
