### ISSUE TITLE
jquery mobile swipeleft doesn't work on mobile devices

### ISSUE THREAD

**Issue by JustDoItSascha** [noraesae/perfect-scrollbar#544]
When using the perfect scrollbar inside of a swipe menu, the swipeleft event is not triggered when done inside the container. But this occurs just on mobile devices (android). On desktop browsers it works.

`swipePropagation` was true.

**Comment by noraesae** [comment]
Duplicated with #538, `swipePropagation` doesn't seem working properly now. Will continue on the issue.
