### ISSUE TITLE
perfectScrollbar('update') is not smooth 

### ISSUE THREAD

**Issue by Suzanne3** [noraesae/perfect-scrollbar#545]
perfectScrollbar('update') is not smooth. The scrollbar is directly move to the final place without moving on Chrome, Firefox, Edge, IE11. 
Note : I have a similar problème with touch on Window tablet. The scroll is not enough smooth when I touch the screen.

**Comment by Suzanne3** [comment]
I found a solution to my problem. I use :    

 **this.myElementwithScrollBar().animate({ scrollTop: scrollTopValue }, 750);
 this.myElementwithScrollBar().perfectScrollbar('update');**

 I have now a smooth effect. It is working very well.

**Comment by shekhargupta019** [comment]
Hi Suzanne,
I am using
 <PerfectScrollbar onScrollY={this.handleScroll}>
<component1 />
