### ISSUE TITLE
Discrepancy in event target when clicking scrollbar, not rail, in Chrome / Firefox

### ISSUE THREAD

**Issue by banan4** [noraesae/perfect-scrollbar#547]
I am attempting to use PS as a modal scrollbar. It loads fine. However, I am experiencing an issue in Chrome when also binding click outside of the modal to close the modal. The problem is that in Chrome (works as expected in Firefox), when I click the scrollbar (not rail), the wrong event is triggered. 

I've set up a test fiddle here that shows the discrepancy in Firefox / Chrome: https://jsfiddle.net/46an3q23/

thank you very much

**Comment by noraesae** [comment]
Fixed.

**Comment by chrisd08** [comment]
Problems seems to still exist in 1.4.0 with Bootstrap 4.1
