### ISSUE TITLE
In browser scroll if we click cmd+downarrow automatically it will scroll down to the bottom of the element. but not in PS.

### ISSUE THREAD

**Issue by rajagopal14** [noraesae/perfect-scrollbar#549]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by rajagopal14** [comment]
@noraesae Any update regarding this?

**Comment by noraesae** [comment]
Hello, I confirmed this doesn't work properly. Unfortunately, I'm working on the next major release, which includes completely new logic, so I may not work on this. However, you can easily fix this in [keyboard handler](https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/keyboard.js) by yourself. Sorry for your inconvenience!
