### ISSUE TITLE
Can add borders to the rail

### ISSUE THREAD

**Issue by supercain** [noraesae/perfect-scrollbar#550]
Hi,
 
everything is fine so far except for one thing. I am trying to add borders to the rail of the slider, like this:

.ps-container > .ps-scrollbar-y-rail {
  border-radius: 5px;
  display: none;
  margin: 0 2px 0 0;
  opacity: 0;
  position: absolute;
  right: 0;
  transition: background-color 0.2s linear 0s, opacity 0.2s linear 0s;
  width: 3px;
  border: 1px solid #555; <-- this is the problem
}

however, once I have added the border, the rail gets buggy because if you scroll down you can take the slider off limits which is not good.

How can I fix this? I really want the borders but I dont want that weird behavior.

Thank you.

**Comment by supercain** [comment]
Any help please??

**Comment by sheparddw** [comment]
I have this issue as well. I added a box shadow to get around this, but when I add margin to prevent the scrollbar from sitting flush with the edge or add a border, it allows the scrollbar to scroll beyond the bottom of the container. Any ideas?

**Comment by noraesae** [comment]
This is somewhat difficult to fix in the current implementation, but we will be easy to handle in v1 as we can literally put scrollbars anywhere, style them anyhow. Sorry that I cannot help on this, but it may be much better to implement v1 ASAP. Please wait a little. Thanks.

**Comment by sheparddw** [comment]
Thanks for the explanation.
