### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by akankov** [noraesae/perfect-scrollbar#552]
Why don't you create typescript definition for your scrollbar?

Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [x] Provide a page or source code where the issue can be checked

**Comment by noraesae** [comment]
It's a nice idea, but I'm currently planning to change PS API to be simpler and better. This work may come later. But thank you very much for the suggestion 👍

**Comment by harryjoy** [comment]
I have made my own for now, you can use it if you want.

```typescript
interface PerfectScrollbarOptions {
    wheelSpeed?: number;
    wheelPropagation?: boolean;
    swipePropagation?: boolean;
    minScrollbarLength?: number;
    maxScrollbarLength?: number;
    useBothWheelAxes?: boolean;
    useKeyboard?: boolean;
    suppressScrollX?: boolean;
    suppressScrollY?: boolean;
    scrollXMarginOffset?: number;
    scrollYMarginOffset?: number;
}

interface PerfectScrollbar {
    initialize(container: HTMLElement, options?: PerfectScrollbarOptions);
    update(container: HTMLElement);
    destroy(container: HTMLElement);
}

interface JQuery {
    perfectScrollbar(options?: PerfectScrollbarOptions): JQuery;
}

declare var ps: PerfectScrollbar;

declare module "perfect-scrollbar" {
    export = ps;
}
```

**Comment by noraesae** [comment]
Thanks!

**Comment by frederikprijck** [comment]
@noraesae Is it possible the d.ts file isn't part of the node_modules folder when installing perfect-scrollbar ? I've got:
![image](https://cloud.githubusercontent.com/assets/2146903/19997635/3f37b0d6-a268-11e6-90af-d53e9ca06ac2.png)

And I'm using 0.6.13...

**Comment by noraesae** [comment]
@frederikprijck Sorry. I've just published 0.6.14 containing the definition. Please try it out.

**Comment by frederikprijck** [comment]
The file exists in node_modules now, but I get the following error:

>  error TS2656: Exported external package typings file '.../node_modules/perfect-scrollbar/perfect-scrollbar.d.ts' is not a module. Please contact the package author to update the package definition.

**Comment by noraesae** [comment]
Hmm, weird. I'm actually not familiar with recent TS conventions. Isn't it enough to specify `typing` field in `package.json`? Doesn't TS load the type infos with just `import`?

**Comment by frederikprijck** [comment]
TS is supposed to load them that way, but it's not working. 
I'm not saying it's an issue on your end, but I guess so.

I'll try to look into this tonight. Your definition's code works fine if I add them to my custom.d.ts files installed using typings, but it doesn't work when importing it from your node_module.

**Comment by noraesae** [comment]
Thank you very much for sharing the case. I also guess that there may be a way to specify the location of the `.d.ts` file for a module. Please feel free to leave a comment or upload a PR.

**Comment by frederikprijck** [comment]
It does find the d.ts file, but it fails to work. I'll try to reproduce it tonight and see where it gets me. I guess it has to do with it not being an external module
