### ISSUE TITLE
After setting PS If I scroll suddenly am getting like this empty space at the bottom of ps element. why? If I toggle some element after that also am getting empty space while scrolling.

### ISSUE THREAD

**Issue by rajagopal14** [noraesae/perfect-scrollbar#558]
<img width="1055" alt="screen shot 2016-08-25 at 5 37 28 pm" src="https://cloud.githubusercontent.com/assets/13791804/17968538/0026f5a0-6aeb-11e6-9850-68cff0fe793f.png">
Make sure these boxes are checked before submitting your issue -- thank you!

- [ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ ] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

**Comment by rajagopal14** [comment]
@noraesae any update on this?

**Comment by mrhammadasif** [comment]
Here is Quickfix for you

`
.ps-scrollbar-x-rail,
.ps-scrollbar-y-rail{
    display: none !important;
}
`

Add these in your stylesheet

**Comment by rajagopal14** [comment]
HI @noraesae  can you please check this am getting this issue ?

**Comment by noraesae** [comment]
It looks like a styling issue. Please check if any element or style is affecting the white space. It must be easy if any browser inspector is used. If it looks like a PS issue even after checking it, please feel free to reopen with a fiddle or example page reproducing the issue.

**Comment by rajagopal14** [comment]
No its not a styling issue. this issue happen only when I scroll suddenly. after I scrollTop this issue resolved.

**Comment by noraesae** [comment]
Hmm, because PS doesn't affect on the container's DOM structure, there should be a specific element or style causing this issue. What do you mean by 'scroll suddenly'? Could you please provide a minimal example?

**Comment by rajagopal14** [comment]
ok. If I click something, some div is going to toggle before toggle that div if I scroll that element am getting this empty space at the bottom

**Comment by rajagopal14** [comment]
![issue10](https://cloud.githubusercontent.com/assets/13791804/18629672/cf593ce6-7e84-11e6-93f6-ceea26f99358.gif)

refer this attachment. I am clicking that icon, textarea is going toggle, when I scroll suddenly while toggling that textarea scroll is going somewhere at the bottom.

**Comment by rajagopal14** [comment]
do you understand what am trying to convey you?

**Comment by noraesae** [comment]
Thanks for the demo. I now understand the situation, but still cannot come up with a reason. Can you please check what actually occupies the space using the inspector?

**Comment by rajagopal14** [comment]
<img width="665" alt="screen shot 2016-09-19 at 4 37 23 pm" src="https://cloud.githubusercontent.com/assets/13791804/18630025/5b29cc3e-7e87-11e6-9284-8b3a23b8f1c6.png">

No space is occupying, but am getting styles for scrollbar like this, refer the attachment

**Comment by rajagopal14** [comment]
I also dont know why this is happening

**Comment by noraesae** [comment]
Hmm, can you please check if the PS stylesheet is properly loaded? It seems like the scrollbars are not positioned and displayed properly.

**Comment by rajagopal14** [comment]
Yeah it is also fine. stylesheet is loaded perfectly

**Comment by rajagopal14** [comment]
if I call element.perfectScrollbar("update") in the inspector this problem has solved but am getting this issue all the places where I use PS.

**Comment by noraesae** [comment]
Hmm, then it may be because the content or geometry of content is updated dynamically in PS. I still cannot tell without seeing the actual source code, but if `element.perfectScrollbar('update')` resolves the problem, please call it after the any visual update is performed. There will be auto update feature in v1, but now `update` should be called manually.

**Comment by rajagopal14** [comment]
Ok I can call but If I use this PS in more than 200 places means I have to update in 200 places. that'y am asking

**Comment by noraesae** [comment]
First of all, if you should use PS in more than 200 places, please consider not using PS for most of them. Hooking a scroll event is not cheap at all, perf experts usually recommend each page having less than one or two scroll event bounds.

Also, using 200 PS instances doesn't mean you should put 200 `update`s in the code. Please consider separating the PS parts into a separate module.

**Comment by rajagopal14** [comment]
am not using PS in 200 places for a single page. its a module specific only

**Comment by noraesae** [comment]
Then please ignore the first advise. You may consider modularizing the update part into a module, calling `update` in it, as it's how PS is designed to work.

**Comment by rajagopal14** [comment]
but sometime If I call update also issue not fixed

**Comment by rajagopal14** [comment]
would you able found the root cause why this is happening when scrolling ?

**Comment by noraesae** [comment]
If `update` doesn't fix the problem, `update` may be called before the layout is fully loaded.

As you already know, there is no silver bullet to fix every problem. Please consider taking a time to find out the original reason of the problem. It must be possible with a help of the inspector, because what is causing the issue must be some elements or styles(really, that's all in browser rendering). Surely, I can help investigating, but only when I have a right (and preferably minimal) example or concrete guide to reproduce the problem. Without it, I cannot do anything even though it's really a PS bug. It's simply because *I* don't know what's happening when *your* app is scrolling.

**Comment by rajagopal14** [comment]
ok will debug it with inspector. thanks for your info

**Comment by noraesae** [comment]
Sorry that I cannot help so much. If you have any further problem, please feel free to ask me.

**Comment by rajagopal14** [comment]
sure.
