### ISSUE TITLE
Can we have wheelPropagation always = false?

### ISSUE THREAD

**Issue by chiss22** [noraesae/perfect-scrollbar#561]
Could we have an option to have wheelPropagation persist whether scrollbars are enabled or not?

For example, when the content area isn't tall enough to enable scrollbars the user can scroll the parent element even with 
`wheelPropagation : false`.

For a demo, see http://codepen.io/anon/pen/mJaeKR and remove some of the content of the scrollable red area so that it is no longer scrollable. I would like scrolling of the parent element to behave exactly like it did when the red area was tall enough.

Thanks for the awesome work on this awesome plugin!

**Comment by DanielApt** [comment]
Perfect-scrollbar strives to behave like the native scrollbar.

When an element is not scrollable, scroll propagates upwards, as such perfect-scrollbar follows this convention.

Also, in your scenario perfect-scrollbar is not the cause nor the solution. When an element is non-scrollable, perfect-scrollbar does not receive `scroll` event. What you are seeing is your browser's default behaviour.

**Comment by chiss22** [comment]
@DanielApt I understand that this is native browser behaviour, I was actually just wondering if we could have it as an _option_. wheelPropogation = false is _not_ default browser behaviour, so with that logic, it would also be nice to offer a sort of "alwaysOnWheelProgogation".

Thanks for the quick reply!

**Comment by rdkmaster** [comment]
I am having the same problem, I hope the parent element can be scolled if there is no need to scroll in the child element, can you please fix this issue?

![aa](https://user-images.githubusercontent.com/16191626/31811690-063cc21c-b5b3-11e7-80fb-a473b479e5d8.gif)
