### ISSUE TITLE
Q: Help needed! How can I programmatically change scroll position?

### ISSUE THREAD

**Issue by AndrewEastwood** [noraesae/perfect-scrollbar#565]
Make sure these boxes are checked before submitting your issue -- thank you!

- [+ ] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ +] Search if there's already one reported in Issues
- [ -] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ -] Provide a page or source code where the issue can be checked

**Comment by DanielApt** [comment]
You can change the scroll position just as you would normally. By changing `scrollTop` or `scrollLeft` you can change the position.

[Here's](https://jsfiddle.net/zg0ujwq9/1/) an example
