### ISSUE TITLE
perfect-scrollbar is not hiding the native scroll when "overflow: hidde" style is applied on the container

### ISSUE THREAD

**Issue by aviklai** [noraesae/perfect-scrollbar#566]

**Comment by DanielApt** [comment]
Could you fork one of [these JSFiddles](https://github.com/noraesae/perfect-scrollbar#jsfiddle) and demonstrate the issue?

**Comment by noraesae** [comment]
This may be the CSS issue, as hiding the native scrollbar for `overflow: hidden` is done by the browser, not PS. Please check if the style is applied well with DevTools.

I close this by inactivity, but if you have further question, please feel free to ask.
