### ISSUE TITLE
Double Vertical Scrollbars showing after Theme is changed

### ISSUE THREAD

**Issue by gregoryagu** [noraesae/perfect-scrollbar#567]
I am using perfect-scrollbar, and it shows up perfectly.

Until I change the theme at runtime.  It then shows double vertical scrollbars.  In other words, the native scrollbar is no longer hidden.

It is part of an app, and I you can see it [here](http://greggum.com/#/entity-shell/entities/2)

When you first open the page, you can scroll up and down and it all looks perfect.  Then click on the "Choose Theme" tab and choose a theme.  It will change the theme.  Then click the back button.  You will now see the double vertical bars.  

If you change the theme, and then go back to "Default" theme, it will still show the double vertical bars. But it is back to the same exact theme, so it should look OK.

How do I resolve this?

I have tried to re-initialize the scrollbar, but it looks the same as using update().

**Comment by noraesae** [comment]
I've check the page and it may have been updated? It seems not using PS for the time being.

Unfortunately, there is currently no way to dynamically change themes. The only way is to destroy and the initialize again. I've added an example `examples/custom-theme.html`, so please refer to it.

Thanks.

**Comment by gregoryagu** [comment]
Ok, thank you.
