### ISSUE TITLE
Scrolling when selecting with keyboard shortcuts

### ISSUE THREAD

**Issue by DerTieran** [noraesae/perfect-scrollbar#570]
Make sure these boxes are checked before submitting your issue -- thank you!

- [x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [x] Search if there's already one reported in Issues
- [x] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [x] Provide a page or source code where the issue can be checked

When selecting a text with a keyboard shortcut (e.g. CTRL + A) you can scroll by moving your mouse.

This is because this triggers the [selectionchange event](https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/selection.js#L44-L51) but the [mouseup event](https://github.com/noraesae/perfect-scrollbar/blob/master/src/js/plugin/handler/selection.js#L52-L57) is never triggered to set `isSelected` to false again.

[Example](https://jsfiddle.net/w12y8r77/)
*Use the shortcut for selecting all text (CMD/CTRL + A) and move your mouse down*

This could be solved by also listening on a `keyup` event
```
i.event.bind(window, 'keyup', function () {
  if (isSelected) {
    isSelected = false;
    stopScrolling();
  }
});
```

**Comment by noraesae** [comment]
I've fixed this with your change. However, I don't recommend using the selection handler, it can possibly cause further problem. I plan to abandon it on v1.

Anyway, thank you very much for your help!
