### ISSUE TITLE
when child div scroll end its must be scroll parent's

### ISSUE THREAD

**Issue by ebatgerel** [noraesae/perfect-scrollbar#572]
how to know when i scrolling child div when it reach end of bottom it should be scroll parent's scroll like default browsers

**Comment by harabara** [comment]
I will join this idea. I have an issue with this on mobile. I have a scrollable div which occupies most of the screen, once scrolled to the bottom, doesn't allow page to be scrolled.

**Comment by harabara** [comment]
I realized that this is what swipePropagation is for. But unfortunately it's not working. Even the demo is not working on my android phone. As I understand it should scroll the page once the image can't scroll anymore in that direction? Well, it doesn't.

**Comment by noraesae** [comment]
Yes, it's what `swipePropagation` is for. This seems like a bug. Duplicated with #538, so will continue there.
