### ISSUE TITLE
jquery module name colllision

### ISSUE THREAD

**Issue by literallylara** [noraesae/perfect-scrollbar#573]
I'm not sure if this is a general problem or specific to Webpack, but when trying to require `perfect-scrollbar/jquery`, `jQuery` inside `mountJQuery` will be an empty object because the file itself is called `jquery.js`, which seems to collide with the module resolution. A solution would be to rename `./jquery.js` and  `./src/adaptor/jquery.js` to `jquery-plugin.js`.

Took me hours to figure this out. :|

**Comment by noraesae** [comment]
Hmm, a variable name in a CommonJS module shouldn't have anything to do with a filename. If it does, it's probably a config issue. Can you provide more detail?

**Comment by noraesae** [comment]
Closed for the inactivity. Please feel free to reopen with more detail.
