### ISSUE TITLE
How to use it with Angular 2 and Angular CLI

### ISSUE THREAD

**Issue by praveenpuglia** [noraesae/perfect-scrollbar#574]
Make sure these boxes are checked before submitting your issue -- thank you!

- [ x] Check [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ)
- [ x] Search if there's already one reported in Issues
- [ ] Prepare a JSFiddle reproducing the issue
  - Perfect Scrollbar JSFiddle: https://jsfiddle.net/DanielApt/xv0rrxv3/
  - With jQuery: https://jsfiddle.net/DanielApt/gbfLazpx/
- [ ] Provide a page or source code where the issue can be checked

Well I left those boxes unchecked because they don't look like they apply here.

Also, I am not sure if the issue should be created here or on angular side but it looks like this to be a better place.

I want to use perfect scrollbar with Angular 2 - Final version and I am using Angular CLI. However, I am clueless about how to import it into a component.

Currently I am doing this.

```
import * as Ps from 'perfect-scrollbar';
```

Although it does seem to import stuff and I can use `Ps.initialize()` and similar methods, the compiler still throws an error saying it can't find the module `perfect-scrollbar`. 

How do I solve this issue?

**Comment by noraesae** [comment]
Did you installed perfect-scrollbar with npm? I'm not sure about Angular CLI, but if it's using Browserify or Webpack, it should find modules installed with npm. Please check if perfect-scrollbar is installed in `node_modules`.

**Comment by praveenpuglia** [comment]
It's installed and available in node_modules. 

Angular CLI uses webpack. Even on their readme they specify that it should be as simple as installing any package with npm. https://github.com/angular/angular-cli#3rd-party-library-installation

Should I be raising a bug there?

**Comment by noraesae** [comment]
Did you add the `declare module 'perfect-scrollbar';` line?

**Comment by praveenpuglia** [comment]
Wow! so all I did is to add `declare module 'perfect-scrollbar';` in typings.d.ts. Everything works smooth now. But I now have to know why this works. Thanks. Closing this.

**Comment by noraesae** [comment]
Good to hear it worked. 👍

**Comment by bborad** [comment]
Hi 
I am trying to use it with Angular 2 CLI but getting following error message. 
'Calling function 'PerfectScrollbarModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function'

Try adding `declare module 'perfect-scrollbar';` in typings.ts but didn't help.

**Comment by praveenpuglia** [comment]
Did you also do this in your component?
```js
import * as Ps from 'perfect-scrollbar';
```

**Comment by bborad** [comment]
its showing error on "PerfectScrollbarModule.forRoot(PERFECT_SCROLLBAR_CONFIG)" in app.module. CLI doesn't seem to like calling forRoot(). 

Any workaround for this?

**Comment by bborad** [comment]
switch to ngx-perfect-scrollbar
