### ISSUE TITLE
white-space: nowrap, custom scrollbar length and click bug

### ISSUE THREAD

**Issue by anotherssa** [noraesae/perfect-scrollbar#576]
Clicking on any place of scroll rail will always place scrollbar at the end.

[Fiddle reproducing the issue](https://jsfiddle.net/v803xtsn/8/)

**Comment by noraesae** [comment]
It's actually not a bug. Clicking a rail will scroll *a page*, like how browser native scroll works.

https://jsfiddle.net/v803xtsn/11/
