### ISSUE TITLE
Ignoring element height

### ISSUE THREAD

**Issue by Iworb** [noraesae/perfect-scrollbar#579]
Elemet height was calculated and set via JS (I've tried to 'update' scrollbar after that too). There's one more block above and below target and scrollbar just ignoring them, fits to height of window instead height of target.
Here's my target block:
![01](https://cloud.githubusercontent.com/assets/6623262/19996504/0f3e0f0c-a271-11e6-8a65-e7e48eeafa05.png)
Here's how scrollbar looks like (same when scrolled bottom):
![02](https://cloud.githubusercontent.com/assets/6623262/19996505/0f3e4f12-a271-11e6-9159-bc898a6899c2.png)
Problem appears in each browser. Everything else is ok.

**Comment by noraesae** [comment]
It seems to me that the problem is not about height, but the top. Please check if your container is positioned, for example with `position: relative`?

**Comment by Iworb** [comment]
Thanks @noraesae, now everything is ok.

**Comment by noraesae** [comment]
Great to hear it worked!
