### ISSUE TITLE
perfect-scrollbar has no default export

### ISSUE THREAD

**Issue by axcl** [noraesae/perfect-scrollbar#582]
I am creating a directive of perfect scrollbar in my angular 2 project, but issue is that when i imported Ps from 'perfect-scrollbar' it give me error that it does not have default export options.

**Comment by noraesae** [comment]
Do you mean 'default export' of ES6 modules? PS doesn't use ES6 module on purpose, so please use CommonJS compatible module system. I'm not sure how TypeScript module system works(as you said it's Angular2, I guess it's TypeScript) but it should be compatible with CommonJS somehow.

**Comment by isairz** [comment]
try `import * as Ps from 'perfect-scrollbar'`
