### ISSUE TITLE
the latest d.ts

### ISSUE THREAD

**Issue by wuzhouyang** [noraesae/perfect-scrollbar#585]
i saw the d.ts in your lastest commit have the `void `
![image](https://cloud.githubusercontent.com/assets/12148043/20417886/9c8bf60e-ad83-11e6-8f84-995a2355ea98.png)
when i install the perfect-scrollbar i find the d.ts but it don't have the ` void`
![image](https://cloud.githubusercontent.com/assets/12148043/20417922/e049fdaa-ad83-11e6-97ce-ba91d868a193.png)
why?

**Comment by noraesae** [comment]
Because it's not released into npm as a new version. Will do in a while.

**Comment by wuzhouyang** [comment]
ok， thanks！
