### ISSUE TITLE
perfect-scrollbar in bootstrap dropdown has a problem

### ISSUE THREAD

**Issue by zwq8299174** [noraesae/perfect-scrollbar#586]
i`m a chinese, my English is not good enough, so sorry.

this is my code:
`$(document).on('shown.bs.dropdown','.dropdown',function(){
			var $list = $(this).find('ul').parent('div');
			var $bar = $list.find('.ps-scrollbar-y');
			var listHiehgt = $list.find('ul').height();	
			if($list.find('li').length==0) return;
			if($list.find('.ps-scrollbar-y-rail').length>0){
				$list.perfectScrollbar('update');
			}else{
				console.log($list.find('ul').height());
				console.log($list.height())
				$list.perfectScrollbar({
	        		suppressScrollX:true
	        	});
	        	if($bar.height()==0&&listHiehgt>205){
					$bar.height((205/listHiehgt)*205);
					$list.addClass('ps-active-y');
				}
			};
		});`
dropdown-menu max-height is 205px,   in chrome click the ‘ps-active-y’, dropdown-menu will hide, in firefox it will not. but it should not hide.  I don't know it is a bug or something wrong.

**Comment by noraesae** [comment]
1. The scrollbar height is not to be set by `$bar.height()`. Please use `minScrollbarLength` and `maxScrollbarLength` options.
2. The `ps-active-y` class is not to be added manually.
3. About the problem, it's difficult just by this snippet of code. Can you provide more details? An example page or jsfiddle will be perfect.

**Comment by noraesae** [comment]
Closed for its inactivity. Please feel free to reopen if there is further information.
