### ISSUE TITLE
Chrome horizontal scroll with shift key not working?

### ISSUE THREAD

**Issue by danielverejan** [noraesae/perfect-scrollbar#589]
http://noraesae.github.io/perfect-scrollbar/ 
Tried the demo and in chrome and opera I can't scroll horizontally using shift key, it works in Firefox and Edge.

Using windows 10.
Chrome version: 54

**Comment by noraesae** [comment]
It works with no problem in macOS Chrome. Unfortunately I do not have a Window machine. Can anybody confirm the problem?

**Comment by danielverejan** [comment]
Probably was a Chrome issue, it works now.

**Comment by noraesae** [comment]
Thanks for feedback. I close this.
