### ISSUE TITLE
Show scrollbar on scroll (like OSX) and hide after stop (1 sec debounce)

### ISSUE THREAD

**Issue by happierall** [noraesae/perfect-scrollbar#590]

**Comment by noraesae** [comment]
Duplicated with #596. The following comment is copied from it.

> This can be only done by JS, and even can be done not in perfect-scrollbar itself. You can just check if scrolling is idle for a while and then hide scrollbars with CSS.
>
> However, checking if something is idle in JS is not cheap. We eventually need to use timers, which I do not like to include in perfect-scrollbar by default.
>
> I am sorry I cannot accept this feature request. You can surely implement one outside perfect-scrollbar as mentioned above, or fork the project and create your own version.
