### ISSUE TITLE
scrolling regular dropdown not working inside perfect scrollbar

### ISSUE THREAD

**Issue by shooby83** [noraesae/perfect-scrollbar#592]
There already was an issue with this topic, but it's closed (https://github.com/noraesae/perfect-scrollbar/issues/272)

I got the same issue: mouse scrolling on the regular dropdown insdie psb is not possible 

```
<div perfect-scrollbar
       wheel-propagation="false"
       swipe-propagation="false"
       suppress-scroll-x="true"
       style="height:500px;overflow-y: hidden">
    <div style="height: 600px; background: red;">
      <div style="height: 200px; width:200px;border: 1px solid black; overflow-y: scroll">
        <div style="height:300px;width: 100px; border: 1px solid yellow">asdljk</div>
      </div>
    </div>
  </div>
```

Appears in current IE, FF and Chrome

Thanks for your help!

**Comment by hoisingtonp** [comment]
I'm also seeing this behavior when trying to scroll a normal "select" element when the parent container (which is using perfect-scrollbar) is "in overflow". The parent container scrolls fine, but the select element does nothing when you try to scroll with the mouse wheel.

**Comment by noraesae** [comment]
Duplicated #571

**Comment by noraesae** [comment]
Moved to #571
