### ISSUE TITLE
Bug in Chrome 55: content jumps back a bit after scrolling with touch gesture

### ISSUE THREAD

**Issue by RavWar** [noraesae/perfect-scrollbar#594]
I have a Samsung Galaxy S7 Edge and recently noticed a bug there: when i scroll a menu down and after the scroll is done, content scrolls back a bit.
I've looked around the code, did some debugging and found that this is caused by easing functionality. Basically, it should continue scrolling, but in my case it did so in the opposite direction. After some further investigation it turned out to be caused by new Pointer Events addition to Chrome 55:
https://www.chromestatus.com/feature/4504699138998272
http://caniuse.com/#feat=pointer

Now touchMove event gets triggered twice and pageX, pageY values are different in each event case. I'm not sure why, but in the Pointer event they are rounded. Here is the result of scrolling straight down:
![rsz_screenshot_from_2016-12-19_15-56-27](https://cloud.githubusercontent.com/assets/675182/21313614/ef53e8ea-c603-11e6-9aa2-f0abb9e36970.png)
DifferenceY should always be negative, but because of rounding and other logic it becomes positive after Pointer event. And because it's triggered last, the easing function thinks we are scrolling up and eases up, when in fact it should ease further down.

**Comment by noraesae** [comment]
PR merged
