### ISSUE TITLE
Feature Request: Add option to hide scrollbar unless it's scrolling.

### ISSUE THREAD

**Issue by madprops** [noraesae/perfect-scrollbar#596]
It would be nice if there's an option to allow the scrollbar to hide after it hasn't been scrolled in a while and make it appear when scrolled. It's nice if you don't want the scrollbar to be visible all the time.

**Comment by noraesae** [comment]
This can be only done by JS, and even can be done not in perfect-scrollbar itself. You can just check if scrolling is idle for a while and then hide scrollbars with CSS.

However, checking if something is idle in JS is not cheap. We eventually need to use timers, which I do not like to include in perfect-scrollbar by default.

I am sorry I cannot accept this feature request. You can surely implement one outside perfect-scrollbar as mentioned above, or fork the project and create your own version.

Thanks!
