### ISSUE TITLE
Issue with scrolling on OS X machines running on VMware VMs.

### ISSUE THREAD

**Issue by bogushvitaly** [noraesae/perfect-scrollbar#597]
On OS X machines running on VMware in Chrome browser observed following issue:
On areas handled by perfect-scrollbar content is scrolled automatically following mouse cursor without using mouse wheel or moving a slider on scrollbar.

The issue is reproducible on VMs only (VMware Fusion):
1) VM - OS X 10.9 Mavericks. Host - Windows 10 or OS X
2) VM - OS X 10.11 El Capitan. Host - Windows 10 or OS X
Not reproducible on hosts.

Reproducible on pages:
- http://noraesae.github.io/perfect-scrollbar/
- http://fuse-angular-material.withinpixels.com/dashboard-project

**Comment by noraesae** [comment]
It may be a bug by how VMware emulates trackpad events of macOS. I assume that it is out of scope to look into VM emulation. Unfortunately I neither have a machine to test it. However I will surely accept any reasonable PR.
