### ISSUE TITLE
adopting bem naming convention

### ISSUE THREAD

**Issue by loominade** [noraesae/perfect-scrollbar#600]
What do you think about adopting the [BEM naming convention](http://getbem.com/naming/)

It was already suggested in https://github.com/noraesae/perfect-scrollbar/issues/553#issuecomment-255194661.

The difference in the Dom should be a minor one:

```diff
- <div class="ps-container ps-theme-default ps-active-x ps-active-y">
+ <div class="ps ps--theme-default ps--active-x ps--active-y">
-   <div class="ps-scrollbar-x-rail">
+   <div class="ps__scrollbar-x-rail">
-     <div class="ps-scrollbar-x"></div>
+     <div class="ps__scrollbar-x"></div>
    </div>
-   <div class="ps-scrollbar-y-rail">
+   <div class="ps__scrollbar-y-rail">
-     <div class="ps-scrollbar-y">
+     <div class="ps__scrollbar-y">
    </div>
  </div>
```

## Block

In BEM methodology this would define the perfect scrollbar as a _block_ with the namespace `ps`.

## Elements

It has the following _elements_:

Element                | Description
------------------|-----------------------------------
`scrollbar-x-rail` | the rail on which X indicator is moving
`scrollbar-x`       | the indicator for the X coordinate of the scroll position
`scrollbar-y-rail` | the rail on which Y indicator is moving
`scrollbar-y`        | the indicator for the Y coordinate of the scroll position

All must be prefixed with the namespace `ps__`.

## Modifiers

The following _modifiers_ are possible.

Modifier                | Meaning
------------------|-----------------------------------
`theme-*`            | The theme of this particular instance of the the scrollbar. May be used for additional styling. The `*` may be replaced with any lowercase alphanumeric string that may also include single dashes (`-`)
`active-x`            | Indicates this scrollbar may be scrolled along the X axis
`active-y`            | Indicates this scrollbar may be scrolled along the Y axis
`x`                       | Indicates that `scrollbar-x` is currently dragged
`y`                       | Indicates that `scrollbar-y` is currently dragged

All must be prefixed with the namespace `ps--`.

**Comment by noraesae** [comment]
Sounds good. I personally do not have any experience with BEM. Could you make a PR?

**Comment by loominade** [comment]
> I personally do not have any experience with BEM.

I am myself not very experienced with it. It would be nice if someone from [github.com/bem](https://github.com/bem) could review it.

**Comment by tadatuta** [comment]
it looks quite fine but take a look at concept of key-value modifiers for `theme`: https://en.bem.info/methodology/naming-convention/#modifier-name (please note that on bem.info different naming scheme is used by default but that does not matter).

**Comment by loominade** [comment]
Interesting. I was only familiar with the [`two dashes style`](https://en.bem.info/methodology/naming-convention/#two-dashes-style)

@tadatuta which style would you recommend to use and why? why is there even a choice between the two styles?

**Comment by tadatuta** [comment]
@loominade it's covered in https://en.bem.info/methodology/naming-convention/#which-style-to-choose
I prefer original style used on bem.info but the only real advantage is that `<` followed with two dashed means comments in XML so underscore is a bit more secure. All the rest is just a matter of taste.

**Comment by loominade** [comment]
So I guess it is up to the maintainer @noraesae which style [to pick](https://en.bem.info/methodology/naming-convention/#alternative-naming-schemes) for modifiers.

The two dashes style is closest to the current implementation.

**Comment by shchukin** [comment]
These code styles options are not equal. In original BEM notation with dashes we have two kind of modifiers. You can call them full and short (not sure if there is a term for this). For example:

1) For full it is
**.block-name_property_value**

.button_palette_danger
.button_palette_success
.button_palette_warning
.button_size_larger
.button_size_largest 
.button_size_smaller
.button_size_smallest
.button_shape_square
.button_shape_circle


2) Short one is for boolean case:
**.block-name_value**
.button_disabled
.button_squared

And second notation is by Nicolas Gallagher (if I remember correctly). In his notation only boolean case exist:

.button--danger
.button--success
.button--warning
.button--larger
.button--largest 
.button--smaller
.button--smallest
.button--shape
.button--circle
.button--disabled
.button--squared

I personally like the original one because that kind of grouping by property more meaningful. Whatever you guys choose please follow it and don't make your own notation :)

**Comment by loominade** [comment]
I propose to change the theme class like this:

```diff
- <div class="ps-container ps-theme-default ps-active-x ps-active-y">
+ <div class="ps ps_theme_default ps--active-x ps--active-y">
```

what do you think? @shchukin, @tadatuta

**Comment by tadatuta** [comment]
@loominade such mix of different delimiters looks a bit strange for me.
Let's consider such variants:
```diff
- <div class="ps-container ps-theme-default ps-active-x ps-active-y">
+ <div class="ps ps_theme_default ps_active-x ps_active-y">
```
or
```diff
- <div class="ps-container ps-theme-default ps-active-x ps-active-y">
+ <div class="ps ps--theme_default ps--active-x ps--active-y">
```

**Comment by loominade** [comment]
thank you @tadatuta 

I propose second variant. Will provide a PR later

**Comment by noraesae** [comment]
I've just merged the PR. Great work! 👍

This is a breaking change, and may take some time to be actually released with a new version. Please wait a little. 😄
