### ISSUE TITLE
Helper.js - clone() isArray edge case

### ISSUE THREAD

**Issue by hgascoigne** [noraesae/perfect-scrollbar#601]
I'm using perfect-scrollbar in a project that works as an overlay on users' existing websites. Some of our users use Prototype JS which overrides the constructor for arrays. In `helper.js`, `clone()` does its array checking using `obj.constructor === Array` which in the case of Prototype will fail. However, using `Array.isArray(obj)` does work. `isArray` is supported back to IE9 according to MDN, but I'm not sure if there are other side effects.

This is a small edge case for a handful of our users, but it would save me a bit of trouble. I'd be happy to make a PR. Thanks!

**Comment by noraesae** [comment]
Sounds good. Would you make a PR?
