### ISSUE TITLE
Feature Request: Snap functionality

### ISSUE THREAD

**Issue by faboudib** [noraesae/perfect-scrollbar#606]
First thanks for sharing your work. Your library seems to be very well developed. I have checked several other Javascript scrollbar libraries. Some of these offer snap functionality either through defining a static snap height/width or by defining the snap element selector. Would be interested in hearing your thoughts on adding such a feature.

**Comment by noraesae** [comment]
Thanks for your opinion. It sounds interesting, but I am afraid I would not add extra functionality other than ones native browsers already support. The current p-s is already quite tricky and buggy, so adding more is not an option, as I think.

Thanks again.
