### ISSUE TITLE
Entire Horizontal Scrollbar is moving while scrolling

### ISSUE THREAD

**Issue by gitsnow** [noraesae/perfect-scrollbar#610]
Not sure if I'm using the plugin correctly but I have a table that has removable columns.  When the table is wider than the container the horizontal perfect scrollbar kicks in.  My problem is that when I scroll right, the entire rail moves along with it instead of just the slider.  Am I missing something simple here?

**Comment by Schnellesadlerauge** [comment]
Use 'position: relative' on the .ps-container

**Comment by gitsnow** [comment]
Thanks, that fixed it but opened a whole new can of worms with the buttons that are auto-gen'd by the Datatable plugin.  I'll have to figure out what to do with them.  Thanks again.
