### ISSUE TITLE
Disable diagonal scrolling request

### ISSUE THREAD

**Issue by oleghind** [noraesae/perfect-scrollbar#611]
When you scroll using native scrollbars with apple's magic mouse you can scroll only in one direction, but perfect-scrollbar allows diagonal scrolling which makes it very difficult to scroll precisely, would be nice to have an option to disable diagonal scrolling

**Comment by noraesae** [comment]
Disabling axis per container is possible via `suppressScrollX` and `suppressScrollY`. Disabling axis per scroll is not possible unfortunately, and quite difficult to handle. Sorry for the inconvenience.
