### ISSUE TITLE
perfect-scrollbar doesn't support jQuery Anymore?!

### ISSUE THREAD

**Issue by dotku** [noraesae/perfect-scrollbar#620]
http://codepen.io/dotku/pen/KaYpjx?editors=0110

when I use jQuery version, ti throw an error says:
Uncaught TypeError: $(...).perfectScrollbar is not a function

**Comment by adfie** [comment]
i got same error...

**Comment by adfie** [comment]
@dotku have u got solution?

**Comment by jfranklin9000** [comment]
If you see this in your javascript console:

`GET 
http://XXX.xxx/js/perfect-scrollbar-0.6.16/js/perfect-scrollbar.jquery.min.js [HTTP/1.1 403 Forbidden 12ms]`

`TypeError: $(...).perfectScrollbar is not a function`

then change the file permissions of the perfect-scrollbar directory from (say) `700` to `755`.

**Comment by SimonFricker** [comment]
I get the same error.

**Comment by bashenandi** [comment]
I get the same error, try use 'perfect-scrollbar.jquery.min.js' file. it`s solved.

**Comment by w9914420** [comment]
I also confirm that I get the same error as @dotku

**Comment by arifhussain353** [comment]
still same error

**Comment by noraesae** [comment]
Please use `perfect-scrollbar.jquery.min.js` instead of `perfect-scrollbar.min.js`.

**Comment by reeslo** [comment]
Can you provide this file into the npm package ?

**Comment by utatti** [comment]
@reeslo jQuery support is dropped from v1.0.
