### ISSUE TITLE
Not scrolling when on hover an iframe

### ISSUE THREAD

**Issue by Simoneth** [noraesae/perfect-scrollbar#625]
Hi,
I love to use this amazing plugin hoever after lot of tries I can't find a solution. for this particular problem..In this example why the Perfect Scrollbar is not working?

http://stackoverflow.com/questions/42305137/how-to-prevent-stop-scrolling-hovering-an-iframe-perfect-scrollbar

Thanks

**Comment by drhouse7** [comment]
I've started a bounty for it...none knows a good reason for this issue. Could anyone here please help me?
Thanks

**Comment by minhcasi** [comment]
I had the same problem, please help.

**Comment by darkterra** [comment]
+1

**Comment by noraesae** [comment]
It's because the scroll event is consumed in the iframe. Please refer to the iframe example.

https://github.com/noraesae/perfect-scrollbar/blob/master/examples/iframe.html

**Comment by monstrfolk** [comment]
@utatti, 404 when trying to view example. Does perfect-srollbar work correctly with iframes? It works on small screen devices.
