### ISSUE TITLE
Angular2: Config option to make the scrollbar always visible

### ISSUE THREAD

**Issue by kilgarenone** [noraesae/perfect-scrollbar#626]
I'm using `angular2-perfect-scrollbar@2.0.5`.

Is there an option to make the scrollbar always visible?

**Comment by paulocheque** [comment]
This can be useful: https://github.com/noraesae/perfect-scrollbar/wiki/FAQ#how-can-i-make-the-scrollbars-always-visible

**Comment by kotmatpockuh** [comment]
@noraesae 
how can i update Ps in angular 2?

**Comment by silentHoo** [comment]
If you're using 0.7.0 you can simply use:

````
.ps > .ps__scrollbar-x-rail,
.ps > .ps__scrollbar-y-rail {
  opacity: 0.6;
}
````

**Comment by noraesae** [comment]
`angular2-perfect-scrollbar` is 3rd-party plugin, and I'm afraid I'm not familiar with Angular. Please refer to the doc and issues of `angular2-perfect-scrollbar`.
