### ISSUE TITLE
Scrollbar z-index on bottom of newly created content

### ISSUE THREAD

**Issue by adfie** [noraesae/perfect-scrollbar#627]
hey thanks for made awesome scrollbar...
but how to make scrollbar keep always on top of content.
i just calling ajax with jquery when scrollbar touched bottom container then add new content to its element.
![untitled](https://cloud.githubusercontent.com/assets/18514068/23313567/d4f06ce0-faf0-11e6-8550-0566f1ba8927.png)

ps: sorry for my bad english...

**Comment by dehimer** [comment]
I think you should calc offset
element.scrollTop = X;
where X is listHeight - containerHeight

**Comment by noraesae** [comment]
It's the problem of z-index. PS do not enforce any z-index, and you can freely add your own style.

``` css
.ps__scrollbar-y-rail {
    z-index: 1000;
}
```

I'm not sure if it's better to add a default z-index to rails.

**Comment by bagaskarala** [comment]
i just meet this issue, so how to fix this?

**Comment by bagaskarala** [comment]
using javascript 
`window.document.getElementsByClassName('ps__scrollbar-y-rail')[1].style.zIndex = 1000;`

using vuejs
` this.$el.querySelector('.ps__scrollbar-y-rail').style.zIndex = 1000;`
