### ISSUE TITLE
[enhancement] Allow for use of clicking mousewheel to auto scroll

### ISSUE THREAD

**Issue by barrychapman** [noraesae/perfect-scrollbar#628]
Allow scrolling when clicking mousewheel turning on auto scroll. This functionality does not work natively with PS.

**Comment by noraesae** [comment]
We once had this, but it was buggy and resulted in removal. I may not add more scroll emulation further, as the current ps is tricky enough. If this kind of scroll is essential, native browser should be used. I'm really sorry for your inconvenience.
