### ISSUE TITLE
Erratic behavior on an unordered list within a scrollable region

### ISSUE THREAD

**Issue by barrychapman** [noraesae/perfect-scrollbar#629]
https://jsfiddle.net/xv0rrxv3/294/

If you view that fiddle - you will see the erratic behavior it creates on the scroll bars.

Thanks!

**Comment by barrychapman** [comment]
This may show it better:

https://jsfiddle.net/xv0rrxv3/297/

**Comment by noraesae** [comment]
It's because you already include scrollbars in HTML, which you shouldn't.

https://jsfiddle.net/xv0rrxv3/486/
