### ISSUE TITLE
SASS files not present in Zip Package and Final min.js not present in Repository

### ISSUE THREAD

**Issue by ldetomi** [noraesae/perfect-scrollbar#632]
Hi,
I'm new with this plugin. My first attempt is download zip package from [this link](https://github.com/noraesae/perfect-scrollbar/releases). Inside are present only CSS and JS files but not SASS versions of css.

Reading [FAQ](https://github.com/noraesae/perfect-scrollbar/wiki/FAQ) I see that to customize theme I should edit directly SASS code that is not present in Zip package.

Conversely, cloning repository in local environment, give me original SRC code but not final comiled ones (differently from other plugins on git, in which are present also SRC and DIST folders). I don't have node.js and Gulp to re-build starting by cloned env so I am unable to use this approach.

It would be possible to make coherent Zip package and Repository?

**Comment by noraesae** [comment]
I've added `/dist` to repo. Thanks for your opinion!
