### ISSUE TITLE
Display problem (text moving a millimeter when mouse hovered)

### ISSUE THREAD

**Issue by Mortens4444** [noraesae/perfect-scrollbar#645]
Hello!

First of all, thanks for this project, I really like it.
I created a web site, and I faced white the following problem: when I move the mouse over the div, which has the perfect-scrollbar, the content in the div move a little (but it is noticeable).
I checked the FAQ, and I searched the issues as well. Sorry that I haven't created a JSFiddle to reproduce the issue.

Here is the site, where you can check this issue: [http://w3.hdsnet.hu/mortens/](http://w3.hdsnet.hu/mortens/)

I'm looking forward to hear from you.
Best regards
Tibor

**Comment by Mortens4444** [comment]
I finally created a JSFiddle example: [https://jsfiddle.net/sgsj7ff1/](https://jsfiddle.net/sgsj7ff1/)

**Comment by Mortens4444** [comment]
I replaced the transorm: translate with flex, so it's working now on the web page.

**Comment by Mortens4444** [comment]
I created a sample from the fixed version: [https://jsfiddle.net/sgsj7ff1/2/](https://jsfiddle.net/sgsj7ff1/2/)

**Comment by noraesae** [comment]
I think it's a browser problem, concerning GPU/CPU rendering. Good to hear that it's resolved.
