### ISSUE TITLE
Can I place the scroll bar on the left side?

### ISSUE THREAD

**Issue by beerteam** [noraesae/perfect-scrollbar#647]
Good day, In documentation and FAQ haven't info about it.

**Comment by dbauszus-glx** [comment]
+1 This is a feature I very much would like to use as well. Currently I use jScrollPane for that reason alone. This works well but jScrollPane requires jQuery and I add jQuery for that reason alone to my project.

**Comment by bulbil** [comment]
@beerteam I have [a two column site](ulises.us) and have had success with placing the scrollbar on the left side. Below is the css I apply to the left column (updated for the 0.7 release).

```
// Perfect scrollbar overrides

.ps#left {

    .ps__scrollbar-y-rail{ left: 0; }
    .ps__scrollbar-x-rail{ display: none; }
}

.ps#right {

    .ps__scrollbar-y-rail{ right: 0.2rem; }
    .ps__scrollbar-x-rail{ display: none; }

}
```

**Comment by noraesae** [comment]
As described on the comment above, you can modify `.ps__scrollbar-y-rail` and `.ps__scrollbar-x-rail`. There is already an example for this.

https://github.com/noraesae/perfect-scrollbar/blob/master/examples/scrollbars-on-the-opposite-side.html
