### ISSUE TITLE
perfect-scrollbar's usage in vue

### ISSUE THREAD

**Issue by FreshCodeMan** [noraesae/perfect-scrollbar#649]
i want to use Ps in my project based on Vuejs,
i installed Ps by npm and then import it into my component. It init successfully,but it seems no style worked for Ps, could you give me a example usage of Ps working with Vuejs?
my code:
```
<template>
  <div class="contanier" ref="test">
    <ul>
      <li v-for="n in 100">{{n}}</li>
    </ul>
  </div>
</template>

<script>
  import Ps from 'perfect-scrollbar'
  export default {
    name: 'test',
    data () {
      return {
      }
    },
    methods: {
    },
    mounted(){
        Ps.initialize(this.$refs.test);
    }
  }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style>
  .contanier{
    width:300px;
    height:600px;
    overflow: auto;
    position: relative;
  }
```

**Comment by FreshCodeMan** [comment]
i solved this situation temporarily by load external css file,but i still dont know why the style doesnt work in that situation

**Comment by neozl24** [comment]
Hey, I met the same problem in my Vue.js project.  After initialization, the scroll bar does work but not appear. Instead, a blank area appear at bottom of my content, with the exact height of the container. 

Searching info on google and they usually tell that the key is to initialize at the right time or update the container. But for me, the problem doesn't seem on that.

After I find your issue, I try to write some external css which does work !!!  
Below is my key css code
`.ps__scrollbar-y-rail {
      position: absolute;
      width: 20px;
      right: 0;
      background-color: #ddd;
      .ps__scrollbar-y {
        position: relative;
        background-color: #aaa;
      }
    }`

**Comment by noraesae** [comment]
CSS is not automatically imported for Vue. Please include it manually or by giving source file path for single-file component.

**Comment by kiwicopple** [comment]
> CSS is not automatically imported for Vue. Please include it manually or by giving source file path for single-file component.

For those wondering how to do this, just add this somewhere to you App's scss:

`@import "../../node_modules/perfect-scrollbar/css/perfect-scrollbar.css";`
