### ISSUE TITLE
Fix ps__scrollbar-y-rail to top:0px;

### ISSUE THREAD

**Issue by Adnan-Oezsarigoel** [noraesae/perfect-scrollbar#651]
perfect-scrollbar don't work with stickySectionHeaders. Can you add an option to fix a scollbar-rail to 0px? I think then both plugins should work together fine.

I have created an own setting fixScrollRail and added the following line after initializing yRailOffset in line 1355 of perfect-scrollbar.jquery.js: 
`if (i.settings.fixScrollRail) yRailOffset.top = 0;`

**Comment by noraesae** [comment]
You can just modify CSS to do this.

fyi: https://github.com/noraesae/perfect-scrollbar/blob/master/examples/scrollbars-on-the-opposite-side.html

**Comment by Adnan-Oezsarigoel** [comment]
Your scrollbar rail top property changes with inline-css while scrolling. In combination with sticky headers it moves out of area. Adding any styles won't fix that.

**Comment by noraesae** [comment]
It sets a proper style values for `top` if `top` is set.

**Comment by noraesae** [comment]
Oh, I may have misunderstood. You're using it with `position: fixed`?

**Comment by Adnan-Oezsarigoel** [comment]
Yes, sticky headers force position:relative; to the wrapper, to put the header on top. But then the slider moves to fast. Therefore I add a property to your plugin. I wrote it in my first post.

**Comment by noraesae** [comment]
I have no idea of what's stickySectionHeaders. Not sure what it's doing, but if it's `position: relative`, not `fixed`, it may not have any problem. `yRailOffset.top = 0;` shouldn't be needed.

**Comment by Adnan-Oezsarigoel** [comment]
This Plugin http://polarblau.github.io/stickySectionHeaders/ uses overflow: hidden; and position: relative;. 

You can test it hear:
https://jsfiddle.net/Adnan_Oezsarigoel/0cL4pf5a/

**Comment by janizde** [comment]
I agree with @Adnan-Oezsarigoel, I also have the problem, that I cannot set the container to `position: relative;`. Just keeping `ps__rail-y` `top` style at 0 would fix the problem. I think the best solution would be to give plugin users the ability to intercept the styles of the generated dom elements.

Something like

```javascript
const container = document.getElementById('#container-with-position-other-than-relative');
new PerfectScrollbar(container, {
  interceptRailY: styles => ({ ...styles, top: 0 }),
});
```

**Comment by janizde** [comment]
FYI I solved it by just using a `top: 0 !important` in CSS. But anyway it would be nice to have more control over the scrollbar DOM elements if it's not a big performance deal

**Comment by Adnan-Oezsarigoel** [comment]
Wow, @janizde. Your fix is ways better then mine. Thank you.

**Comment by JordanSjodinFaithlife** [comment]
@utatti are you sure you should have closed this? Having a `relative` wrapper around the scrollable content is required for my use case, and would cut down on the fancy logic mutating `top` and `bottom` on the scroll rails.

Having a `relative` wrapper would mean you only need to set `top` to 0 and never think about it again. (Since the rail would be absolute relative to the non-scrollable portion)  Would you consider re-opening this issue?

**Comment by pathaksa** [comment]
I had the same issue and it solved with `top: 0px !important`

Not sure what'st the reason why `top` changes for  `.ps__rail-y`
