### ISSUE TITLE
[ps-scroll-y]how to get scroll distance

### ISSUE THREAD

**Issue by jslixiaolin** [noraesae/perfect-scrollbar#663]
hi,when i using the event ps-scroll-y.how can i know the scroll distance in y direction?
```
$(window).on('ps-scroll-y',function(){
   // is there any params that i can get scroll distance
})
```
thanks

**Comment by DMShamonov** [comment]
You need get '.ps__scrollbar-y' dom element and read this 'offsetTop' property. But perfect-scrollbar fires events before re-render scrollbar dom element, and so 'offsetTop' property has old value (value before re-rendering scrollbar dom element).

**Comment by noraesae** [comment]
You can just refer to `scrollTop` on `scroll` event.
