### ISSUE TITLE
PS fires events 'ps-scroll-up' and 'ps-scroll-down' before re-render dom elements

### ISSUE THREAD

**Issue by DMShamonov** [noraesae/perfect-scrollbar#667]
I'm want get current 'offsetTop' property for '.ps__scrollbar-y' dom element when PS fires 'ps-scroll-down' event. But PS fires events before re-render '.ps__scrollbar-y' dom elements, and so it's 'offsetTop' property has old value (before re-rendering). Why is this so?

https://jsfiddle.net/xv0rrxv3/428/ - after first event 'ps-scroll-down' I'm get offsetTop = 0 for '.ps__scrollbar-y' dom element, but I need offsetTop = 41 (it's gets after second 'ps-scroll-down' event).

**Comment by noraesae** [comment]
Duplicated #663
