### ISSUE TITLE
For infinite scroll 

### ISSUE THREAD

**Issue by sandeeproop** [noraesae/perfect-scrollbar#670]
Is there any way(event) or option in which i can trigger my server call to fetch more data before my y-scroll reaches  at end(for eg. 30px before reaching end).

**Comment by noraesae** [comment]
There's no specific event for that, but you can subscribe plain `scroll` event and check scrollY.

**Comment by sandeeproop** [comment]
Can you help me and let me know how to do that

**Comment by noraesae** [comment]
If you have a container div element, `.container`, you can hook `scroll` event and check the scroll top by the following code:

```js
const container = document.querySelector('.container');

container.addEventListener('scroll', () => {
    console.log(container.scrollTop);
});
```

**Comment by sandeeproop** [comment]
getScrollTriggerPoint(containerElem:any):boolean {
    let scrollBarElem = containerElem.querySelector('.ps__scrollbar-y');
    if(scrollBarElem) {
      let scrollBarHeight = scrollBarElem.style.height.split('px')[0];
      let contHeight = containerElem.clientHeight;
      let offSetTop = scrollBarElem.offsetTop;
      // console.log('offSetTop + scrollBarHeight',(offSetTop + scrollBarHeight));
      // console.log('contHeight - 10',contHeight - 30)
      if((parseInt(offSetTop) + parseInt(scrollBarHeight)) >= (parseInt(contHeight) - 30)) {
        return true;
      }
    }

    return false;
  }
I have used above code to determine 30px before reaching end 
and used (ps-scroll-down) event for handling that.
this works perfectly when user scroll slowly if user scroll fast this won't help.
any idea what i am doing wrong.
