### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by gvmohzibat** [noraesae/perfect-scrollbar#671]
I have this code in my script.js file:
``` javascript
var Ps = require("perfect-scrollbar");
require('perfect-scrollbar/jquery')($);
$('#scrollbar1').perfectScrollbar();
$('#scrollbar1').perfectScrollbar('update');
```
after loading the page my #scrollbar1 element has this properties:
```html
<div id="scrollbar1" class="ps ps--theme_default ps--active-y" data-ps-id="4cfdae94-73dd-af1d-87cf-5f4f81eb96a4">
```

and inside of it there are two elements ps__scrollbar-x-rail and ps__scrollbar-y-rail but I don't see any changes in my webpage! The element doesn't have any scrollbars and the content of it, is overflowed

**Comment by marko-hologram** [comment]
> The following requirements should meet.
* the container must have a 'position' css style.
* the container must be a normal container element.
* PS may not work well in body, textarea, iframe or flexbox.


Does you container element meet these Perfect Scrollbar requirements ?

**Comment by gvmohzibat** [comment]
Thanks for your reply.
The problem was with the css file and it wasn't loaded. I had to add this line of code to my sass file:
``` css
@import "~perfect-scrollbar/dist/css/perfect-scrollbar.css";
```

**Comment by mazeeblanke** [comment]
i have imported the css from cdn i see those classes in my element "ps ps--theme_default"  but the look/theme remains the same :(

**Comment by vislogurov** [comment]
I have the same issue http://s.csssr.ru/U0FMPH83W/20180111124136.png

**Comment by vm-bio** [comment]
Ich bin von Di, 09.01.2018 bis Mi, 21.02.2018 abwesend.




Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[utatti/perfect-scrollbar] Doesn't work (#671)" gesendet am 11.01.2018
10:43:56.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, während
diese Person abwesend ist.

www.biotronik.com 
BIOTRONIK - excellence for life 

BIOTRONIK SE & Co. KG 
Woermannkehre 1, 12359 Berlin, Germany 
Sitz der Gesellschaft: Berlin, Registergericht: Berlin HRA 6501 

Vertreten durch ihre Komplementärin: 
BIOTRONIK MT SE 
Sitz der Gesellschaft: Berlin, Registergericht: Berlin HRB 118866 B 
Geschäftsführende Direktoren: Dr. Daniel Bühler, Dr. Lothar Krings, Dr. Ralf Lieb, Thomas Simmerer 
This e-mail and the information it contains including attachments are confidential and meant only for use by the intended recipient(s); disclosure or copying is strictly prohibited. If you are not addressed, but in the possession of this e-mail, please notify the sender immediately and delete the document.
