### ISSUE TITLE
Scrolling up or down on a horizontal element becomes sticky on touchpad (Macbook)

### ISSUE THREAD

**Issue by danielhac** [noraesae/perfect-scrollbar#673]
Using the jsfiddle provided to us: [https://jsfiddle.net/DanielApt/gbfLazpx/]( https://jsfiddle.net/DanielApt/gbfLazpx/)

When I hover over the image and use my touchpad, it scrolls down just fine but it will not continue to scroll towards the bottom of the container unless I hover outside of the image and continue to scroll down.

This is the same while scrolling up.

Any help will be appreciated! Thanks!

**Comment by noraesae** [comment]
Please refer to the `wheelPropagation` option.
