### ISSUE TITLE
scrollbar not showing in correct position when refreshing page

### ISSUE THREAD

**Issue by scooterlord** [noraesae/perfect-scrollbar#83]
Hello and well done for the great job you have done so far!

I realized that when you have perfect scrollbar enabled for an element, you scroll down and then refresh the page, the scrollbar does not appear in the correct position until you scroll inside the element again. I have tried updating the scrollbar on document load but had no luck, so I thought I'd ask here as well. Any ideas?

**Comment by noraesae** [comment]
It seems it's been fixed in Firefox as well, at least in Firefox 37.0a2.
